### PR TITLE
fix(ScalarObservable): set _isScalar to false when initialized with a scheduler.

### PR DESCRIPTION
**Pull request by trxcllnt**
**Description:**
ScalarObservable's `_isScalar` flag was permanently `true`, even if initialized with a `scheduler`. This caused our internal `subscribeToResult` helper to short-circuit subscribing to the `ScalarObservable`, so the emission was never scheduled. This PR changes that.

**Related issue (if exists):**
None yet.

### CODE REVIEW

**Comment by kwonoj** [comment]
Can we think of some test cases for this? (not sure, just throwing out idea)

**Comment by blesh** [comment]
Agree. Should add a test or two

**Comment by blesh** [comment]
I'm going to add a couple of tests and merge this today. No worries, @trxcllnt

**Comment by blesh** [comment]
Merged as of bea15ca... thanks @trxcllnt!

**Pull request closed without merging**
