### PR TITLE
chore(package.json): add commit message format helper script

### PR DESCRIPTION
**Pull request by kwonoj**
This PR adds one additional script command `npm run commit`, which invokes cli based step by step commit message formatter follows convention in [contributing guideline](https://github.com/ReactiveX/RxJS/blob/master/CONTRIBUTING.md#-commit-message-guidelines) to help anyone who are new to codebase can easily compose commit message.

See how does wizard works in action:
commit

**What's required if I don't need this helper but I can control git by myself completely?**
: Do not need anything. Unless explicitly invoke `npm run commit` command, helper won't be able to do anything. This applies GUI client also, currently there isn't way hook this helper with GUI client.

### CODE REVIEW

**Comment by staltz** [comment]
Love it

**Comment by luisgabriel** [comment]
:+1:

**Comment by blesh** [comment]
This is very cool.  @igorminar @jeffbcross you might benefit from this module on the angular project if you're not already using it.

**Comment by kwonoj** [comment]
Honestly, I am inspired by angular repo's open issue (https://github.com/angular/angular.js/issues/12730) and adopted into here first :wink:

**Comment by blesh** [comment]
merged with 5f68356... great stuff, @kwonoj

**Comment by jimthedev** [comment]
@kwonoj per your comment about Git GUIs I've opened https://github.com/commitizen/cz-cli/issues/45 to track this idea. Thanks!

**Comment by kwonoj** [comment]
@jimthedev It is so appreciate! I was actually curious if it could be possible.

**Comment by jimthedev** [comment]
@kwonoj I think it is possible assuming that they provide us some hook that we could wrap. I've not done much native node development so I'd probably reach out to community members on how to implement it, but as long as they implement the inquirer interface then I can see it being possible. 

Thanks again for putting in this PR. RxJS is such a freaking awesome project.

**Pull request closed without merging**
