### PR TITLE
chore(typings): add typings for fromNodeCallback

### PR DESCRIPTION
**Pull request by david-driscoll**

### CODE REVIEW

**Comment by blesh** [comment]
GIt isn't doing us any favors here with the diff. It _looks_ like all you did was add typings to the `create` function, is that right?

**Comment by david-driscoll** [comment]
Yeah, they're similar to the typings for `BoundCallbackObservable` as done for https://github.com/ReactiveX/RxJS/commit/7c9547a246ef23a82b821844a867e15a2d9e370c

**Comment by blesh** [comment]
It _looks_ okay. But since the diff is so crazy red/green it's hard to tell what's changed exactly. @kwonoj or @staltz can you give it a second pair of eyes?

**Comment by david-driscoll** [comment]
I wonder if somehow different line endings slipped in?

**Comment by david-driscoll** [comment]
I went and double checked... it's not line endings from what I can tell anyway.  Everything in using `LF`.

**Comment by kwonoj** [comment]
Looks good to me too, not sure why diff have troubles though. I've manually created small diff below for reference. Basically this PR adds up n-number param signatures for `create`.

```diff
  /* tslint:disable:max-line-length */
+  static create<R>(callbackFunc: (callback: (err: any, result: R) => any) => any, selector?: void, scheduler?: Scheduler): () => Observable<R>;
+  static create<T, R>(callbackFunc: (v1: T, callback: (err: any, result: R) => any) => any, selector?: void, scheduler?: Scheduler): (v1: T) => Observable<R>;
+  static create<T, T2, R>(callbackFunc: (v1: T, v2: T2, callback: (err: any, result: R) => any) => any, selector?: void, scheduler?: Scheduler): (v1: T, v2: T2) => Observable<R>;
+  static create<T, T2, T3, R>(callbackFunc: (v1: T, v2: T2, v3: T3, callback: (err: any, result: R) => any) => any, selector?: void, scheduler?: Scheduler): (v1: T, v2: T2, v3: T3) => Observable<R>;
+  static create<T, T2, T3, T4, R>(callbackFunc: (v1: T, v2: T2, v3: T3, v4: T4, callback: (err: any, result: R) => any) => any, selector?: void, scheduler?: Scheduler): (v1: T, v2: T2, v3: T3, v4: T4) => Observable<R>;
+  static create<T, T2, T3, T4, T5, R>(callbackFunc: (v1: T, v2: T2, v3: T3, v4: T4, v5: T5, callback: (err: any, result: R) => any) => any, selector?: void, scheduler?: Scheduler): (v1: T, v2: T2, v3: T3, v4: T4, v5: T5) => Observable<R>;
+  static create<T, T2, T3, T4, T5, T6, R>(callbackFunc: (v1: T, v2: T2, v3: T3, v4: T4, v5: T5, v6: T6, callback: (err: any, result: R) => any) => any, selector?: void, scheduler?: Scheduler): (v1: T, v2: T2, v3: T3, v4: T4, v5: T5, v6: T6) => Observable<R>;
+  static create<T>(callbackFunc: Function, selector?: void, scheduler?: Scheduler): (...args: any[]) => Observable<T>;
+  static create<T>(callbackFunc: Function, selector?: (...args: any[]) => T, scheduler?: Scheduler): (...args: any[]) => Observable<T>;
  /* tslint:enable:max-line-length */
  static create<T>(callbackFunc: Function,
+-                selector: Function | void = undefined,
                   scheduler?: Scheduler): Function {
    return (...args: any[]): Observable<T> => {
+-      return new BoundNodeCallbackObservable(callbackFunc, <any>selector, args, scheduler);
    };
  }
```

**Comment by blesh** [comment]
Git's just weird with diffs at times. I'm not sure what happened either. I'm not too worried about it. Two sets of eyes will probably do the trick.

**Comment by kwonoj** [comment]
Merged with 8dd5620, thanks @david-driscoll , and @blesh for reviewing.

**Pull request closed without merging**
