### PR TITLE
chore(docs): revert gh-pages with banner to v6 firebase

### PR DESCRIPTION
**Pull request by pertrai1**
**Description:**

Possible solution to those who are able to find more helpful information from the old docs while still having a clearly visible callout to the newer docs that are being developed.

screen shot 2018-09-03 at 2 42 16 am

**Related issue (if exists):**
#4004

### CODE REVIEW

**Comment by benlesh** [comment]
The problem is the old docs have outdated information on them. I'm not sure it's going to make things less confusing to have two sets of documentation on them.

We should identify what exactly people are missing from the old docs and port that, rather than have two sets of documentation. It took _years_ for people to start finding the RxJS 5/6 docs instead of always going to the v4 docs in the old repository.

**Comment by benlesh** [comment]
If we *did* go with two sets of docs (which I'm _not_ in favor of) I think it would be better to have the new docs be the primary, since most people are on v6.

**Comment by pertrai1** [comment]
So how about we go with the docs being as they are with the redirect and then a link to take someone to previous docs if they need them?

**Comment by JWO719** [comment]
Unfortunately the docs couldn't be deployed recently due to some mistakes I made with the deployment script. We are currently trying to find the problem. But I agree with Ben it would be mostly confusing for people. And we anyway wanted to migrate the stuff of the old docs. Maybe we should focus on this?

**Comment by pertrai1** [comment]
@JWO719 are you saying that we should not worry about having a way for others to find the older documentation?

**Comment by JWO719** [comment]
No you slightly misunderstood me. It's not about being worried or not, I just think that this is not the best approach to solve this problem. The problem with the old docs is that it is sometimes rxjs 5 related and sometimes v6. I would prefer having one strict version and a proper documentation of that. If one  has a proper v 6 documentation and really needs infos about v5, that step backwards is not that complicated. Therefore I would prefer improving the new docs with the stuff that is needed by the community and maybe add a chapter about things changed in v6 from v5.

**Comment by pertrai1** [comment]
Ok, sounds good. Best to go ahead and close this PR.

**Comment by JWO719** [comment]
Don't get me wrong, I really welcome any suggestions and your initiativ

**Comment by benlesh** [comment]
Thank you for your work, @pertrai1. I'm going to close this one for now.

**Comment by dietergeerts** [comment]
I also think one place for docs is better, BUT almost everything is missing..... No marble diagrams, no examples, descriptions gone from a LOT of methods etc....  I wonder why this happened? Are the docs not manually tested to see if the docs written actually end up on the docs site?

examples:
- https://rxjs-dev.firebaseapp.com/api/index/function/from (only typings, you can't even click through to find out what all the types are)
- shareReplay, same
- ...

**Pull request closed without merging**
