### PR TITLE
chore(package.json): simplify chained npm scripts

### PR DESCRIPTION
**Pull request by kwonoj**
**Description:**

This PR introduces small npm cli tool named `npm-run-all` (https://www.npmjs.com/package/npm-run-all) allows to chain npm scripts without chaining it via && everytime. It's just small cosmetic changes, but simplifies npm script to read. Few more fancy features like parellel execution is also supported but not using it for now.

`npm-run-all` works on Windows/*nix both.

**Related issue (if exists):**
none

### CODE REVIEW

**Comment by trxcllnt** [comment]
@kwonoj also, once linting (and perhaps one of the compilation steps) is done, we could use [parallelshell](https://www.npmjs.com/package/parallelshell) to run the  rest of the compilation steps in parallel to speed up the total build time.

**Comment by kwonoj** [comment]
@trxcllnt thanksfully `npm-run-all` has parallel option (`npm-run-all clean --parallel "build:* -- --watch"`) :) I'd like to test parallel execution bit more thoroughly before introduce it.

**Comment by kwonoj** [comment]
I'll check this in later today to tomorrow if there isn't other suggestion.

**Comment by kwonoj** [comment]
Merged with 6f7c767. @blesh @staltz @trxcllnt @david-driscoll @luisgabriel @saneyuki , may need trigger `npm install` .

**Pull request closed without merging**
