### PR TITLE
docs(operators): write comprehensive docs on delay() and switch()

### PR DESCRIPTION
**Pull request by staltz**
**Description:**
I'm starting to document each operator in details and this first PR is just to demonstrate my general approach to document an operator. There are two operators documented here: `delay` and `switch`. The structure is:

1. **Short headline** describing the operator
2. **Short "informal" description** of the operator. Think of this as "the operator explained for dummies". Rx4 docs suffered from overly-technical and accurate descriptions which made it hard for normal humans to parse in their brains. I'm trying to provide both formal and informal descriptions.
3. **Marble diagram**
4. **Longer formal/technical description**
5. **Signature**: params and return
6. **Example code** that actually makes sense in the real world
7. **Link to the tests**

Here is how `delay` and `switch` look like. @blesh @trxcllnt @jhusain your feedback here is important, whether this structure is good. If it's good, I'll just go ahead and do this for all operators.

screen shot 2016-03-15 at 17 24 34
  
screen shot 2016-03-15 at 17 25 55

**Related issue (if exists):**
#1060, #1242

### CODE REVIEW

**Comment by blesh** [comment]
Looks great, @staltz.

**Comment by frederikschubert** [comment]
I am relatively new to reactive programming and if all documentation was like your two examples it would have  made my life much easier! 👍

**Comment by staltz** [comment]
Good point @frederikschubert

**Comment by blesh** [comment]
This is a point for later, but can we have `higher-order observable` link to a glossary somewhere that defines this for people? There are a lot of people who don't know what a "higher-order" function is.

Otherwise, LGTM.

**Comment by staltz** [comment]
Good point, and yes, let's do that.
ESDoc has non-customizable section structure, so we have to choose whether to put a guide on `higher-order` either in *Manual* or *Tutorial*. Anyway, it'll exist.

**Comment by kwonoj** [comment]
Merged with 1c4f9f5, thanks @staltz

**Pull request closed without merging**
