### PR TITLE
test(concat): add test against breaking unsubscription chain

### PR DESCRIPTION
**Pull request by luisgabriel**
Relates to #875.

### CODE REVIEW

**Comment by blesh** [comment]
merged with 2220faa... thanks @luisgabriel

**Comment by staltz** [comment]
This was duplicate work, now we got the same test twice in this file.

**Comment by kwonoj** [comment]
@staltz Should one of test to be removed?

**Comment by staltz** [comment]
I'll send a PR to remove duplicates anywhere.

**Comment by luisgabriel** [comment]
@staltz Indeed. I opened this PR before the lots of PRs you opened. I was not sure how it was handled.

**Comment by blesh** [comment]
Doh

**Pull request closed without merging**
