### PR TITLE
Update migration docs

### PR DESCRIPTION
**Pull request by blesh**
The migration docs need a little love. The idea here was just to make it easier to find operators that you're trying to migration, and provide a little more guidance and context for people trying to deal with migrating operators we aren't going to add or haven't added yet.

### CODE REVIEW

**Comment by jayphelps** [comment]
Love love love this. How bout we change `Not yet implemented` to just `No longer implemented`. Because the former heavily implies to people that we _will_ implement it soon; we've had several people point to it as justification. We certainly may add some of them, either to core or to some future addon libraries, but I don't want to imply anything. If you're good with that, I'm happy to change it for you, just reply 👍

**Comment by kwonoj** [comment]
I think this PR is ready to check in but only LGTM prevents it? (hope my LGTM unlocks this)

**Comment by jayphelps** [comment]
@kwonoj I still think we should change `Not yet implemented` to `No longer implemented` or something else non-committal sounding. Maybe `No longer provided`. Any thoughts Mr. @blesh?

**Comment by kwonoj** [comment]
@jayphelps totally agree to replace string other than current one. Not sure about what would be best to describe it though. (maybe just big red large **'X'**?)

**Comment by blesh** [comment]
@jayphelps updated... what do you think?

**Comment by jayphelps** [comment]
LGTM

**Pull request merged**
