### PR TITLE
build(docs): remove yarn

### PR DESCRIPTION
**Pull request by JWO719**
As discussed in #3771 this pr removes yarn as package manager for the docs and make use of npm to be consistent.

### CODE REVIEW

**Comment by ladyleet** [comment]
@JWO719 thank you *so* much for helping and contributing!

**Comment by JWO719** [comment]
It's a pleasure :)

**Comment by benlesh** [comment]
Thanks again, @JWO719

**Comment by ladyleet** [comment]
🎉

**Pull request merged**
