### PR TITLE
test(bindCallback): replaced test case under bindCallback test

### PR DESCRIPTION
**Pull request by kwonoj**
### NOT TO MERGE

to observe weirdness of jasmine's intermittent failure. Moved test case back, and local & travis both works fine - anyone interested just could give a quick try by pull this PR if this works on different system (mostly mac maybe?) if it has differences.

I'll leave this PR around day and close it without merging in this weekend.

### CODE REVIEW

**Comment by blesh** [comment]
Did you observe the behavior, @kwonoj?

**Comment by kwonoj** [comment]
No, that was reason I created PR - on local machine & travis both, issue wasn't able to reproduced.

**Comment by kwonoj** [comment]
to clarify, 
> weirdness of jasmine's intermittent failure. 

means it's quite random and for some reason seems working again. PR was created to show it's working on travis and anyone would like try on local, not to be merged actually.

**Comment by kwonoj** [comment]
Closing to not to be merged.

**Pull request closed without merging**
