### PR TITLE
Write JSDoc for merge*, switch*, concat*, exhaust*

### PR DESCRIPTION
**Pull request by staltz**
**Description:**
write comprehensive JSDoc on the merge operator family.
Also rename _nested_ Observable to _inner_ Observable where applicable.

**Related issue:**
https://github.com/ReactiveX/rxjs/issues/1502

### CODE REVIEW

**Comment by staltz** [comment]
Updated this PR to have JSDoc content written for merge, mergeMap, mergeMapTo, mergeAll, switch, switchMap, switchMapTo, concat, concatAll, concatMap, concatMapTo, exhaust, exhaustMap.

**Comment by blesh** [comment]
LGTM

**Comment by kwonoj** [comment]
Seems other document checkin makes this rebased again..

**Comment by staltz** [comment]
I rebased like 1 second ago.

**Comment by kwonoj** [comment]
Merged with e310ce0, thanks @staltz (and sorry for rebase, rebase, rebase..)

**Pull request closed without merging**
