### PR TITLE
refactor(Observable): remove fromArray operator

### PR DESCRIPTION
**Pull request by luisgabriel**
**Description:**
Remove `fromArray` operator as it's deprecated in RxJS 4 (https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/fromarray.md).

### CODE REVIEW

**Comment by luisgabriel** [comment]
cc/ @blesh as this is a breaking change.

**Comment by kwonoj** [comment]
Just side note - there was proposed PR https://github.com/ReactiveX/rxjs/pull/251 removed `fromArray` and `fromArray` both, per issue https://github.com/ReactiveX/rxjs/issues/239 but closed due to perf differences between `from` to individual. 

Codebase has been changed & evloved over time, might be changed - can we run some quick perf just in case?

**Comment by kwonoj** [comment]
Maybe it's ok since old perf comparison was fromArray vs. fromArray and RxJS 4's fromArray's deprecated anyway.

**Comment by luisgabriel** [comment]
Thanks, @kwonoj. I was not aware of these previous discussions. 

I'm ok with whatever you guys decide. My main motivation to create this PR was the fact that `fromArray` is currently deprecated on RxJS 4. Feel free to close this PR if needed.

**Comment by kwonoj** [comment]
> currently deprecated on RxJS 4

: Yes, previous PR was created before it's deprecated in RxJS 4.

**Comment by blesh** [comment]
I'm generally for this change, I think. Curious what the perf differences are.

**Comment by blesh** [comment]
Either way, I'm going to push this through today.

**Comment by blesh** [comment]
Merged with b32930f... thanks @luisgabriel

**Pull request closed without merging**
