### PR TITLE
add dgeni config

### PR DESCRIPTION
**Pull request by robwormald**
take 2

### CODE REVIEW

**Comment by robwormald** [comment]
note: this includes 3 dgeni packages - rxjs, typescript and links. i'll open a PR to add typescript to dgeni packages per @petebacondarwin's suggestion and remove it from this repo later

**Comment by blesh** [comment]
Great, reviewing this  in a little bit.

**Comment by blesh** [comment]
Do you have instructions on using this? We should probably be able to demonstrate this documenting one class (Observable for example) and one operator (maybe filter?). Just something basic as a starting point. Until it's able to do that, we probably shouldn't merge it into master.

**Comment by robwormald** [comment]
closing in favor of #294 - will revisit later

**Pull request closed without merging**
