### PR TITLE
Improve readability of UnsubscriptionError

### PR DESCRIPTION
**Pull request by blesh**
**Description:**
Makes the logged error message from `UnsubscriptionError` more readable by adding the messages from it's inner errors.

Also refactors UnsubscriptionError to be in it's own module.

**Related issue (if exists):**
#1590

### CODE REVIEW

**Comment by blesh** [comment]
cc/ @juliemr

**Comment by kwonoj** [comment]
Is this may clears https://github.com/ReactiveX/rxjs/issues/1534 as well?

**Comment by juliemr** [comment]
I approve of this change and its test error messages.

**Comment by blesh** [comment]
merged with dd01279

**Pull request closed without merging**
