### PR TITLE
build: move index.ts to operators.ts to avoid node module resolution …

### LINKED ISSUE #2971: Error looking for rxjs/operators.js
**RxJS version: 5.5.0 ** 

**Additional information:**
It looks like there is still one place using the old operators file (src/observable/dom/AjaxObservable.ts) line 7: import { map } from '../../operators';

### PR DESCRIPTION
**Pull request by jasonaden**
…in SystemJS

Fixes #2971, #2996, #3011

### CODE REVIEW

**Comment by ViictorG1** [comment]
@jasonaden Was there a new version with the fix?

**Comment by jasonaden** [comment]
@ViictorG1 There will be a new version with this and other fixes, yes. It should end up in `5.5.3`.

**Comment by benlesh** [comment]
Merged and cherry-picked into master as well.

**Comment by danwulff** [comment]
@jasonaden @kwonoj @benlesh any news on when 5.5.3 will be cut?

**Pull request merged**
