### PR TITLE
chore(package.json): bump up version of remap-istanbul, commitizen

### PR DESCRIPTION
**Pull request by kwonoj**
relates to #633 

Bumped up version of `remap-istanbul` added requested changes of verbose output if remapping fails.
+Bonus bump up for `commitizen`.

### CODE REVIEW

**Comment by blesh** [comment]
merged with 9f0e6be... thanks @kwonoj!

**Comment by blesh** [comment]
This actually broke the build and I had to revert the change. :\ Something weird with istanbul. No biggy, we'll sort it out.

**Comment by kwonoj** [comment]
@blesh Yes, also noticed travis was unhappy. It's because this PR makes `remap-istanbul` speaks out loud when it fails, instead of keep silence, cases of intermittent coverage reporting failures.

Just looked at it and see failures as below
>node lib/stage_sourcemap.js && remap-istanbul -i coverage/coverage.json -o coverage/coverage-remapped.json && remap-istanbul -i coverage/coverage.json -o coverage/coverage-remapped.lcov -t lcovonly && remap-istanbul -i coverage/coverage.json -o coverage/coverage-remapped -t html
Error: Could not find file: "/home/travis/build/ReactiveX/RxJS/dist/cjs/util/ArgumentOutOfRangeError.js.map"
    at readJSON (/home/travis/build/ReactiveX/RxJS/node_modules/remap-istanbul/lib/remap.js:133:11)
    at /home/travis/build/ReactiveX/RxJS/node_modules/remap-istanbul/lib/remap.js:170:21
    at Array.forEach (native)
    at /home/travis/build/ReactiveX/RxJS/node_modules/remap-istanbul/lib/remap.js:153:22
    at Array.forEach (native)
    at remap (/home/travis/build/ReactiveX/RxJS/node_modules/remap-istanbul/lib/remap.js:152:12)
    at /home/travis/build/ReactiveX/RxJS/node_modules/remap-istanbul/bin/remap-istanbul:121:19
    at process._tickCallback (node.js:368:9)
    at Function.Module.runMain (module.js:469:11)
    at startup (node.js:136:18)

Will investigate further why this is happening.

**Comment by kwonoj** [comment]
Updated issue https://github.com/ReactiveX/RxJS/issues/633. I'd like to suggest defer this PR after get conclusion of https://github.com/ReactiveX/RxJS/issues/663. If all build generated via typescript, this PR can be discarded.

**Comment by kwonoj** [comment]
Marked as blocked due to https://github.com/ReactiveX/RxJS/pull/664. If it's merged, I'll close this PR without merging.

**Comment by kwonoj** [comment]
Closing this since `remap-istanbul` is not required anymore.

**Pull request closed without merging**
