### PR TITLE
docs(manual): write content for scheduler.md

### PR DESCRIPTION
**Pull request by staltz**
**Description:** Write documentation content on Schedulers, for the docs site.

**Related issue (if exists):**
#1060, #1242

### CODE REVIEW

**Comment by mattpodwysocki** [comment]
LGTM.  I'd also include the Virtual Time Scheduler as well as TestScheduler stuff in there as well as those are scheduler instances you can use.  I'd also add a little blurb as to why the schedulers are there such as enabling virtual time.  In addition, if we're going to have a section of testing, we should link to that along with any notion of a virtual time or test scheduler

**Comment by staltz** [comment]
I absolutely agree. The whole Virtual Time Scheduler story is not addressed in this PR but it'll get its own PR. One reason why VT Scheduler was not listed alongside `asap`, `async` and others is that currently even in the API they are not available under `Rx.Scheduler.*`.

**Comment by mattpodwysocki** [comment]
@staltz I guess this is a question then for @trxcllnt then about having things like `Scheduler.requestAnimationFrame` and others here or are they in DOM specific documentation?

**Comment by staltz** [comment]
Hard to tell in which category things fit.

**Comment by kwonoj** [comment]
Merged with 9a9baac, thanks @staltz

**Pull request closed without merging**
