### PR TITLE
feat(observable): add Observable.forkJoin

### PR DESCRIPTION
**Pull request by blesh**

### CODE REVIEW

**Comment by mattpodwysocki** [comment]
@blesh not a fan of this naming here.  Also, the forkJoin should also take a selector function at the end as the current implementation does.

**Comment by blesh** [comment]
@mattpodwysocki ... I don't have a problem with what you're saying. Changing it to `all` was a request from multiple people. Perhaps it's worth just aliasing? [FWIW, the selector function isn't documented in current Rx](https://github.com/Reactive-Extensions/RxJS/blob/de3d945cf9cea8e78d61486e9220f10846ce3463/doc/api/core/operators/forkjoin.md)

**Comment by blesh** [comment]
@mattpodwysocki ... also I'm not seeing the selector function you're talking about in the current implementation: https://github.com/Reactive-Extensions/RxJS/blob/de3d945cf9cea8e78d61486e9220f10846ce3463/src/core/linq/observable/forkjoin.js

**Comment by blesh** [comment]
@jayphelps suggested `joinLast` as another alternative. `forkJoin` just doesn't make sense to me, personally. But if I'm alone in that sentiment, then I'm happy to leave it `forkJoin`.

**Comment by blesh** [comment]
Changed `all` back to `forkJoin` since there were no strong opinions about it.

**Pull request merged**
