### PR TITLE
test(skipUntil): add micro-benchmark performance test for skipUntil operator

### PR DESCRIPTION
**Pull request by kwonoj**
Trying to cover https://github.com/ReactiveX/RxJS/issues/350.

### CODE REVIEW

**Comment by blesh** [comment]
from now on, can we label test-related commits with `test(skipUntil): yadda`? I just noticed the conventional changelog generator was omitting ones that started with `chore()`

**Comment by kwonoj** [comment]
Sure, shall I change this commit's label also?

**Comment by kwonoj** [comment]
Actually, just did and update PR with suggested commit message.

**Comment by blesh** [comment]
merged with 7ce1486

thanks, @kwonoj!

**Pull request closed without merging**
