### PR TITLE
feat(reduce): add thisArg parameter

### PR DESCRIPTION
**Pull request by luisgabriel**
Adds `thisArg` as the third argument to have symmetry with native Array.prototype.reduce().

Relates to #878 and #996.

### CODE REVIEW

**Comment by blesh** [comment]
LGTM

**Comment by luisgabriel** [comment]
Just updated with a bugfix on ScalarObservable::reduce and adding a test case to cover it.

**Comment by kwonoj** [comment]
Looks good to me too. merging..

**Comment by mattpodwysocki** [comment]
@kwonoj please do not merge

**Comment by kwonoj** [comment]
@mattpodwysocki OK, holding. any concerns?

**Comment by mattpodwysocki** [comment]
@kwonoj yes, see above comment.  This is an unneeded PR.

**Comment by luisgabriel** [comment]
Fair enough. I think I saw `reduce` in some issue. Sorry about that.

**Comment by kwonoj** [comment]
Whew, appreciate @mattpodwysocki for catching and pointing this out. I could make mistake.

**Comment by blesh** [comment]
:+1: thanks @mattpodwysocki

**Pull request closed without merging**
