### PR TITLE
feat(dematerialize): add dematerialize operator

### LINKED ISSUE #391: Comprehensive marble tests for materialize
Should duplicate the current RxJS 3/4 tests

Should adhere to our contribution guidelines and operator authoring docs.

### PR DESCRIPTION
**Pull request by kwonoj**
- add dematerialize operator
- add marble test case for materialize, dematerialize operator

closes #391, #475 

Effort to try close above 2 opened issues. Migrated RxJS4 tests for `materialize` operator, added coverage for `dematerialize` as well.

### CODE REVIEW

**Comment by blesh** [comment]
@kwonoj, can you break this into two commits? I tried to do it myself, but I can't do it without putting the commits under my name.

basically it's just `git reset HEAD~`, then `git add` the files individually before your commit.

The two commits I'd like are:

1. feat(dematerialize): add demat... (your text here)
2. test(materialize): add tests for ... (your text here)

.. be sure to include the issue numbers they close.

Again, I'm happy to do this for you, I just don't want you to lose your github "cred". ;)

**Comment by kwonoj** [comment]
Sure, I'll give it a try and update PR.

**Comment by kwonoj** [comment]
Update PR to contain 2 separated commits for adding `dematerialize` operator and expanding test coverage for `materialize`.

**Comment by blesh** [comment]
Merged with ff1a7f9! Thanks, as always @kwonoj. :)

**Pull request closed without merging**
