### PR TITLE
refactor(Rx): import missing pairwise operator

### PR DESCRIPTION
**Pull request by jmurzy**
:beers:

### CODE REVIEW

**Comment by luisgabriel** [comment]
Good catch. ;)

**Comment by kwonoj** [comment]
@jmurzy , appreciate for taking time to create PR.

So far I remember, `pairwise` is currently exported under `Rx.KithenSink`, and core `Rx` module does not include it per https://github.com/ReactiveX/RxJS/pull/1047. Let me cc @blesh to get right confirmation on those before proceeding this PR further.

**Comment by jmurzy** [comment]
@kwonoj — Ah, completely missed that discussion. Thanks!

**Comment by justinwoo** [comment]
Yeah, as a non-essential operator, we didn't add `pairwise` to the core operators. Should work in KitchenSink though. Pairwise commit: https://github.com/ReactiveX/RxJS/commit/1432e594a18590881879498578f4fd7bf28a8c00

**Comment by kwonoj** [comment]
@justinwoo , Thanks for confirmation.

@jmurzy , would it be ok for you to close this PR? Again, it's appreciate for effort to contribute and hope to have more contributions further :)

**Comment by jmurzy** [comment]
Done.

**Pull request closed without merging**
