### PR TITLE
Initial configuration for docs app based off aio 

### PR DESCRIPTION
**Pull request by ashwin-sureshkumar**
This is the initial docs app for extracting documentation from source code. 
This app is based of aio and contains most of the configuration and data. 
Next tasks are to remove unused configuration, update branding and content for rxjs

To run docs, `cd docs_app`

`yarn docs` 

`yarn start`

### CODE REVIEW

**Comment by sumitarora** [comment]
@ashwin-sureshkumar 👍

**Comment by JWO719** [comment]
For me it looks good. How to proceed? Put it on a seperate branch, or fork, or directly into master?

**Comment by benlesh** [comment]
Whoa... 5,000+ files, >300,000 lines of code?. I'm not sure where to start to review this, haha. 

Maybe we *should* put this in another branch... :\

I'm going to think about this over the weekend and get back to you, @ashwin-sureshkumar

**Comment by ashwin-sureshkumar** [comment]
@benlesh I agree, As I had mentioned in chat we can work of branch or fork to strip down further. 

But just for your info, there are two commits in this PR. 

First commit is straight move of aio into rxjs with no changes. This acts as base (this code has been approved/merged into angular repo)

Second commit is a very small commit which is the changes and configuration changes needed for rxjs.

**Comment by benlesh** [comment]
@ashwin-sureshkumar ... I recommend working in the branch on your fork until this is stripped down to *just* be what's required for RxJS without all of the AIO stuff cooked in. Once we're in that place... the *minimal* docs, we can merge it into master here.

**Comment by ashwin-sureshkumar** [comment]
@benlesh  - Perfect. 

Will co-ordinate with the rest of the learning team to get these broken up. 
@sumitarora @knittingcodemonkey @btroncone @JWO719

**Comment by benlesh** [comment]
@ashwin-sureshkumar shall I close this until you're ready?

**Comment by ashwin-sureshkumar** [comment]
@benlesh Sorry I meant too. I lost track.

**Pull request closed without merging**
