### PR TITLE
Angular 9 update

### PR DESCRIPTION
**Pull request by ajitsinghkaler**
**Description:**
Angular 9 has many new features. Update from angular 8 to angular 9 of the docs_app.

**Related issue (if exists):**

### CODE REVIEW

**Comment by niklas-wortmann** [comment]
This is fantastic, thanks a lot for your pr. I will take a look at it and give you feedback within the next days!

**Comment by niklas-wortmann** [comment]
@ajitsinghkaler again thanks a lot for this pr. Code-vise it looks pretty good and I would love to merge this but I noticed that the tests are not working. On the same time I noticed that tests and listing are failing in master right now. I am taking care of listing and the tests in master, could you take care of the tests in this branch afterwards?

**Comment by niklas-wortmann** [comment]
Ok tests and linting for the docs are fixed now. Could you rebase and take care of the failing tests in this branch. It seems like the tests might be a little bit flaky so if you stumble across something weird just let me know

**Comment by ajitsinghkaler** [comment]
@niklas-wortmann can you please explain more what do you mean by taking care of tests ans listing on this branch

**Comment by niklas-wortmann** [comment]
Sure so I already took care of linting, so as soon as you rebased master in this branch there shouldn't be any listing issues (in case you didn't introduce new ones). Additionally, I noticed that tests were failing in this branch, but also some were failing in master. I took care of the ones that were broken in master, so also for those you need the new changes from the master branch. But there were more tests failing in your branch and I'd appreciate if you could take care of those. If you need any kind of help, don't hesitate to ask me.

Did that clarify the problem?

**Comment by ajitsinghkaler** [comment]
You were writing listing actually you men listing. That created all the confusion. yeah I'll have a look and let you know

**Comment by ajitsinghkaler** [comment]
@niklas-wortmann I found that most of the failures were in app.component.spec.ts I think createTestingModule is not working right. Will tell you details after more investigation

**Comment by ajitsinghkaler** [comment]
If you can point out somewhere It will be really helpful

**Comment by niklas-wortmann** [comment]
@ajitsinghkaler I will directly contact you on AngularNation, that's probably easier

**Comment by ajitsinghkaler** [comment]
@niklas-wortmann the failure in CI is because of typescript 3.9 we run tests on latest ts and the last commit on master was tested with ts 3.8 and this one is tested with 3.9

**Comment by ajitsinghkaler** [comment]
@niklas-wortmann your test changes LGTM. You can merge this.

**Comment by ajitsinghkaler** [comment]
@niklas-wortmann is there a blocker for this pr

**Comment by niklas-wortmann** [comment]
Thanks a lot for the work you put into this! happy that it is merged now

**Comment by ajitsinghkaler** [comment]
Thanks @niklas-wortmann

**Pull request merged**
