### PR TITLE
Correct takeUntil comment - does not stop taking values if notifier completes without emitting

### PR DESCRIPTION
**Pull request by jeffbski**
If this takeUntil test is correct then I believe the comment is wrong, it will not stop taking values if the notifier completes without emitting any values (empty).

https://github.com/ReactiveX/rxjs/blob/master/spec/operators/takeUntil-spec.ts#L38-L48

### CODE REVIEW

**Comment by kwonoj** [comment]
Not sure why but build failed by this change? 🤔

**Comment by jeffbski** [comment]
It looks like maybe it was due to trailing whitespace in a comment line. I have fixed that line so hopefully it will build properly now.

**Comment by aciccarello** [comment]
For some reason I'm not seeing this change in the online docs. Has the website been updated?

**Comment by frederikprijck** [comment]
When is this change going to be visible on the docs so that https://github.com/ReactiveX/rxjs/issues/2160 can be closed (and the docs are correct)?

http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html#instance-method-takeUntil still mentions 

> takeUntil subscribes and begins mirroring the source Observable. It also monitors a second Observable, notifier that you provide. If the notifier emits a value **or a complete notification**, the output Observable stops mirroring the source Observable and completes.

**Pull request merged**
