### PR TITLE
chore(dep): update benchpress for compat with protractor 2.5. See ang…

### LINKED ISSUE #1228: Performance tests interpretation
I'm trying to run the perf tests on the following setup:

 - Windows 10
 - Protractor 2.3.0 installed globally (Protractor 2.4.0+ causes [this error](https://github.com/angular/benchpress-tree/issues/8))
 - chromedriver_2.19
 - selenium-server-standalone-2.47.1

Here's the output for a sample test:

```
BENCHMARK bufferCount Rx2
Description:
- forceGc: false
- iterations: 1000
- regressionSlopeMetric: scriptTime
- sampleSize: 20
- userAgent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36
Metrics:
- gcAmount: gc amount in kbytes
- gcTime: gc time in ms
- majorGcTime: time of major gcs in ms
- pureScriptTime: script execution time in ms, without gc nor render
- renderTime: render time in ms
- scriptTime: script execution time in ms, including gc and render

          gcAmount |             gcTime |        majorGcTime |     pureScriptTime |         renderTime |         scriptTime
------------------ | ------------------ | ------------------ | ------------------ | ------------------ | ------------------
              0.00 |               0.00 |               0.00 |               0.00 |               0.22 |               0.00
              0.00 |               0.00 |               0.00 |               0.00 |               0.09 |               0.00
              0.00 |               0.00 |               0.00 |               0.00 |               0.06 |               0.00
            201.75 |               0.75 |               0.00 |               0.00 |               0.16 |               0.00
              0.00 |               0.00 |               0.00 |               0.00 |               0.10 |               0.00
              0.00 |               0.00 |               0.00 |               0.00 |               0.14 |               0.00
              0.00 |               0.00 |               0.00 |               0.00 |               0.06 |               0.00
              0.00 |               0.00 |               0.00 |               0.00 |               0.18 |               0.00
              0.00 |               0.00 |               0.00 |               0.00 |               0.14 |               0.00
              0.00 |               0.00 |               0.00 |               0.00 |               0.20 |               0.00
              0.00 |               0.00 |               0.00 |               0.00 |               0.05 |               0.00
              0.00 |               0.00 |               0.00 |               0.00 |               0.05 |               0.00
              0.00 |               0.00 |               0.00 |               0.00 |               0.17 |               0.00
              0.00 |               0.00 |               0.00 |               0.00 |               0.06 |               0.00
              0.00 |               0.00 |               0.00 |               0.00 |               0.24 |               0.00
              0.00 |               0.00 |               0.00 |               0.00 |               0.05 |               0.00
              0.00 |               0.00 |               0.00 |               0.00 |               0.12 |               0.00
              0.00 |               0.00 |               0.00 |               0.00 |               0.14 |               0.00
              0.00 |               0.00 |               0.00 |               0.00 |               0.09 |               0.00
            643.57 |               1.77 |               0.00 |               0.00 |               0.08 |               0.00
================== | ================== | ================== | ================== | ================== | ==================
       42.27+-342% |         0.13+-325% |         0.00+-299% |               0.00 |          0.12+-48% |               0.00
```

I'm trying to understand what this means. For example, the `scriptTime`, which is supposed to be the total of the `pure`, `gc` and `render` times (if I'm understanding correctly), is always 0, even in cases where the sum of those three values isn't zero. 

Also, the `pureScriptTime` is zero in all tests, which I'm assuming means the test is completing in negligible time, or that something is wrong. Is there a problem with my setup?

### PR DESCRIPTION
**Pull request by masaeedu**
…ular/protractor#2592

The selenium webdriver API changed between protractor 2.3 and 2.4. This change affects benchpress among other areas in angular2 codebase. Update benchpress dep version for compatibility with protractor 2.4+

Fixes #1228

### CODE REVIEW

**Comment by kwonoj** [comment]
As same as previous PR, would you able to share snippet of benchmark after fix?

**Comment by kwonoj** [comment]
(trying myself also meanwhile..)

**Comment by masaeedu** [comment]
@kwonoj The benchmarks are unchanged for me unfortunately. This pull just ensures the perf tests don't crash with `capsObject.toJSON is not a function` when using protractor 2.4+.

**Comment by kwonoj** [comment]
So it partially resolves issue but perf numbers does not changes, correct?

**Comment by masaeedu** [comment]
@kwonoj Yes. This PR allows the tests to be run with the version of protractor specified in devDependencies, which otherwise causes all tests to fail with the error I mentioned. 

It would be good if you could confirm whether you're seeing the same thing with the current version (i.e. running perf tests with Protractor 2.5 installed causes all test to fail).

**Comment by kwonoj** [comment]
Still it resolves some, change looks good to me. Issue can be triaged incrementally. 

Would you do one favor if you don't mind? Would you able to amend commit messages to follow (https://github.com/ReactiveX/RxJS/blob/master/CONTRIBUTING.md#commit), such as 
- limit subject under 100 char
- body contains detail
- and you may change `Fixes #xxxx` to `relates to ...` by this change yet closes issue. We use term of `closes` vs. `relates` to refer issue tracking.

I know it's picky, if you feel trouble I can amend myself - just checking before I do it for my own. RxJS repo currently uses some of automatic mechanism to generate change log, so aligned commit message would be greatly help those effort. (Yes, I'm slave of auto-robot-script :sunglasses: )

**Comment by masaeedu** [comment]
@kwonoj Not a problem at all, I'm still learning to write useful commit messages, so feedback is appreciated! I'll condense the subject a bit further, although you'll be happy to learn my git client won't even let me commit messages longer than 100 chars due to your configuration :smile:

Regarding "body contains detail", I tried to follow this guideline by adding a blank line before more detailed explanation. Did I get it wrong?

**Comment by kwonoj** [comment]
> Regarding "body contains detail", 

No, I believe you're correct for current body. It's just listing out recommendation. So I think moving some of details from subject to detail would work.

>my git client won't even let me commit messages longer than 100 chars due to your configuration

: yes, we do have hooks for that. for this specific PR, I thought it was over 100 by referring issue in subject. My mistake.

**Comment by masaeedu** [comment]
@kwonoj Ok, I've improved the commit message (hopefully). Thanks for your patience

**Comment by kwonoj** [comment]
> Thanks for your patience

: Not at all. It is appreciate to take time for contribution along with updating it. 

Merged with 6434e04. Thanks again @masaeedu !

**Comment by T0BiD** [comment]
I don't know if I can reach some of you with this, but I see no other possibility.
I'm trying to setup benchpress myself and because of the lack of documentation and tutorials I have a hard time doing so. I have the same error as stated in this PR, that's why I'm here

In my first try, I made sure everything is up to date, which didn't work. Then I tried to apply the fix stated here, and I still have the same error (caps.Object.forEach is not a function)
And the same Issue is stated in an still open (since 2015) Issue here: https://github.com/angular/benchpress-tree/issues/8

As I have no idea how to proceed or how to setup benchpress properly, I herby ask kindly for your help. 

As I know this is not the right place to discuss such things, I don't know where else to ask.

You can contact me privately at t0bi@protonmail.com
Thanks in advance

**Pull request closed without merging**
