### PR TITLE
Adds generics, Observer, Subscription, Subscriber, Operator, and Observable type classes, and updates all operators to use the Observable/Operator pair.

### LINKED ISSUE #69: Proposal: Implement CompositeSubscription behavior in Subscription, remove other Subscription types
Realistically, we can model all subscription logic with CompositeSubscription. Promoting composite behavior to the Subscription base class will reduce file size and complexity.

We can reduce the number of Subscription allocations by sharing a single Subscription instance between all intermediate Observers per subscribe call. Some operators don't allocate resources that need to be disposed. The ones that do (the flattening, splitting, and coincidence strategies) can add their inner Subscriptions to the Subscription shared between all Observers. This also reduces complexity inside those operators, as they don't have to worry about removing their inner subscriptions from the shared Subscription, because they'll be cleaned up when the shared Subscription is disposed (on throw, return, or dispose).

This is probably only feasible if Subscriptions store their inner subscriptions in a HashSet for O(1) insertion and removal.

### PR DESCRIPTION
**Pull request by trxcllnt**
Fixes #69, #70, #75, #72, #82, #96, #108, #109, #112, and #116.

### CODE REVIEW

**Comment by jeffbcross** [comment]
Holy giant commit!

**Comment by staltz** [comment]
Next time it would be friendly to use Github's *Assignee* feature before starting to fix the issue so multiple contributors don't do the same task in vain.

**Comment by blesh** [comment]
> Next time it would be friendly to use Github's Assignee feature before starting to fix the issue so multiple contributors don't do the same task in vain.

I agree. I knew of some of the things that @trxcllnt was working on, and I had assigned them to myself. But I didn't know the full scope until yesterday.

**Comment by blesh** [comment]
Either way, I'm thankful for this commit. We just need to keep it to smaller bites from here on out.

**Pull request merged**
