### PR TITLE
[WIP] feat(concatenate): new operator

### PR DESCRIPTION
**Pull request by maxime1992**
This closes ReactiveX/rxjs#4164

**Description:**
See #4164 

Before taking care of the tests, marble diagram and all I'd like to know if that operator has a chance to get merged or not :)

### CODE REVIEW

**Comment by kwonoj** [comment]
@maxime1992 thanks for contribution, but please hold and continue discussions in issue first in case of if we do not decide to accept new operators.

**Comment by maxime1992** [comment]
Sure thing, I won't spend more time on the PR before we agree (or not) to add it :+1:

**Comment by kwonoj** [comment]
closed via #4164 .

**Comment by maxime1992** [comment]
Closing the issue, closing the PR, I guess it's a no then :man_shrugging:

**Pull request closed without merging**
