### PR TITLE
feat(operator): add timeInterval operator

### PR DESCRIPTION
**Pull request by kwonoj**
* adding timeInterval operator, as well as migrating RxJS4 testcases

### CODE REVIEW

**Comment by staltz** [comment]
Pretty cool :sunglasses:

**Comment by kwonoj** [comment]
Thanks! :smiley:

**Comment by blesh** [comment]
Is this something that should be a core operator? It seems like this could be accomplished with `scan`. I love it, and I want to keep it, but perhaps this should go in the extended set of operators.

**Comment by kwonoj** [comment]
Do you suggest to move to extended operator? I'm feeling somewhat similar too.

**Comment by blesh** [comment]
I think so. It's one of those operators I think is cool, and that I want documented and available to people, but ultimately probably shouldn't ship with core.

**Comment by kwonoj** [comment]
OK, I'll update PR as suggested.

**Comment by kwonoj** [comment]
* Now `timeInterval` operator is placed under extended operators
* updated PR to satisfy lint

**Comment by blesh** [comment]
Thanks for your hard work!

**Pull request merged**
