### PR TITLE
fix README version

### PR DESCRIPTION
**Pull request by tomByrer**
update to `npm install @reactivex/rxjs@5.0.0-beta.1`

### CODE REVIEW

**Comment by kwonoj** [comment]
Hi @tomByrer , thanks for catching this :) would you able to update commit message to make consistency between history?

**Comment by tomByrer** [comment]
@kwonoj Like that?

**Comment by kwonoj** [comment]
Not sure where 'that' exactly points, we use convention https://github.com/ReactiveX/RxJS/blob/master/CONTRIBUTING.md#commit-message-format, so it'll be looks like

`docs(README): awesome update for readme`

if there's related issue you can refer it in detail, but for this there isn't so you don't need to attach it.

**Comment by tomByrer** [comment]
nm you fix it

**Comment by blesh** [comment]
Hey @tomByrer, I want to thank you for your effort to contribute and apologize if you found the process frustrating. We try to keep our commit messages to an [expected format]() because we use some automation to analyze them and use them for various purposes (mostly for changelog generation).

Again, my apologies if your experience with this PR put a sour taste in your mouth, and I sincerely hope to see more contributions from you in the future.

**Pull request closed without merging**
