### PR TITLE
Added new file for the take operator micro perf test

### PR DESCRIPTION
**Pull request by smaye81**
Added a new file for the `take` operator micro perf test.  This is my first attempt at contribution just to learn the architecture.  I'm really interested in helping out, so please let me know if I did this incorrectly

### CODE REVIEW

**Comment by blesh** [comment]
Thank you so much for the PR! Can you add the test for the immediate thread scheduler for `take` as well? Then call them in the `perf/micro/index.js` file?

Thanks again for your help!

**Comment by smaye81** [comment]
Updated.  Thanks for the input / guidance!

**Comment by trxcllnt** [comment]
@smaye81 @blesh looks good to me!

**Comment by blesh** [comment]
This has been merged as of 2239313

**Pull request closed without merging**
