### PR TITLE
fix(WebSocketSubject): prevent early close

### PR DESCRIPTION
**Pull request by deontologician**
**Description:**
This prevents the WebSocketSubject from prematurely closing the underlying websocket before all subscriptions have completed.

**Related issue (if exists):**
ReactiveX/rxjs#1827

### CODE REVIEW

**Comment by kwonoj** [comment]
I think additional test case can be added for this behavior changes. (check stub socket.close being called only if condition mets)

**Comment by deontologician** [comment]
Alright, test added. I've confirmed it fails on master and succeeds on this branch (on master the second `B next` is not received)

**Comment by deontologician** [comment]
Has anyone had a chance to check this out?

**Comment by kwonoj** [comment]
For me this change looks ok, need other reviewer's approval as well.

**Comment by mattpodwysocki** [comment]
LGTM

**Comment by deontologician** [comment]
Thanks!

**Pull request merged**
