### PR TITLE
feat(flatMap) Add support for returning Arrays from a flatMap selector.

### PR DESCRIPTION
**Pull request by trxcllnt**

### CODE REVIEW

**Comment by mattpodwysocki** [comment]
@trxcllnt instead of Arrays, I would say support iterables which could be arrays, maps, sets, and even generators as it is currently supported in RxJS

**Comment by xgrommx** [comment]
@trxcllnt @mattpodwysocki Why not just `flatMap(...).toArray()`?

**Comment by mattpodwysocki** [comment]
@trxcllnt @xgrommx that doesn't make any sense because it won't give us the same as a selector return value

**Comment by trxcllnt** [comment]
@mattpodwysocki I agree, but I needed this in a project last night, so y'know... incremental development

**Comment by blesh** [comment]
This is pre-alpha... the skateboard could be merged to the smiley-face's small intestines.

**Comment by blesh** [comment]
This LGTM. I think we need a broader approach that utilizes techniques like this for dealing with inner subscriptions.

**Comment by blesh** [comment]
This has been merged with 4ad6797

**Pull request closed without merging**
