### PR TITLE
feat(operators): add `operators` operator

### PR DESCRIPTION
**Pull request by blesh**
This adds an operator call `operators` that enables users to create a new Observable with
operators added to it as methods based on a passed hash of operator methods.

``` ts
source.operators({ filter, map })
  .filter(x => x > 1)
  .map(x => x * 10)
```

related #2034

### CODE REVIEW

**Comment by blesh** [comment]
I'm proposing this because:

1. I think it solves some of the type inference concerns.
2. It reads a little cleaner and is more ergonomic.
3. It's an alternative

**Comment by blesh** [comment]
NOTE: We can move the method to `Observable` proper like `operate` from #2034 as well.

**Comment by blesh** [comment]
... also the name can be bike-shedded, this is more of a proposal.

**Comment by staltz** [comment]
Name suggestion: `include` or `including`. But still not super happy with the direction this is going.

**Pull request closed without merging**
