### PR TITLE
feat(operator): Add do operator.

### PR DESCRIPTION
**Pull request by trxcllnt**

### CODE REVIEW

**Comment by mattpodwysocki** [comment]
Do we not want Observer support here as well in addition to the three main functions?

**Comment by trxcllnt** [comment]
@mattpodwysocki we do, but I need this now for my work on Falcor right now. Should also probably be `doObserver` or something similar, as we've decided against polymorphic functions for performance reasons.

**Comment by mattpodwysocki** [comment]
@trxcllnt then are we going to support `doOnNext` etc to handle `onNext` calls, and for all of the other verbiage like we have in the current as well?

**Comment by trxcllnt** [comment]
@mattpodwysocki I don't see why not.

**Pull request merged**
