### PR TITLE
refactor(observeOn): let observeOn uses notification instead of custo…

### PR DESCRIPTION
**Pull request by kwonoj**
…m implementation

Trying to make changes as suggested in https://github.com/ReactiveX/RxJS/issues/247

* Since this is first time to try to make in source tree, not sure if changes are correctly following recommended pattern. Used delay operator's implementation as reference, would be appreciate to let me know if it's not feasible way to do.

* Not sure about testcases, does current codebase has testscheduler in place? Wasn't able to find it so far.

### CODE REVIEW

**Comment by blesh** [comment]
>  does current codebase has testscheduler in place?

Not yet, there is a virtual scheduler in the works, hopefully landing soon.

**Comment by blesh** [comment]
Otherwise this looks good to me.

**Comment by kwonoj** [comment]
Thanks. in that case would it be acceptable PR's merged then test case comes with separate PR once scheduler is in place? or PR should be updated with test?

**Comment by blesh** [comment]
@kwonoj yes, we're going to proceed with development, but we'll need to circle back and add a LOT of tests with the VirtualScheduler

**Comment by blesh** [comment]
Thanks @kwonoj

**Pull request merged**
