### PR TITLE
style(src): add lint tasks for TypeScript and JS

### PR DESCRIPTION
**Pull request by staltz**
Establish a code style using tslint (for src/) and eslint (for perf/
and spec/). The existing code style was approximately inferred by
analyzing which style was the most common. The lint tasks should also
run in Travis. An established code style is important for a large
project such as RxJS which expects multiple contributions from the
community, in order to avoid pollution of feature-related commits with
style refactors.

PS: I know this is a huge commit which touches everything, but it's meant to happen only once. Will be much easier to handle code style issues in the future if we have linting tasks in place.

### CODE REVIEW

**Comment by kwonoj** [comment]
What about adding lint task to be executed when `build_all` is invoked?

**Comment by blesh** [comment]
@staltz can you rebase this one?

**Comment by blesh** [comment]
Also, it wouldn't be a bad thing to run this with build_test at least, so it was part of travis checks.

**Comment by staltz** [comment]
Will do.

**Comment by staltz** [comment]
All done

**Pull request merged**
