### PR TITLE
refactor(operator): move auto-patching modules into subdirectory

### PR DESCRIPTION
**Pull request by jeffbcross**

### CODE REVIEW

**Comment by blesh** [comment]
I thought we wanted `rxjs/add/map` and not `rxjs/operator/add/map`?

**Comment by jeffbcross** [comment]
@blesh I had forgotten to move `observable/*` over, but I've corrected that. I also fixed lint and failing tests.

**Comment by jeffbcross** [comment]
I also changed the target directory to `rxjs/add/operator/*` and `rxjs/add/observable/*` to mirror the src structure.

**Comment by jeffbcross** [comment]
Oops, I accidentally pushed another commit to this branch. I'm going to remove and re-push.

**Comment by jeffbcross** [comment]
Out-of-place commit has been removed.

**Comment by blesh** [comment]
merged with 1ab3508... thanks @jeffbcross

**Pull request closed without merging**
