### PR TITLE
chore(npm): fix `serve-and-sync` command

### LINKED ISSUE #5282: Serve-and-sync command doesn't work
## Bug Report

**Current Behavior**
When I run the docs locally, I usually stop the server, re-generate the docs and start the server again when I want to preview a change because the `serve-and-sync` command fails with the following error. The error appears when saving files that are located in the `docs_app/content` folder.

image

### PR DESCRIPTION
**Pull request by dzhavat**
**Description:**
Fix `serve-and-sync` command fails when working with the docs locally. It happens only after saving files that are located in the `content` folder. Looks like the reason for this is the RegExp that matches the path to the files. 

**Related issue (if exists):**
Close #5282

### CODE REVIEW

**Comment by cartant** [comment]
@dzhavat If you rebase this PR onto `master`, CI should pass.

**Comment by dzhavat** [comment]
Just figured out that the command still errors when a file in the `operators` folder is saved. Couldn't fix it.

**Comment by JWO719** [comment]
I would still like to merge that as it clearly improves the developer experience. Any objections?

**Comment by dzhavat** [comment]
It'd be nice if we can fix the error that (still) occurs when a file in the `operators` folder is saved (as pointed out above). If someone can take a look at it that'd be great because I don't know the docs build process that well.

**Comment by benlesh** [comment]
Thank you, @dzhavat!

**Pull request merged**
