### PR TITLE
Bump up typescript to latest

### PR DESCRIPTION
**Pull request by kwonoj**
**Description:**
This PR bumps up tsc / type definition (`typings`) into latest. PR intentionally picks tsc version to `latest`, let master branch try to build on latest release always to check regressions earlier.

**Related issue (if exists):**

### CODE REVIEW

**Comment by kwonoj** [comment]
Uh forgot error object thing. :/

**Comment by kwonoj** [comment]
Error object change is basically cherry picking https://github.com/ReactiveX/rxjs/pull/2614/commits/d242156448186798eb02733106122615c59d5b22 merged in next previously.

**Comment by benlesh** [comment]
@kwonoj what is dependency cruiser? Is it required for this change? Can we discuss it and perhaps move it to a different PR?

**Comment by kwonoj** [comment]
@benlesh it's replacement to `madge` for circular ref check. It should be included in this PR, cause madge has inner peer dep prevented to bump up ts recently. (Jay hits this). Course we can discuss if needed, but not as a separate PR.

**Comment by benlesh** [comment]
@kwonoj right on

:shipit:

**Pull request merged**
