### PR TITLE
test(toArray): add marble tests for toArray

### PR DESCRIPTION
**Pull request by adrianomelo**
Refactor test with multiple values and add missing tests for toArray operator.

### CODE REVIEW

**Comment by blesh** [comment]
Awesome! Can you add tests for `Observable.throw` and `Observable.empty`?

**Comment by adrianomelo** [comment]
Hi @blesh,
Does this patch closes #379?

**Comment by blesh** [comment]
@adrianomelo yes it does.

**Comment by blesh** [comment]
Merged with 58b91fb

Thank you so much, @adrianomelo! I appreciate the work!

**Pull request closed without merging**
