### PR TITLE
doc(decision-tree): update operator/function names

### PR DESCRIPTION
**Pull request by mtaran-google**
**Description:** updates to the operator decision tree widget's content

**Related issue (if exists):** #3900

### CODE REVIEW

**Comment by JWO719** [comment]
In my opinion these changes shouldn't be part of the old docs. I thought we use the /doc folder for documenting rxjs < 6? I'm not sure if we want to mix it up

**Comment by cartant** [comment]
@JWO719 I'm not sure what's supposed to be where, but there is already some v6-specific documentation in `/doc` directory: [`doc/marble-testing.md`](https://github.com/ReactiveX/rxjs/blob/master/doc/marble-testing.md).

**Comment by JWO719** [comment]
@cartant I totally share your opinion on that, but we should agree on an intention of the `/doc` folder

**Comment by benlesh** [comment]
Thanks, @mtaran-google

**Pull request merged**
