### PR TITLE
fix(bufferCount): will behave as expected when `startBufferEvery` is …

### LINKED ISSUE #2062: Issue with bufferCount?
**RxJS version:**
5.0.0.rc-1

**Code to reproduce:**
http://codepen.io/nabati/pen/kkVLwr

**Expected behavior:**
When clicking three times in the document, expecting PING PING PING, PING PING PONG. 

**Actual behavior:**
Getting PING PING PING, PING PONG PING. 

**Additional information:**
Seems like adding a delay(0) before the last map solves the issue, as such 
```
// ...
	.delay(0)
	.map(action => store$.next(action));
```

### PR DESCRIPTION
**Pull request by blesh**
…greater than `bufferSize`

- fixed issue where internal `buffers` store was keeping an additional buffer for no good reason
- improved logic and performance around updating internal `buffers` list
- adds a test to ensure proper behavior

fixes #2062

### CODE REVIEW

**Comment by blesh** [comment]
Worth noting, performance improves here as well:

This branch:

```
                                         |                     RxJS 4.1.0 |                RxJS 5.0.0-rc.1 |          factor |      % improved
---------------------------------------------------------------------------------------------------------------------------------------------------
                 buffercount - immediate |                24,789 (±0.76%) |               455,692 (±0.57%) |          18.38x |        1,738.3%
                             buffercount |                19,820 (±1.55%) |               242,544 (±1.45%) |          12.24x |        1,123.7%
```

master:

```
                                         |                     RxJS 4.1.0 |                RxJS 5.0.0-rc.1 |          factor |      % improved
---------------------------------------------------------------------------------------------------------------------------------------------------
                 buffercount - immediate |                25,716 (±0.73%) |               403,000 (±0.87%) |          15.67x |        1,467.1%
                             buffercount |                19,664 (±1.47%) |               226,951 (±1.35%) |          11.54x |        1,054.1%
```

**Comment by jayphelps** [comment]
@blesh #2062 is actually the opposite, `startBufferEvery` is _less_ than `bufferSize`. (the PR description says this fix is for when `startBufferEvery` is _greater_ than `bufferSize`)

**Comment by blesh** [comment]
haha... @jayphelps oops.

**Comment by blesh** [comment]
Also, I checked `windowCount`, and it does not have the same issue.

**Comment by blesh** [comment]
FYI: I think the coverage zero tolerance is getting us here with an unfortunate mathematical jump.

**Pull request merged**
