### PR TITLE
chore(doctest) Test all code examples are runnable with markdown-doctest

### PR DESCRIPTION
**Pull request by Widdershin**
Hi!

While working on the RxJS documentation, I noticed that there was quite a bit of broken or outdated code. That spurred me to write a tool, [markdown-doctest](https://github.com/Widdershin/markdown-doctest). markdown-doctest pulls all of the JS examples out of the markdown documentation, and then runs them to make sure they're syntactically valid and actually executable.

I've already used markdown-doctest to [find and fix 25 syntax errors](https://github.com/Reactive-Extensions/RxJS/pull/993) in the RxJS docs, as well as to update [old and broken testing documentation](https://github.com/Reactive-Extensions/RxJS/pull/1001).

I would like to have `markdown-doctest` run after `jasmine`, as part of `npm test`. That way, any out of date or invalid code examples in documentation will be caught by the CI, and pull requests will need to have valid examples before they can merge.

As part of adding this, `markdown-doctest` has already found one SyntaxError, a missing comma in `writing-marble-tests.md`.

I would love to hear any feedback you have on this idea.

### CODE REVIEW

**Comment by blesh** [comment]
Wow, @Widdershin ... this is a really impressive tool. I'm worried it won't work with what we're doing though because I don't have docs in markdown. They're written inline as esdoc (jsdoc) style comments, and then generated as HTML after the fact.

There are a *few* markdown files that are used, and this might be helpful there.

I can *definitely* see the merit of your tool.. I'm just not sure how to integrate it. The docs for this project are pretty light though, so there's a lot of room for movement.

What do you think?

cc/ @robwormald since he worked on doc generation.

**Comment by Widdershin** [comment]
Hi @blesh,

I had made the assumption that the docs for this project were going to be in the same style as the current version of RxJS, so in that light this is definitely a bit less useful for RxJS-next.

There is still an advantage to using `markdown-doctest` even if it just means that all examples that *are* written in markdown are actually runnable. There are currently 8 such examples in this project, and `markdown-doctest` already found a SyntaxError in one of them.

Potentially there is room for another tool or an extension to `esdoc`? `esdoctest`? Do you think that would be of use?

**Comment by blesh** [comment]
> Potentially there is room for another tool or an extension to esdoc? esdoctest? Do you think that would be of use?

Sure, it sounds really cool/interesting. We'd just want to make sure it aligns with our documentation story and there are a lot of questions there... Do we have some sort of JSBin embed with runnable snippets? If so how do we create them? etc.

**Comment by Widdershin** [comment]
@blesh: I'm wondering about getting this pull request merged.

I feel like it contributes value as long as there are code examples in markdown in this repo. Even if that just means checking that the README works I think that's useful. If it ends up that all of that stuff is moved somewhere else, it would be trivial to remove.

I gather from your comments that you want to ensure thought is put into how documentation will be handled before investing too much effort in a certain direction. I don't think that adopting `markdown-doctest` would limit the options on how the docs are done. We can always remove it.

I'm eager to maintain this utility and if so desired adapt it to suit the direction the docs eventually move in.

> I'm just not sure how to integrate it. The docs for this project are pretty light though, so there's a lot of room for movement.

I'm guessing you're talking about integrating it with the docs across the board (since it's already integrated with `npm test`/travis as part of this pull request). My instinct is to postpone worrying about that until the direction for the docs has been decided. 

Am I totally off the mark here?

**Comment by blesh** [comment]
No worries. I'm just slow with merging. I'll try to more thoroughly review this Monday or Tuesday. This one will take some fiddling with for me to understand, I think

**Comment by Widdershin** [comment]
Okay cool, I'm in no rush. Let me know if you have any questions or
concerns I can address.

**Comment by trxcllnt** [comment]
A+++++ PR, would review again.

**Comment by blesh** [comment]
This has some conflicts to resolve before I can merge it.

**Comment by Widdershin** [comment]
@blesh I just rebased from master and the tests are passing :smile:

**Comment by blesh** [comment]
Cool, thanks @Widdershin

**Comment by robwormald** [comment]
@Widdershin we'd probably love something like this over in angular2, if you're into that kind of thing ;-)

**Pull request merged**
