### PR TITLE
[DO NOT MERGE][MERGE INTO NEXT BRANCH] chore(TypeScript): Upgrade TypeScript to 2.2

### LINKED ISSUE #2178: Custom error object is no longer typeof Error from TypeScript 2.1
**RxJS version:**

**Code to reproduce:**

**Expected behavior:**

**Actual behavior:**

**Additional information:**
Was shared in meeting, it is actually intended design of TS 2.1 (https://github.com/Microsoft/TypeScript-wiki/blob/master/Breaking-Changes.md#extending-built-ins-like-error-array-and-map-may-no-longer-work) that no longer allows to extend built in object by default. 

Means, all of custom errors in RxJS v5 (i.e `TimeoutError`) is not typeof `Error`, will break existing code if anyone does type checking for those, as well as existing test cases too.

### PR DESCRIPTION
**Pull request by saneyuki**
- BREAKING CHANGE: This requires to use TypeScript 2.2 or later for
  users.
   - This will be effect to the next semver major release.
   - Not related for the next v5 release.
- This is the proposal for the next semver major release.
- After TypeScript 2.1, there are some breaking change which cannot
  support ~IE10. It is handled by
  https://github.com/ReactiveX/rxjs/issues/2178.
- This also sort tslib's version with tsc's version.
- By this change, we can retry to install type definitions from npm.
  - https://github.com/ReactiveX/rxjs/pull/2120

## Related Issues

- This requires to fix #2178 before merging this.
- https://github.com/ReactiveX/rxjs/issues/2437
- https://github.com/ReactiveX/rxjs/issues/2436

### CODE REVIEW

**Comment by kwonoj** [comment]
Please refer https://github.com/ReactiveX/rxjs-core-notes/blob/master/2017-01/january-30.md, we decided to align with ng2's compiler upgrade plan and until then we probably won't visit compiler bump up.

**Comment by saneyuki** [comment]
> we decided to align with ng2's compiler upgrade plan and until then we probably won't visit compiler 

I know it. This is still a proposal and I don't claim to merge this immediately :)

**Comment by kwonoj** [comment]
Do we need pr opened for this? There is no specific eta for this and probably this PR will stale for quite long time, will make you wait for those time period.

**Comment by saneyuki** [comment]
Okay. I'll close this.

**Comment by kwonoj** [comment]
I'm also quite in favor this and would like to have it soon, thanks for bringing up. Let's take a revisit once we can introduce this.

**Pull request closed without merging**
