### PR TITLE
docs(exhaustMap): fix example

### PR DESCRIPTION
**Pull request by tanem**
Add missing import 🦅

### CODE REVIEW

**Comment by stck** [comment]
I think it better to avoid remove of line breaks. Your thoughts?

**Comment by tanem** [comment]
> I think it better to avoid remove of line breaks. Your thoughts?

That was due to Prettier reformatting. Since there doesn't appear to be a consistent code style applied to the docs examples though, I'm happy to change it back in order to respect the existing style in this example.

**Comment by tanem** [comment]
Thanks @JWO719, no problem at all 🙂

**Comment by JWO719** [comment]
@tanem Could you report the merge conflicts?

**Comment by tanem** [comment]
> @tanem Could you report the merge conflicts?

@JWO719 sure, all done :+1:

**Comment by JWO719** [comment]
Thank you very much for all the work you put into the docs! I really appreciate that

**Pull request merged**
