### PR TITLE
chore(test): add macro performance tests for merge

### PR DESCRIPTION
**Pull request by kwonoj**
Try to close https://github.com/ReactiveX/RxJS/issues/257.

After adding this test case I'm observing failures on my machine at the end of perf test using **Windows 10, Chrome 45.0.2454.85 m (64-bit)**. To verify it's occurring on other configuration created clean machine runnning **Ubuntu 12.02 LTS 45.0.2454.85 (64-bit) and test was exited without error**. Since test case itself ran successfully I suspect this is somewhat related with protractor issue (maybe this? https://github.com/angular/protractor/issues/2001) but do not have concrete clue. While trying to troubleshoot issue, creating PR to ask if anyone experiences similar cases.

>github\RxJS\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:377
>      throw new Error('This driver instance does not have a valid session ID ' +
>            ^
>Error: This driver instance does not have a valid session ID (did you call WebDriver.quit()?) and may no longer be used.
>    at checkHasNotQuit (Z:\github\RxJS\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:377:13)
>    at Z:\github\RxJS\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:350:5
>    at [object Object].webdriver.promise.ControlFlow.runInNewFrame_ (Z:\github\RxJS\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:1654:20)
>    at [object Object].webdriver.promise.ControlFlow.runEventLoop_ (Z:\github\RxJS\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:1518:8)
>    at [object Object].wrapper [as _onTimeout] (timers.js:265:14)
>    at Timer.listOnTimeout (timers.js:110:15)
>==== async task ====
>WebDriver.quit()
>    at [object Object].webdriver.WebDriver.schedule (Z:\github\RxJS\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:345:15)
>    at [object Object].webdriver.WebDriver.quit (Z:\github\RxJS\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:418:21)
>    at Z:\github\RxJS\node_modules\protractor\lib\driverProviders\driverProvider.js:59:14
>    at Z:\github\RxJS\node_modules\protractor\node_modules\selenium-webdriver\lib\goog\base.js:1582:15
>    at [object Object].webdriver.promise.ControlFlow.runInNewFrame_ (Z:\github\RxJS\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:1654:20)
>    at notify (Z:\github\RxJS\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:465:12)
>    at [object Object].then (Z:\github\RxJS\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:522:7)
>    at [object Object].DriverProvider.quitDriver (Z:\github\RxJS\node_modules\protractor\lib\driverProviders\driverProvider.js:57:23)
>    at Array.map (native)
>[launcher] Process exited with error code 1

### CODE REVIEW

**Comment by kwonoj** [comment]
Tried some more scenarios to dig this and came to suspect it's related with protractor. Long story in short, trying with latest version of protractor (2.2.0) makes this problem goes away. Unfortunately do not have answer why current version (1.7.0) fails though. (Tested on systems I have, Windows 10+Chrome 45 x 2 + Ubuntu+Chrome 45 x 1).

**Comment by blesh** [comment]
@kwonoj ... according to @jeffbcross we should have a new version of benchpress shortly (releases are tied to Angular releases). Perhaps that will also solve this problem?

**Comment by kwonoj** [comment]
@blesh I have not updated version of benchpress but only updated protractor and it seems solves this specific problem. If updating version of benchpress & protractor can be aligned together, I think it'll solve problem. Does benchpress has specific version dependency to protractor?

**Comment by kwonoj** [comment]
+if benchpress update comes shortly, my suggestion is below :

1. Mark macro perf test PR as blocked for now
2. Once benchpress is ready, create PR for bump up version of benchpress & protractor both and merge it
3. Once test regression is verified, merge pending PR if exists

What do you think?

**Comment by blesh** [comment]
Considering all macro perf tests are broken for me at the moment, and in most cases we're adding tests where nothing existed before, I think we're okay to merge any good looking macro perf test as-is and create issues for corrections if need be once benchpress is sorted out.

**Comment by kwonoj** [comment]
I'm fine with allowing merge and take further action after benchpress update. Suggestion above is just based on personal preferences.

**Comment by blesh** [comment]
Merged with 26661c8

Thanks @kwonoj!

**Pull request closed without merging**
