### PR TITLE
docs(DeferObservable.ts, EmptyObservable.ts, FromEventObservable.ts, …

### PR DESCRIPTION
**Pull request by jrroman**
**Description:**

**Related issue (if exists):**

…FromObservable.ts, combineLates

Add output results for the examples in the documentation pertaining to the operators. Change

seqenceEqual.ts 'var code = Observable.from' to 'var code = Rx.Observable.from'. If the current

example is pasted into an editor and executed it will throw an error of 'Observable not defined'.

The addition of Rx. fixes this.

Issue: Examples do not have resulting output #2171

### CODE REVIEW

**Comment by staltz** [comment]
Hi @jrroman. Have you tried generating the docs site (`npm run build_docs` if I'm not mistaken) after your changes? I'm afraid those `//` comments won't show up in the code block, because the documentation generator looks for adjacent lines. So to be safe the `//` comments should be after code, with no empty line in between.

**Comment by jrroman** [comment]
Hi @staltz, I did run `npm run build_docs` and it looked like they appear in the code block with the associated example. I have attached a screenshot of my local, maybe I misunderstood something. If you would like I can move them directly adjacent so that there is no chance of error.

screen shot 2016-12-08 at 16 51 49

**Comment by jrroman** [comment]
@staltz I have gone through and removed all spaces between the code and the comments. It now looks like the below screenshot. If this is what you mean, I can push these changes.

screen shot 2016-12-08 at 17 14 03

**Comment by blesh** [comment]
@jrroman I personally like it better with a space in between. But that's me...

**Comment by staltz** [comment]
Ok, cool. I was suggesting no lines in between just to make sure that they compiled as a code block. If it works even with an empty line in between, then sure, go ahead.

**Comment by jrroman** [comment]
@blesh @staltz I cleaned the examples output up a bit just slight corrections with spacing and such. I kept the space between the example and the output per blesh's request.

**Comment by jrroman** [comment]
screenshot of the output from the last commit for reference.

screen shot 2016-12-09 at 16 48 24

**Comment by staltz** [comment]
LGTM

**Comment by blesh** [comment]
LGTM

**Pull request merged**
