### PR TITLE
chore(Observable.ajax): change method to optional on interface, since…

### PR DESCRIPTION
**Pull request by elliotschi**
**Description:**

**Related issue (if exists):**

… it gets set to GET by default

### CODE REVIEW

**Comment by kwonoj** [comment]
Change itself makes sense, only thing bit bothers me is since `AjaxRequest` is not completely optional interfaces, so `AjaxObservable.create({})` is valid construction. Seems not an issue, just looking bit odd.

**Comment by kwonoj** [comment]
I wouldn't worry that much about `AjaxObservable.create({})`, change itself LGTM. Just will leave this opened bit more to see if there's any concerns around.

**Comment by elliotschi** [comment]
@kwonoj 👍

**Comment by elliotschi** [comment]
@kwonoj sounds good

**Comment by jayphelps** [comment]
LGTM, please rebase.

**Comment by kwonoj** [comment]
@jayphelps you're so fast, I was about to click merge btn and it was already merged! 💨

**Comment by jayphelps** [comment]
👊 fastest merge in the West.

**Pull request merged**
