### PR TITLE
[ImgBot] Optimize images

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
## Beep boop. Your images are optimized!

Your image file size has been reduced by **14%** 🎉

<details>
<summary>
Details
</summary>

| File | Before | After | Percent reduction |
|:--|:--|:--|:--|
| /docs_app/assets/images/marble-diagrams/empty.png | 10.24kb | 4.78kb | 53.35% |
| /docs_app/src/assets/images/marble-diagrams/empty.png | 10.24kb | 4.78kb | 53.35% |
| /docs_app/assets/images/marble-diagrams/never.png | 8.12kb | 3.82kb | 52.99% |
| /docs_app/src/assets/images/marble-diagrams/NEVER.png | 8.12kb | 3.82kb | 52.99% |
| /docs_app/content/images/marketing/home/Rx_Logo-512-512.png | 95.95kb | 45.62kb | 52.45% |
| /docs_app/src/assets/images/marble-diagrams/throwIfEmpty.png | 16.16kb | 7.72kb | 52.21% |
| /docs_app/assets/images/marble-diagrams/throwIfEmpty.png | 16.16kb | 7.72kb | 52.21% |
| /docs_app/src/assets/images/marble-diagrams/throw.png | 12.54kb | 6.12kb | 51.18% |
| /docs_app/assets/images/marble-diagrams/throw.png | 12.54kb | 6.12kb | 51.18% |
| /docs_app/src/assets/images/marble-diagrams/forkJoin.png | 43.34kb | 31.38kb | 27.60% |
| /docs_app/assets/images/marble-diagrams/forkJoin.png | 43.34kb | 31.38kb | 27.60% |
| /doc/asset/marble-diagram-anatomy.svg | 13.16kb | 10.06kb | 23.56% |
| /docs_app/src/assets/images/guide/marble-diagram-anatomy.svg | 13.16kb | 10.06kb | 23.56% |
| /docs_app/src/assets/images/marble-diagrams/concatAll.png | 131.30kb | 103.43kb | 21.23% |
| /docs_app/assets/images/marble-diagrams/concatAll.png | 131.30kb | 103.43kb | 21.23% |
| /docs_app/src/assets/images/marble-diagrams/windowCount.png | 133.99kb | 105.70kb | 21.11% |
| /docs_app/assets/images/marble-diagrams/windowCount.png | 133.99kb | 105.70kb | 21.11% |
| /docs_app/src/assets/images/marble-diagrams/window.png | 133.83kb | 106.45kb | 20.46% |
| /docs_app/assets/images/marble-diagrams/window.png | 133.83kb | 106.45kb | 20.46% |
| /docs_app/assets/images/marble-diagrams/combineAll.png | 111.07kb | 88.45kb | 20.37% |
| /docs_app/src/assets/images/marble-diagrams/combineAll.png | 111.07kb | 88.45kb | 20.37% |
| /docs_app/src/assets/images/marble-diagrams/exhaust.png | 117.51kb | 93.59kb | 20.35% |
| /docs_app/assets/images/marble-diagrams/exhaust.png | 117.51kb | 93.59kb | 20.35% |
| /docs_app/src/assets/images/marble-diagrams/mergeAll.png | 114.58kb | 91.78kb | 19.90% |
| /docs_app/assets/images/marble-diagrams/mergeAll.png | 114.58kb | 91.78kb | 19.90% |
| /docs_app/src/assets/images/marble-diagrams/combineLatest.png | 96.86kb | 77.79kb | 19.69% |
| /docs_app/assets/images/marble-diagrams/combineLatest.png | 96.86kb | 77.79kb | 19.69% |
| /docs_app/src/assets/images/marble-diagrams/windowWhen.png | 122.08kb | 98.09kb | 19.65% |
| /docs_app/assets/images/marble-diagrams/windowWhen.png | 122.08kb | 98.09kb | 19.65% |
| /doc/asset/Rx_Logo_S.png | 10.02kb | 8.06kb | 19.57% |
| /docs_app/src/assets/images/logos/Rx_Logo_S.png | 10.02kb | 8.06kb | 19.57% |
| /docs_app/assets/images/marble-diagrams/mergeMap.png | 89.35kb | 72.33kb | 19.05% |
| /docs_app/src/assets/images/marble-diagrams/mergeMap.png | 89.35kb | 72.33kb | 19.05% |
| /docs_app/src/assets/images/marble-diagrams/concatMap.png | 89.32kb | 72.33kb | 19.02% |
| /docs_app/assets/images/marble-diagrams/concatMap.png | 89.32kb | 72.33kb | 19.02% |
| /docs_app/assets/images/marble-diagrams/groupBy.png | 117.90kb | 95.49kb | 19.01% |
| /docs_app/src/assets/images/marble-diagrams/groupBy.png | 117.90kb | 95.49kb | 19.01% |
| /docs_app/assets/images/marble-diagrams/switchAll.png | 105.67kb | 85.64kb | 18.95% |
| /docs_app/src/assets/images/marble-diagrams/switchAll.png | 105.67kb | 85.64kb | 18.95% |
| /docs_app/src/assets/images/marble-diagrams/zipAll.png | 104.32kb | 84.59kb | 18.91% |
| /docs_app/assets/images/marble-diagrams/windowTime.png | 96.02kb | 77.97kb | 18.80% |
| /docs_app/src/assets/images/marble-diagrams/windowTime.png | 96.02kb | 77.97kb | 18.80% |
| /docs_app/assets/images/marble-diagrams/switchMap.png | 88.05kb | 71.50kb | 18.80% |
| /docs_app/src/assets/images/marble-diagrams/switchMap.png | 88.05kb | 71.50kb | 18.80% |
| /docs_app/assets/images/marble-diagrams/bufferCount.png | 88.29kb | 71.77kb | 18.71% |
| /docs_app/src/assets/images/marble-diagrams/bufferCount.png | 88.29kb | 71.77kb | 18.71% |
| /docs_app/assets/images/marble-diagrams/mergeMapTo.png | 86.70kb | 70.52kb | 18.66% |
| /docs_app/src/assets/images/marble-diagrams/mergeMapTo.png | 86.70kb | 70.52kb | 18.66% |
| /docs_app/assets/images/marble-diagrams/switchMapTo.png | 83.25kb | 67.98kb | 18.34% |
| /docs_app/src/assets/images/marble-diagrams/switchMapTo.png | 83.25kb | 67.98kb | 18.34% |
| /docs_app/assets/images/marble-diagrams/windowToggle.png | 74.69kb | 61.04kb | 18.27% |
| /docs_app/src/assets/images/marble-diagrams/windowToggle.png | 74.69kb | 61.04kb | 18.27% |
| /docs_app/src/assets/images/marble-diagrams/concatMapTo.png | 86.10kb | 70.49kb | 18.13% |
| /docs_app/assets/images/marble-diagrams/concatMapTo.png | 86.10kb | 70.49kb | 18.13% |
| /docs_app/src/assets/images/marble-diagrams/distinctUntilKeyChanged.png | 65.97kb | 54.22kb | 17.81% |
| /docs_app/src/assets/images/marble-diagrams/throttleTime.png | 84.29kb | 69.60kb | 17.43% |
| /docs_app/assets/images/marble-diagrams/throttleTime.png | 84.29kb | 69.60kb | 17.43% |
| /docs_app/src/assets/images/logos/twitter-icon.svg | 0.92kb | 0.76kb | 17.29% |
| /docs_app/assets/images/marble-diagrams/withLatestFrom.png | 78.17kb | 64.75kb | 17.16% |
| /docs_app/src/assets/images/marble-diagrams/withLatestFrom.png | 78.17kb | 64.75kb | 17.16% |
| /docs_app/assets/images/marble-diagrams/partition.png | 58.04kb | 48.17kb | 17.01% |
| /docs_app/src/assets/images/marble-diagrams/partition.png | 58.04kb | 48.17kb | 17.01% |
| /docs_app/assets/images/marble-diagrams/buffer.png | 87.23kb | 72.78kb | 16.56% |
| /docs_app/src/assets/images/marble-diagrams/buffer.png | 87.23kb | 72.78kb | 16.56% |
| /docs_app/assets/images/marble-diagrams/retry.png | 60.01kb | 50.16kb | 16.41% |
| /docs_app/src/assets/images/marble-diagrams/retry.png | 60.01kb | 50.16kb | 16.41% |
| /docs_app/assets/images/marble-diagrams/exhaustMap.png | 81.02kb | 67.92kb | 16.16% |
| /docs_app/src/assets/images/marble-diagrams/exhaustMap.png | 81.02kb | 67.92kb | 16.16% |
| /docs_app/src/assets/images/marble-diagrams/sampleTime.png | 58.55kb | 49.15kb | 16.06% |
| /docs_app/assets/images/marble-diagrams/sampleTime.png | 58.55kb | 49.15kb | 16.06% |
| /docs_app/assets/images/marble-diagrams/range.png | 57.73kb | 48.63kb | 15.77% |
| /docs_app/src/assets/images/marble-diagrams/range.png | 57.73kb | 48.63kb | 15.77% |
| /docs_app/src/assets/images/logos/github-icon.svg | 1.01kb | 0.85kb | 15.76% |
| /docs_app/src/assets/images/marble-diagrams/multicast.png | 62.58kb | 52.74kb | 15.73% |
| /docs_app/assets/images/marble-diagrams/multicast.png | 62.58kb | 52.74kb | 15.73% |
| /docs_app/src/assets/images/marble-diagrams/publishBehavior.png | 61.83kb | 52.12kb | 15.70% |
| /docs_app/assets/images/marble-diagrams/sequenceEqual.png | 59.53kb | 50.24kb | 15.60% |
| /docs_app/src/assets/images/marble-diagrams/sequenceEqual.png | 59.53kb | 50.24kb | 15.60% |
| /docs_app/assets/images/marble-diagrams/throttle.png | 82.91kb | 69.98kb | 15.60% |
| /docs_app/src/assets/images/marble-diagrams/throttle.png | 82.91kb | 69.98kb | 15.60% |
| /docs_app/assets/images/marble-diagrams/delayWhen.png | 77.70kb | 65.73kb | 15.40% |
| /docs_app/src/assets/images/marble-diagrams/delayWhen.png | 77.70kb | 65.73kb | 15.40% |
| /docs_app/src/assets/images/marble-diagrams/pairwise.png | 62.46kb | 53.00kb | 15.14% |
| /docs_app/assets/images/marble-diagrams/pairwise.png | 62.46kb | 53.00kb | 15.14% |
| /docs_app/assets/images/marble-diagrams/bufferTime.png | 72.70kb | 61.73kb | 15.09% |
| /docs_app/src/assets/images/marble-diagrams/bufferTime.png | 72.70kb | 61.73kb | 15.09% |
| /docs_app/assets/images/marble-diagrams/skipWhile.png | 61.45kb | 52.58kb | 14.44% |
| /docs_app/src/assets/images/marble-diagrams/skipWhile.png | 61.45kb | 52.58kb | 14.44% |
| /docs_app/assets/images/marble-diagrams/bufferToggle.png | 83.97kb | 71.87kb | 14.42% |
| /docs_app/src/assets/images/marble-diagrams/bufferToggle.png | 83.97kb | 71.87kb | 14.42% |
| /docs_app/src/assets/images/marble-diagrams/every.png | 55.82kb | 47.84kb | 14.29% |
| /docs_app/src/assets/images/favicons/favicon-72x72.png | 7.42kb | 6.36kb | 14.26% |
| /docs_app/assets/images/marble-diagrams/merge.png | 73.69kb | 63.78kb | 13.44% |
| /docs_app/src/assets/images/marble-diagrams/merge.png | 73.69kb | 63.78kb | 13.44% |
| /docs_app/assets/images/marble-diagrams/takeWhile.png | 55.43kb | 48.03kb | 13.36% |
| /docs_app/src/assets/images/marble-diagrams/takeWhile.png | 55.43kb | 48.03kb | 13.36% |
| /docs_app/src/assets/images/marble-diagrams/publishReplay.png | 55.98kb | 48.53kb | 13.31% |
| /docs_app/src/assets/images/marble-diagrams/takeUntil.png | 49.74kb | 43.13kb | 13.28% |
| /docs_app/assets/images/marble-diagrams/takeUntil.png | 49.74kb | 43.13kb | 13.28% |
| /docs_app/assets/images/marble-diagrams/bufferWhen.png | 68.77kb | 59.86kb | 12.96% |
| /docs_app/src/assets/images/marble-diagrams/bufferWhen.png | 68.77kb | 59.86kb | 12.96% |
| /docs_app/src/assets/images/marble-diagrams/sample.png | 68.86kb | 59.97kb | 12.91% |
| /docs_app/assets/images/marble-diagrams/sample.png | 68.86kb | 59.97kb | 12.91% |
| /docs_app/src/assets/images/support/rxjs-404.png | 70.42kb | 61.52kb | 12.65% |
| /docs_app/src/assets/images/marble-diagrams/distinctUntilChanged.png | 51.46kb | 45.00kb | 12.54% |
| /docs_app/src/assets/images/marble-diagrams/auditTime.png | 59.79kb | 52.36kb | 12.43% |
| /docs_app/assets/images/marble-diagrams/auditTime.png | 59.79kb | 52.36kb | 12.43% |
| /docs_app/src/assets/images/marble-diagrams/filter.png | 53.51kb | 46.91kb | 12.34% |
| /docs_app/assets/images/marble-diagrams/filter.png | 53.51kb | 46.91kb | 12.34% |
| /docs_app/assets/images/marble-diagrams/expand.png | 57.82kb | 50.80kb | 12.15% |
| /docs_app/src/assets/images/marble-diagrams/expand.png | 57.82kb | 50.80kb | 12.15% |
| /docs_app/assets/images/marble-diagrams/catch.png | 54.42kb | 47.88kb | 12.03% |
| /docs_app/src/assets/images/marble-diagrams/catch.png | 54.42kb | 47.88kb | 12.03% |
| /docs_app/assets/images/marble-diagrams/debounceTime.png | 54.58kb | 48.04kb | 11.98% |
| /docs_app/src/assets/images/marble-diagrams/debounceTime.png | 54.58kb | 48.04kb | 11.98% |
| /docs_app/assets/images/marble-diagrams/refCount.png | 50.29kb | 44.41kb | 11.69% |
| /docs_app/src/assets/images/marble-diagrams/refCount.png | 50.29kb | 44.41kb | 11.69% |
| /docs_app/src/assets/images/favicons/favicon-96x96.png | 10.36kb | 9.17kb | 11.50% |
| /docs_app/assets/images/marble-diagrams/share.png | 49.01kb | 43.40kb | 11.45% |
| /docs_app/src/assets/images/marble-diagrams/share.png | 49.01kb | 43.40kb | 11.45% |
| /docs_app/assets/images/marble-diagrams/onErrorResumeNext.png | 57.11kb | 50.76kb | 11.12% |
| /docs_app/src/assets/images/marble-diagrams/onErrorResumeNext.png | 57.11kb | 50.76kb | 11.12% |
| /docs_app/src/assets/images/marble-diagrams/findIndex.png | 48.40kb | 43.02kb | 11.10% |
| /docs_app/assets/images/marble-diagrams/findIndex.png | 48.40kb | 43.02kb | 11.10% |
| /docs_app/assets/images/marble-diagrams/timeoutWith.png | 62.75kb | 55.97kb | 10.80% |
| /docs_app/src/assets/images/marble-diagrams/timeoutWith.png | 62.75kb | 55.97kb | 10.80% |
| /docs_app/assets/images/marble-diagrams/repeatWhen.png | 62.69kb | 55.93kb | 10.77% |
| /docs_app/src/assets/images/marble-diagrams/repeatWhen.png | 62.69kb | 55.93kb | 10.77% |
| /docs_app/assets/images/marble-diagrams/skipUntil.png | 54.43kb | 48.64kb | 10.65% |
| /docs_app/src/assets/images/marble-diagrams/skipUntil.png | 54.43kb | 48.64kb | 10.65% |
| /docs_app/assets/images/marble-diagrams/endWith.png | 45.08kb | 40.29kb | 10.62% |
| /docs_app/src/assets/images/marble-diagrams/endWith.png | 45.08kb | 40.29kb | 10.62% |
| /docs_app/src/assets/images/marble-diagrams/audit.png | 63.91kb | 57.13kb | 10.60% |
| /docs_app/assets/images/marble-diagrams/audit.png | 63.91kb | 57.13kb | 10.60% |
| /docs_app/assets/images/marble-diagrams/repeat.png | 51.58kb | 46.16kb | 10.50% |
| /docs_app/src/assets/images/marble-diagrams/repeat.png | 51.58kb | 46.16kb | 10.50% |
| /docs_app/src/assets/images/marble-diagrams/publish.png | 48.40kb | 43.33kb | 10.48% |
| /docs_app/assets/images/marble-diagrams/publish.png | 48.40kb | 43.33kb | 10.48% |
| /docs_app/src/assets/images/marble-diagrams/retryWhen.png | 56.83kb | 50.91kb | 10.43% |
| /docs_app/assets/images/marble-diagrams/retryWhen.png | 56.83kb | 50.91kb | 10.43% |
| /docs_app/src/assets/images/marble-diagrams/timestamp.png | 45.98kb | 41.19kb | 10.42% |
| /docs_app/assets/images/marble-diagrams/timestamp.png | 45.98kb | 41.19kb | 10.42% |
| /docs_app/assets/images/marble-diagrams/find.png | 47.18kb | 42.27kb | 10.41% |
| /docs_app/src/assets/images/marble-diagrams/find.png | 47.18kb | 42.27kb | 10.41% |
| /docs_app/assets/images/marble-diagrams/startWith.png | 43.58kb | 39.05kb | 10.39% |
| /docs_app/src/assets/images/marble-diagrams/startWith.png | 43.58kb | 39.05kb | 10.39% |
| /docs_app/src/assets/images/marble-diagrams/skip.png | 50.10kb | 44.98kb | 10.21% |
| /docs_app/assets/images/marble-diagrams/skip.png | 50.10kb | 44.98kb | 10.21% |
| /docs_app/src/assets/images/marble-diagrams/tap.png | 51.12kb | 45.99kb | 10.04% |
| /docs_app/src/assets/images/marble-diagrams/takeLast.png | 41.08kb | 37.02kb | 9.88% |
| /docs_app/assets/images/marble-diagrams/takeLast.png | 41.08kb | 37.02kb | 9.88% |
| /docs_app/src/assets/images/marble-diagrams/timeInterval.png | 45.89kb | 41.37kb | 9.86% |
| /docs_app/assets/images/marble-diagrams/timeinterval.png | 45.89kb | 41.37kb | 9.86% |
| /docs_app/src/assets/images/favicons/favicon-128x128.png | 14.56kb | 13.14kb | 9.71% |
| /docs_app/assets/images/marble-diagrams/map.png | 50.32kb | 45.51kb | 9.55% |
| /docs_app/src/assets/images/marble-diagrams/map.png | 50.32kb | 45.51kb | 9.55% |
| /docs_app/src/assets/images/marble-diagrams/dematerialize.png | 48.24kb | 43.77kb | 9.26% |
| /docs_app/assets/images/marble-diagrams/dematerialize.png | 48.24kb | 43.77kb | 9.26% |
| /docs_app/src/assets/images/marble-diagrams/debounce.png | 51.37kb | 46.67kb | 9.15% |
| /docs_app/assets/images/marble-diagrams/debounce.png | 51.37kb | 46.67kb | 9.15% |
| /docs_app/assets/images/marble-diagrams/scan.png | 48.61kb | 44.25kb | 8.96% |
| /docs_app/src/assets/images/marble-diagrams/scan.png | 48.61kb | 44.25kb | 8.96% |
| /docs_app/src/assets/images/favicons/favicon-152x152.png | 18.06kb | 16.48kb | 8.78% |
| /docs_app/src/assets/images/favicons/favicon-144x144.png | 16.76kb | 15.33kb | 8.56% |
| /docs_app/src/assets/images/marble-diagrams/pluck.png | 49.35kb | 45.15kb | 8.51% |
| /docs_app/assets/images/marble-diagrams/pluck.png | 49.35kb | 45.15kb | 8.51% |
| /resources/CI-CD/logo/svg/RxJs_Logo_Basic.svg | 3.76kb | 3.45kb | 8.38% |
| /docs_app/assets/images/marble-diagrams/concat.png | 53.52kb | 49.10kb | 8.26% |
| /docs_app/src/assets/images/marble-diagrams/concat.png | 53.52kb | 49.10kb | 8.26% |
| /docs_app/src/assets/images/marble-diagrams/skipLast.png | 39.01kb | 35.82kb | 8.17% |
| /docs_app/assets/images/marble-diagrams/skipLast.png | 39.01kb | 35.82kb | 8.17% |
| /docs_app/assets/images/marble-diagrams/materialize.png | 48.51kb | 44.65kb | 7.96% |
| /docs_app/src/assets/images/marble-diagrams/materialize.png | 48.51kb | 44.65kb | 7.96% |
| /docs_app/src/assets/images/favicons/favicon-192x192.png | 24.06kb | 22.20kb | 7.73% |
| /docs_app/src/assets/images/favicons/apple-touch-icon-144x144.png | 13.82kb | 12.80kb | 7.37% |
| /docs_app/assets/images/marble-diagrams/take.png | 37.50kb | 34.79kb | 7.23% |
| /docs_app/src/assets/images/marble-diagrams/take.png | 37.50kb | 34.79kb | 7.23% |
| /docs_app/src/assets/images/marble-diagrams/observeOn.png | 40.90kb | 38.11kb | 6.84% |
| /docs_app/assets/images/marble-diagrams/reduce.png | 40.77kb | 38.12kb | 6.49% |
| /docs_app/src/assets/images/marble-diagrams/reduce.png | 40.77kb | 38.12kb | 6.49% |
| /docs_app/src/assets/images/marble-diagrams/mapTo.png | 43.45kb | 40.83kb | 6.04% |
| /docs_app/assets/images/marble-diagrams/mapTo.png | 43.45kb | 40.83kb | 6.04% |
| /docs_app/src/assets/images/marble-diagrams/subscribeOn.png | 40.14kb | 37.75kb | 5.97% |
| /docs_app/assets/images/marble-diagrams/subscribeOn.png | 40.14kb | 37.75kb | 5.97% |
| /docs_app/src/assets/images/marble-diagrams/publishLast.png | 37.65kb | 35.42kb | 5.92% |
| /docs_app/assets/images/marble-diagrams/publishLast.png | 37.65kb | 35.42kb | 5.92% |
| /docs_app/src/assets/images/marble-diagrams/interval.png | 35.50kb | 33.42kb | 5.87% |
| /docs_app/assets/images/marble-diagrams/interval.png | 35.50kb | 33.42kb | 5.87% |
| /resources/CI-CD/logo/svg/RxJs_Logo_Basic_Outline.svg | 8.43kb | 7.94kb | 5.85% |
| /docs_app/src/assets/images/favicons/favicon-384x384.png | 56.40kb | 53.11kb | 5.82% |
| /docs_app/src/assets/images/favicons/favicon-512x512.png | 80.00kb | 75.68kb | 5.40% |
| /docs_app/src/assets/images/marble-diagrams/elementAt.png | 41.02kb | 38.87kb | 5.25% |
| /docs_app/assets/images/marble-diagrams/elementAt.png | 41.02kb | 38.87kb | 5.25% |
| /docs_app/src/assets/images/logos/logo.png | 4.25kb | 4.03kb | 5.15% |
| /docs_app/src/assets/images/marble-diagrams/delay.png | 39.70kb | 37.80kb | 4.78% |
| /docs_app/assets/images/marble-diagrams/delay.png | 39.70kb | 37.80kb | 4.78% |
| /docs_app/assets/images/marble-diagrams/defer.png | 31.70kb | 30.52kb | 3.73% |
| /docs_app/src/assets/images/marble-diagrams/defer.png | 31.70kb | 30.52kb | 3.73% |
| /resources/CI-CD/logo/svg/RxJs_Logo_Black.svg | 3.24kb | 3.13kb | 3.46% |
| /resources/CI-CD/logo/svg/RxJs_Logo_Black_Outline.svg | 5.20kb | 5.02kb | 3.46% |
| /docs_app/content/images/marketing/home/rxjs-live.svg | 8.67kb | 8.40kb | 3.18% |
| /docs_app/src/assets/images/marble-diagrams/generate.png | 28.74kb | 27.85kb | 3.09% |
| /docs_app/assets/images/marble-diagrams/generate.png | 28.74kb | 27.85kb | 3.09% |
| /docs_app/assets/images/marble-diagrams/first.png | 35.36kb | 34.36kb | 2.81% |
| /docs_app/src/assets/images/marble-diagrams/first.png | 35.36kb | 34.36kb | 2.81% |
| /docs_app/assets/images/marble-diagrams/timer.png | 30.79kb | 29.94kb | 2.76% |
| /docs_app/src/assets/images/marble-diagrams/timer.png | 30.79kb | 29.94kb | 2.76% |
| /docs_app/src/assets/images/marble-diagrams/fromEventPattern.png | 27.68kb | 26.94kb | 2.68% |
| /docs_app/assets/images/marble-diagrams/fromEventPattern.png | 27.68kb | 26.94kb | 2.68% |
| /docs_app/assets/images/marble-diagrams/from.png | 28.51kb | 27.82kb | 2.42% |
| /docs_app/src/assets/images/marble-diagrams/from.png | 28.51kb | 27.82kb | 2.42% |
| /docs_app/src/assets/images/marble-diagrams/create.png | 24.29kb | 23.71kb | 2.37% |
| /docs_app/src/assets/images/marble-diagrams/of.png | 23.44kb | 22.89kb | 2.35% |
| /docs_app/assets/images/marble-diagrams/of.png | 23.44kb | 22.89kb | 2.35% |
| /docs_app/assets/images/marble-diagrams/ignoreElements.png | 35.35kb | 34.53kb | 2.31% |
| /docs_app/src/assets/images/marble-diagrams/ignoreElements.png | 35.35kb | 34.53kb | 2.31% |
| /docs_app/src/assets/images/marble-diagrams/fromEvent.png | 26.37kb | 25.85kb | 1.99% |
| /docs_app/assets/images/marble-diagrams/fromEvent.png | 26.37kb | 25.85kb | 1.99% |
| /docs_app/src/assets/images/marble-diagrams/last.png | 31.14kb | 30.53kb | 1.95% |
| /docs_app/assets/images/marble-diagrams/last.png | 31.14kb | 30.53kb | 1.95% |
| /docs_app/src/assets/images/marble-diagrams/count.png | 31.64kb | 31.03kb | 1.94% |
| /docs_app/assets/images/marble-diagrams/count.png | 31.64kb | 31.03kb | 1.94% |
| /docs_app/src/assets/images/marble-diagrams/min.png | 28.70kb | 28.17kb | 1.85% |
| /docs_app/assets/images/marble-diagrams/min.png | 28.70kb | 28.17kb | 1.85% |
| /docs_app/src/assets/images/marble-diagrams/single.png | 29.06kb | 28.54kb | 1.79% |
| /docs_app/assets/images/marble-diagrams/single.png | 29.06kb | 28.54kb | 1.79% |
| /docs_app/src/assets/images/marble-diagrams/max.png | 32.17kb | 31.62kb | 1.72% |
| /docs_app/assets/images/marble-diagrams/max.png | 32.17kb | 31.62kb | 1.72% |
| /docs_app/src/assets/images/marble-diagrams/timeout.png | 28.48kb | 28.06kb | 1.49% |
| /docs_app/assets/images/marble-diagrams/timeout.png | 28.48kb | 28.06kb | 1.49% |
| /docs_app/assets/images/marble-diagrams/toArray.png | 29.30kb | 28.87kb | 1.48% |
| /docs_app/src/assets/images/marble-diagrams/toArray.png | 29.30kb | 28.87kb | 1.48% |
| /docs_app/assets/images/marble-diagrams/pairs.png | 27.27kb | 26.91kb | 1.30% |
| /docs_app/src/assets/images/marble-diagrams/pairs.png | 27.27kb | 26.91kb | 1.30% |
| /docs_app/src/assets/images/marble-diagrams/defaultIfEmpty.png | 26.57kb | 26.24kb | 1.26% |
| /docs_app/assets/images/marble-diagrams/defaultIfEmpty.png | 26.57kb | 26.24kb | 1.26% |
| /docs_app/assets/images/marble-diagrams/isEmpty.png | 18.25kb | 18.07kb | 0.98% |
| /docs_app/src/assets/images/marble-diagrams/isEmpty.png | 18.25kb | 18.07kb | 0.98% |
| | | | |
| **Total :** | **12,924.10kb** | **11,086.17kb** | **14.22%** |
</details>

---

[📝docs](https://imgbot.net/docs) | [:octocat: repo](https://github.com/dabutvin/ImgBot) | [🙋issues](https://github.com/dabutvin/ImgBot/issues) | [🏅swag](https://goo.gl/forms/1GX7wlhGEX8nkhGO2) | [🏪marketplace](https://github.com/marketplace/imgbot)

### CODE REVIEW

**Comment by MichaelDeBoey** [comment]
If you want, you can install https://imgbot.net in this repo (or in the full organization).
It will automatically send PRs for image optimization 🙂

**Comment by benlesh** [comment]
Pretty cool. Thanks!

**Comment by benlesh** [comment]
This couldn't be applied to the patch branch, but that's probably not a big deal.

**Comment by MichaelDeBoey** [comment]
Hope it's a useful bot you can install on the entire organization 🙂

**Pull request merged**
