### PR TITLE
feat(mergeScan): add new mergeScan operator.

### PR DESCRIPTION
**Pull request by trxcllnt**

### CODE REVIEW

**Comment by blesh** [comment]
Cool! This looks interesting.

I think we discussed this before, and the basic idea is that it's exactly like a `mergeMap/flatMap` accept you pump the value back into the selector, right? 

How does this differ from `expand`? What are the use cases?

cc/ @mattpodwysocki - might be interested in this.

**Comment by staltz** [comment]
Pretty cool addition, we talked about it in person already.

It's missing some thorough unsubscription tests. But we can merge this already and later I can add unsub tests.

**Comment by blesh** [comment]
oh oh ... @trxcllnt this is that "exscand" operator we discussed a while back right? Yes, I like this, and there's really not another way to do it efficiently with existing operators.

**Comment by trxcllnt** [comment]
@blesh not yet, I was going to put that in my next PR and call it "expandScan." This operator flattens multiple inner Observables and computes a aggregate value over all the inner values.

**Comment by blesh** [comment]
@trxcllnt can you rebase and resolve the conflicts?

**Comment by blesh** [comment]
@trxcllnt why did this close?

**Comment by trxcllnt** [comment]
@blesh because it'd already been merged.

**Comment by blesh** [comment]
Ah... I failed to mention it in a comment. :\ Thanks.

**Pull request closed without merging**
