### PR TITLE
fix(dependency): move symbol-observable into devdependency

### PR DESCRIPTION
**Pull request by kwonoj**
**Description:**
We don't use `symbol-observable` for dependency anywhere, moving it into devdep.

**Related issue (if exists):**

### CODE REVIEW

**Comment by benlesh** [comment]
@kwonoj was this meant for stable or master?

**Comment by kwonoj** [comment]
@benlesh master. I didn't want to bring any possible regressions in `stable`, though change looks harmless.

**Comment by lrowe** [comment]
If rxjs removes the symbol-observable dependency how do other observable implementations interoperate with rxjs through the symbol-observable protocol? Does this continue to work because symbol-observable mutates the global Symbol object to add a Symbol.observable property?

**Comment by kwonoj** [comment]
Rxjs has own symbol interop already. https://github.com/ReactiveX/rxjs/blob/master/src/symbol/observable.ts

**Pull request merged**
