### PR TITLE
chore(package): update package-lock

### LINKED ISSUE #3284: Update dependency-cruiser
Once this lands: https://github.com/sverweij/dependency-cruiser/pull/31

We should try to update dependency-cruiser to the latest version.

### PR DESCRIPTION
**Pull request by kwonoj**
**Description:**
This PR pins all of our dependncies, also check in package-lock.json. Now package lock support becomes quite stable, it works on cross-platform without modifying dependency when just try to install dependencies. We may need bump up huge number of dependencies in here, but that's different story.

**Related issue (if exists):**
- closes #3284

### CODE REVIEW

**Comment by kwonoj** [comment]
🤔 just pinning dependency makes test fails?

**Comment by kwonoj** [comment]
pin just removed caret from version range. There should be some semver minor bumps with carets, but still making test fails seems bit odd.

**Comment by cartant** [comment]
How did that test ever pass? The [implementation](https://github.com/ReactiveX/rxjs/blob/master/src/internal/observable/concat.ts#L112-L114) seems to explicitly **not** use the scheduler if there is only one observable?

```ts
if (observables.length === 1 || (observables.length === 2 && isScheduler(observables[1]))) {
  return from(<any>observables[0]);
}
```

**Comment by kwonoj** [comment]
> The implementation seems to explicitly not use the scheduler if there is only one observable?

that's true, test case description is reading bit confusing. It concat's `one` observable + scheduler as param, which takes execution path for arguments length as > 1 .

**Comment by kwonoj** [comment]
phew, bit larger work than I thought.

**Pull request merged**
