### PR TITLE
refactor(do): Make `DoSubscriber`'s menbers private.

### PR DESCRIPTION
**Pull request by saneyuki**
These members are not referred from others.

### CODE REVIEW

**Comment by kwonoj** [comment]
Just checking - is this changes are same changes in https://github.com/ReactiveX/RxJS/pull/1116 did not added at the moment?

**Comment by saneyuki** [comment]
@kwonoj 

>  is this changes are same changes in #1116 did not added at the moment?

No, This is the separated change. This makes them private which stores callback functions passed from `DoOperator`.

**Comment by kwonoj** [comment]
Change looks good to me. I'll check this in around later today if there isn't any suggestions.

**Comment by blesh** [comment]
merged with a5927ba. Thanks @saneyuki

**Pull request closed without merging**
