### PR TITLE
test(do): test when handlers raise an exception

### PR DESCRIPTION
**Pull request by adrianomelo**

### CODE REVIEW

**Comment by blesh** [comment]
Nice @adrianomelo! Do you think you'd like to add tests for errors thrown in the other handlers?

**Comment by blesh** [comment]
If not, no big deal, I can merge this one.

**Comment by adrianomelo** [comment]
@blesh, yes, sure! It'll make a better commit.

**Comment by blesh** [comment]
Awesome! I'll leave this PR up until you're ready! Thanks again!

**Comment by adrianomelo** [comment]
@blesh, this pr is now updated..

**Comment by blesh** [comment]
Great! I've merged this as of 1647aff

Thanks for the good work, @adrianomelo! Much appreciated.

**Pull request closed without merging**
