### PR TITLE
docs: Update to angular 11

### PR DESCRIPTION
**Pull request by paulmojicatech**
**Description:**
Update docs app to Angular 11
**Related issue (if exists):**
#5920

### CODE REVIEW

**Comment by benlesh** [comment]
The commits here look wrong, @paulmojicatech, maybe you're targeting the wrong branch or something got crossed? Might want to take a look at that.

**Review by benlesh — CHANGES_REQUESTED** [review]
The commits here look wrong, @paulmojicatech, maybe you're targeting the wrong branch or something got crossed? Might want to take a look at that.

**Comment by paulmojicatech** [comment]
@benlesh , thanks for the feedback.  I went ahead and pulled from master and pushed to my branch again.  Hopefully this resolves the commit issues. Thanks!

**Comment by niklas-wortmann** [comment]
Sorry for the late feedback, @paulmojicatech could you resolve the merge conflicts, I try to test this pr manually as soon as possible and give you feedback. Thanks a lot for all the work you put into it

**Comment by paulmojicatech** [comment]
No worries @niklas-wortmann .  I updated the PR to resolve the merge conflict.  Please let me know if it looks OK. Thanks again for your time and effort!

**Comment by paulmojicatech** [comment]
Created a new PR for update to Angular 12

**Pull request closed without merging**
