### PR TITLE
examples not equivalent

### PR DESCRIPTION
**Pull request by calidion**
**Description:**

examples not in accordance with each other.

**Related issue (if exists):**

### CODE REVIEW

**Comment by kwonoj** [comment]
what does last commit do?

**Comment by calidion** [comment]
sorry, i should create a brach for this files added.

**Comment by kwonoj** [comment]
@calidion I'd like to suggest PR to include scoped minimal changes.

And also by seeing commits it seems there are some translated docs - while it is great appreciate, current doc folder is intended to publish into http://reactivex.io/rxjs/ directly and not for direct-reading in repo, which needs pipeline setup to have proper localization support for doc page generation. 

If it is intended to provide translated documentation, please file an issue with a high-level proposal first to discuss & settle down initial pipelines. Again, appreciate for all effort!

**Comment by calidion** [comment]
@kwonoj 

I have removed these files from master.

Those files are just a start of translation for learning purpose, I would not intend to integrate those files right now:)

sorry for the mistake.

To get better understanding of how RxJS works, I am verifying the code examples from articles inside the `doc` folder,  then I found this inaccordance. Hope i'm on the way to improve the document. If rxjs will support i18n, I would be glad to contribute.

**Comment by kwonoj** [comment]
> sorry for the mistake.

: no worries, it is totally fine.

> Hope i'm on the way to improve the document

: absolutely, it is one of important goals to fill missing document / improve existing one. Check this out. https://twitter.com/BenLesh/status/811728544543801345 :)

**Comment by calidion** [comment]
hope i can have some RxJS T-shirts some day:)

**Comment by blesh** [comment]
@calidion ... t-shirts are absolutely coming for people that contribute docs after my tweet. There's going to be a wait while I get them ordered and shipped, however. Still in the ordering process. It's a little slow over the holidays.

**Comment by calidion** [comment]
@blesh 
I am translating official docs into Chinese,
don't know how to contribute to this project.

**Comment by blesh** [comment]
@calidion ... Yeah, I'm honestly not sure either. I'll need to check with the ReactiveX documentation folks and see what's been done in the past. I'll also check with the Angular team and see if they're doing anything like this.

**Pull request merged**
