### PR TITLE
docs: update Operators overview

### PR DESCRIPTION
**Pull request by EnricoPicci**
Introduce the concept that what we normally call "operators", such as `map`
or `filter`, are Pipeable Operator Factory functions which, when called,
return a "real" Pipeable Operator.

**Description:**

**BREAKING CHANGE:** 

**Related issue (if exists):**

### CODE REVIEW

**Review by jakovljevic-mladen — CHANGES_REQUESTED** [review]
@EnricoPicci, thanks for your contribution. Changes LGTM, but there's a conflict that needs to be resolved.

**Comment by EnricoPicci** [comment]
@jakovljevic-mladen Thanks for your reply. To be honest I do not know how to resolve this conflict. Can you guide me? Thanks

**Comment by jakovljevic-mladen** [comment]
@EnricoPicci, it's a bit hard 🙂 I can do it for you?

**Comment by EnricoPicci** [comment]
@jakovljevic-mladen if you can do it, please do it. Thanks a lot.

**Review by jakovljevic-mladen — APPROVED** [review]
LGTM, thanks and sorry for waiting this long.

**Pull request merged**
