### PR TITLE
Remove ESDoc related stuff

### PR DESCRIPTION
**Pull request by jakovljevic-mladen**
Hi everyone. Here's a cleanup PR. I'm not completely sure that this should be done, so I've split code changes to three commits, where I hope that at least one or two of them might be merged, if not all.

* I removed a script that was added with this commit 2ef4682f. Based on #4771, ESDoc is removed, so it makes sense to remove it now.
* Also, since `@owner` is removed (51a860b6) from most of the docs, I have removed almost all other `@owner` leftovers. There's only one place where `@owner` appears: `Observable`'s `create` method.
* Since ESDoc is not being used anymore, it makes sense not to have block comments that clearly stated that they were used to affect ESDoc.

Please let me know if these changes make sense. If some of them don't, I can remove them.

### CODE REVIEW

**Comment by niklas-wortmann** [comment]
This is an amazing pull request. Thanks a lot for taking care of this. I need to check it out locally. I'll try to take care of this, this weekend and come back to you!

**Comment by jakovljevic-mladen** [comment]
Thank you @niklas-wortmann. I hope you won't have problems when you try this.

**Comment by jakovljevic-mladen** [comment]
Hey @niklas-wortmann, since this PR changes lots of files, a since lots of conflicts occur over time, please let me know once you start your review, so I can rebase and resolve conflicts at that time. Or, if you want to do it on your own, please do.

**Review by niklas-wortmann — APPROVED** [review]

**Comment by niklas-wortmann** [comment]
pinging @cartant, @kolodny, @benlesh just to double check that this does not affect the generated d.ts files

**Comment by kolodny** [comment]
🤷‍♂️ I wouldn't worry about it IMO, if folks start complaining then we can see what we can do. My gut tells me this is already pretty safe

**Review by kolodny — APPROVED** [review]

**Review by cartant — APPROVED** [review]
LGTM

Thanks for splitting the changes into separate commits, @jakovljevic-mladen This was very easy to review. ❤

**Pull request merged**
