### PR TITLE
fix(shareReplay): subscribe to subject before source subscription starts

### PR DESCRIPTION
**Pull request by josepot**
**Description:**

Addresses #5520

### CODE REVIEW

**Comment by josepot** [comment]
> TBH, I preferred the previous test - the one with the cold, synchronous marbles source.

The problem with using `cold` is that if we run it against master the test should fail, but it passes :disappointed: I think that the scheduler does something behind the scenes that doesn't make the observable completely cold? :man_shrugging: @voliva was the one that came up with the idea of using `from` instead of `cold` and it did the trick (fails on master and passes after the fix)

**Comment by cartant** [comment]
My original, suggested test had an error in it: `!` instead of `|`. A `|` character would represent completion. Does it fail as you'd expect if the marble source completes?

```
(abcd|)
```

If it doesn't, using `from` is fine, but I guess there's a bug if that's the case.

**Comment by voliva** [comment]
> My original, suggested test had an error in it: `!` instead of `|`. A `|` character would represent completion. Does it fail as you'd expect if the marble source completes?

Unfortunately it doesn't - It seems like the "frame 0" doesn't get emitted synchronously when the subscription is made.

**Comment by josepot** [comment]
> My original, suggested test had an error in it: ! instead of |. A | character would represent completion. Does it fail as you'd expect if the marble source completes?

When I try to run this test:
```ts
it('should not skip values on a sync source', () => {
  const a = cold(  '(abcd!)');                       
  const x = cold(  'x-------x');                     
  const expected = '(abcd)--d';                      
                                                     
  const shared = a.pipe(shareReplay(1));             
  const result = x.pipe(mergeMapTo(shared));         
  expectObservable(result).toBe(expected);           
});                            
```
I get the following error:

```bash
Error: cold observable cannot have unsubscription marker "!"
```

**Comment by cartant** [comment]
Yeah, that's the error I made. The source should have had `|` in it, not `!`. It should have been:

```
const a = cold(  '(abcd|)');
```

**Comment by cartant** [comment]
> Unfortunately it doesn't - It seems like the "frame 0" on a cold() doesn't get emitted synchronously when the subscription is made.

Yeah, I guess that would be what's happening. Using `from` is fine. Thanks.

**Comment by josepot** [comment]
yep, sorry for the mess @cartant . I've opened #5522 to demonstrate that the test using `cold` for some reason does pass on `master`.

As much as I struggle with marble tests I do appreciate the value that they add by visually showing what's happening. However, in this particular case it looks like we can't use `cold` to test this

**Comment by cartant** [comment]
Could you add a comment that mentions the use of `from` is deliberate as `cold("(abcd|)")` synchronously emits at frame 0, but is not synchronous-upon-subcription? - so that the `from` source is not unwittingly replaced with a marble at a later date.

I'll have to go through the other tests later, too, as I suspect there are other places in which a source is supposed to be synchronous-upon-subscription and not just the synchronous emission of multiple notifications - e.g. [here](https://github.com/ReactiveX/rxjs/blob/d608cf33791cceb5f330270da96b0b2805223208/spec/operators/share-spec.ts#L209).

**Comment by josepot** [comment]
@cartant please let me know if [this is good enough](https://github.com/ReactiveX/rxjs/pull/5521/files#diff-52f62da75a279650a9e6557aa988f9ceR271-R278), or if you would like for me to change/rephrase that. (English is not my first language and I'm always trying to improve, so please don't hesitate to suggest changes to make it more understandable.

**Pull request merged**
