### PR TITLE
style(tslint): expand tslint rules

### PR DESCRIPTION
**Pull request by kwonoj**
Applied small refactoring along with expanding additional tslint rules.

### CODE REVIEW

**Comment by staltz** [comment]
Great. I remember putting those rules was too aggressive at the time, but now is a good time to add them.

**Comment by kwonoj** [comment]
Yes, I thought also it's considerable to expand more rules into lint. Plans to add couple of more rules further which requires some additional efforts.

**Comment by blesh** [comment]
it looks like there are some lint errors.

> > @reactivex/rxjs@5.0.0-alpha.7 lint_src /Users/blesh/GitHub/blesh/RxJS
> tslint -c .tslintrc src/**/*.ts

> src/operators/expand-support.ts[2, 8]: unused variable: 'Observer'
> src/operators/first.ts[4, 8]: unused variable: 'Observer'
> src/operators/last.ts[4, 8]: unused variable: 'Observer'
> src/operators/shareBehavior.ts[2, 8]: unused variable: 'Scheduler'
> src/operators/switch.ts[2, 8]: unused variable: 'Observer'
> src/operators/takeUntil.ts[47, 21]: block is empty

**Comment by kwonoj** [comment]
Updated PR with changes of
- applying lint rules for rest of codes
- found travis did not run lint after removing duplicated build execution, added lint to be executed

**Comment by blesh** [comment]
Thanks, @kwonoj

**Pull request merged**
