### PR TITLE
docs(UI): Reintroduce Docs Search Capability

### PR DESCRIPTION
**Pull request by pertrai1**
**Description:**

Uncomment the search box for quicker document lookup.

screen shot 2018-08-30 at 3 39 06 am

### CODE REVIEW

**Comment by JWO719** [comment]
We commented that out, because it displayed angular related content. It might be possible that there is none now, after  we have removed most of the angular specific content. But I would like to check it manually

**Comment by pertrai1** [comment]
@JWO719 do you think this will be something that will be good to re-introduce?

**Comment by JWO719** [comment]
Definetly !!! I just couldn't check it yet. Sorry for that. I hope to take a look at it this weekend.

**Comment by pertrai1** [comment]
@JWO719 thanks. I fixed the conflict.

**Pull request merged**
