### PR TITLE
Make 'take' unsubscribe when it reaches the total

### PR DESCRIPTION
**Pull request by Igorbek**
**Description:**

- add a test that highlights the issue being fixed
- add a fix

**Related issue (if exists):**

#1543

### CODE REVIEW

**Comment by staltz** [comment]
Funny, I thought this (existing) test was supposed to cover this case:

```js
  it('should take one values of an observable with many values', () => {
     const e1 = hot('--a--^--b----c---d--|');
     const e1subs =      '^  !            ';
     const expected =    '---(b|)         ';
 
     expectObservable(e1.take(1)).toBe(expected);
     expectSubscriptions(e1.subscriptions).toBe(e1subs);
   });
```

**Comment by kwonoj** [comment]
Maybe cause taksSubscriber completes destination but didn't do it for self? (which this PR added)

**Comment by Igorbek** [comment]
I suspect that case was handled by scheduler logic. Since it's a hot observable, subscriptions linked with scheduled actions.
BTW, do you have any way to test cold synchronous subscriptions/unsubscriptions with marble diagrams? '(abc|)' doesn't really work if I need to test the order of occurrences.

**Comment by blesh** [comment]
> '(abc|)' doesn't really work if I need to test the order of occurrences.

It should... `(abc|)` does NOT match `(bac|)` with our tests.

**Comment by blesh** [comment]
This LGTM.

**Comment by kwonoj** [comment]
Merged with 6cd2f25, added a commit amends assertion in test cases. Thanks @Igorbek ! :tada:

**Pull request closed without merging**
