### PR TITLE
feat(cache): remove `cache` operator

### PR DESCRIPTION
**Pull request by blesh**
Because of all of the confusion around the `cache` operator, this removes the operator
from RxJS ahead of the 5.0.0 release. This is done for a few reasons\:

1. The name `cache` implies it supports all sorts of caching strategies, when this is pretty limited
2. Behavior around unending and hot observables is hard to reason about
3. Once we have a properly designed `cache` operator we can add it at a later time and it will not be a breaking change

### CODE REVIEW

**Comment by blesh** [comment]
related #839 #1718 #2006 #1417 #1405 and many more I'm sure.

**Comment by blesh** [comment]
cc/ @kwonoj @staltz @jayphelps @trxcllnt

**Comment by blesh** [comment]
more related: #2010 #1959

**Comment by jayphelps** [comment]
I'm very very 👍 , but since there's a chance this is controversial, going to wait for others to chime in.

**Comment by kwonoj** [comment]
I'm 👍  too. If it's debatable about behavior need to be settled down, better to make it once instead of changing behavior over different release which can cause confusion.

**Comment by trxcllnt** [comment]
LGTM

**Comment by staltz** [comment]
LGTM

"Cache invalidation" :trollface:

**Comment by tinchou** [comment]
Hey guys. I can't seem to find a simple alternative to `.cache()`. I asked this on [SO](http://stackoverflow.com/questions/41176489/rxjs-5-and-alternatives-to-the-cache-operator), but maybe you can help me out too.

Thanks!

**Comment by zixia** [comment]
It takes me some time to finger out that the `cache` method has gone in v5.0.

I think the better way to _remove_ `cache` is to show a DEPRECATED message when `cache` method is called, and keep it for compatible from earlier code bases.

**Comment by jayphelps** [comment]
@zixia sorry about the confusion. We made the change back in October when v5 was in beta, where we do not make any guarantees about API stability and deprecation cycles. Some of us have talked about possibly doing deprecation warnings if we do similar sweeping removals for future major versions e.g. v6, v7, etc. but we haven't commited to anything cause we don't yet have any such changes. The only breaking change we have queued up is #2174 which slightly changes the behavior of the buffer operator--it's a bugfix, but since it's a _breaking_ bugfix we're holding off on releasing it until v6.

**Pull request merged**
