### PR TITLE
docs(exhaustAll): fix marble diagram

### LINKED ISSUE #6909: exhaustAll marble diagram references deprecated exhaust function
### Describe the bug

The marble diagram in the description references the deprecated "exhaust" function.

### Expected behavior

The text "exhaust" needs be changed to "exhaustAll" in the `exhaust.png` and resulting from that the file should be renamed to `exhaustAll.png`.

### Reproduction code

_No response_

### Reproduction URL

https://rxjs.dev/api/operators/exhaustAll

### Version

7.5.5

### Environment

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jakovljevic-mladen**
**Description:**
This PR fixes exhaustAll marble diagram. Details described in #6909.

@timdp, the latest `ghosts` parameter feature works like a charm, thank you for the quick work on this one. If you publish non-alpha 0.18.1 version before this gets merged, I will update this PR.

**Related issue (if exists):**
Fixes #6909

Thanks @mlegenhausen for reporting.

### CODE REVIEW

**Comment by timdp** [comment]
Cool! I'll probably release the stable version later today. The API will be identical.

Incidentally, you don't need the legacy `swirly-*` packages. I migrated everything to `@swirly/*` a while ago. I thought I'd also created a PR here but maybe something diverged.

**Comment by jakovljevic-mladen** [comment]
Thanks @timdp.

> Incidentally, you don't need the legacy `swirly-*` packages. I migrated everything to `@swirly/*` a while ago.

I'm gonna remove`swirly-parser`, `swirly-renderer-node` and `swirly-types` packages in that case.

**Comment by timdp** [comment]
You can now upgrade to 0.18.1. I've also taken the liberty of adding your diagram to the repo as an example. 🙂

**Comment by benlesh** [comment]
@jakovljevic-mladen ... can you rebase this? You can merge it after that.

**Review by benlesh — APPROVED** [review]

**Comment by jakovljevic-mladen** [comment]
@benlesh, since PRs like this one can be cherry-picked to the V7 branch, shall I do that?

**Pull request merged**
