### PR TITLE
feat(typescript): remove dependency to 3rd party es2015 definition

### LINKED ISSUE #2016: Include es6 type definition via TypeScript compiler or 3rd party module
**RxJS version:**
.Beta.12

**Additional information:**
related to https://github.com/ReactiveX/rxjs/issues/2011#issuecomment-252418870

Lot of confusion from TypeScript user is RxJS rely on some of 3rd party type definition to support ES2015 signatures and they have to install it by themselves. From TS@2.0, there's newly introduced mechanism to supply 3rd party type definition by installing published npm packages, like `es6-shim`(https://www.npmjs.com/package/@types/es6-shim) . 

RxJS can specify them as dependency to remove those issues completely, or set loosely as peerDependency to consumer knows it's requires, feel freely choose between @types package or their own (i.e, typings).

I believe `redux-observable` is aim for similar, /cc @jayphelps as well for opinions.

### PR DESCRIPTION
**Pull request by kwonoj**
**Description:**
This PR enables `lib` option in TypeScript compiler 2.0 to include es2015 native type definitions for cjs build, instead of supplying 3rd party type definition.

**Related issue (if exists):**

closes #2016

### CODE REVIEW

**Comment by kwonoj** [comment]
This seems working by trying out local package generated via `npm pack`, not sure about additional verification approaches.

/cc @david-driscoll , @jayphelps for visibility.

**Comment by david-driscoll** [comment]
Travis stuck?  Should I restart the build?

**Comment by kwonoj** [comment]
yes, let's retrigger. Not sure what happened on travis. For documentation, I think release note woild be suffecient since supplying 3rd party typing was never officially documented. After this change, theoritically any consumer would not need 3rd party definition due to RxJS.

**Comment by blesh** [comment]
LGTM ... merge if you're ready, @david-driscoll

**Pull request merged**
