### PR TITLE
chore(build): Inject tslib functions

### PR DESCRIPTION
**Pull request by imcotton**
To avoid prepend **tslib** globally.

### CODE REVIEW

**Comment by imcotton** [comment]
Odd, unit test seems failed on the master HEAD already, shouldn't caused be this PR I think.

**Comment by kwonoj** [comment]
one another unexpected behavior of `yarn`, it picks up `2.1.1` of TypeScript compiler. 

https://github.com/ReactiveX/rxjs/pull/2120 will resolve build failure by taking out yarn.

**Comment by kwonoj** [comment]
Change.. looks fine to me, but it'd be appreciate to elaborate few details if possible 

- how to test regressions for this changes?
- how much gain after applying this changes?

**Comment by imcotton** [comment]
This PR is the first step toward to its ultimate goal, which depends on two another up coming developments:

  0. Set `--importHelpers` when targeting to TS v2.1
  0. `tslib` module provides full ES6 outputs (Microsoft/tslib#5)
  

Where No.1 lands then below changes will no longer required:

```javascript
rollupInject({
  exclude: 'node_modules/**',
  modules: _.mapValues(tslib, function (value, key) {
    return ['tslib', key];
  }),
})
```


Where No.2 lands then below changes will no longer required:

```javascript
rollupCommonJS({
  namedExports: {
    tslib: Object.keys(tslib),
  },
})
```


The final result will let `Rollup` being able to tree-shakes every helper functions in `tslib` module, but right now this is as near as it gets.

To the test matter that I couldn't figure out yet, would be great to have any suggestion.

**Comment by kwonoj** [comment]
Please allow me some dumb question, as 2.1 is nearby and seems `tslib` change's also suggested as PR, is there specific reason to not to wait those release and make desired change at once? Is this change makes functional changes need to be adapted as soon as possible?

**Comment by imcotton** [comment]
One reason to me is by simply prepending `tslib` for a library bundle seems too rough and aggressive, since it touches global env of user end, another concern is adopting TS v2.1 might not going to happen soon (at least before 5.0 final release).

**Comment by kwonoj** [comment]
So this seems depends on when codebase moves to TS@2.1. I think once it becomes public release (and if there is no regression) it can be upgraded fairly easily as codebase won't have 2.1 specific breaking features. Question would be when'll be planned for v5 public release.

**Comment by imcotton** [comment]
So there are two taking of this PR:

  0. Merge right away, and propose new PR which only minus two plugin calls when requirements satisfied.
  0. Modify current PR to its final shape with labeled `WIP` and waits for the time ready to hit the merge button.

**Comment by Flounn** [comment]
Can you take a decision with this pr? We can't use the Rx.min.js file in an Angular 2 project, we need to rebuild the rxjs library.
Thx

**Comment by jayphelps** [comment]
Can someone explain this to me in laymens? Seems like it's basically don't bundle tslib in global builds, instead rely on it being globally available? If that's the case, this is a breaking change btw.

**Comment by kwonoj** [comment]
@jayphelps no afaik it's how to inject tslib instead of reading tslib directly as file and concat what we do currently. @imcotton can explain in detail.

**Comment by jayphelps** [comment]
We have some thoughts and concerns, we're going to discuss this Monday at our team meeting.

**Comment by imcotton** [comment]
This change is utilizing `rollupInject` plugin to gather global function calls depend on `tslib` during its tree-shaking process, which can be achieved by `--importHelpers` flag from TS v2.1 (see [support for external helpers library][importHelpers]).


[importHelpers]: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-1.html#support-for-external-helpers-library-tslib

**Comment by imcotton** [comment]
I've had rebase against `master` branch.

**Comment by jayphelps** [comment]
Thanks @imcotton !

**Pull request merged**
