### PR TITLE
fix(build_docs): fix doc building

### PR DESCRIPTION
**Pull request by bafolts**
**Description:**

`npm run build_docs` was not working for me. I was missing the escape regular expression dependency and the `@hide` tag was no longer working for me when the custom plug-in would attempt to parse it. I replaced `@hide` with the esdoc `@ignore` tag.

### CODE REVIEW

**Comment by staltz** [comment]
Did you check that those `We need this JSDoc comment for affecting ESDoc.` JSDocs did *not* appear in the generated documentation?

**Comment by bafolts** [comment]
This now appears to build and "hide" for me. I don't see the hidden classes in the generated docs.

**Comment by staltz** [comment]
Ok, I trust your judgement then.

**Comment by staltz** [comment]
LGTM

**Comment by bafolts** [comment]
I don't have write access to merge this. Is there anything else to do on my end prior to merging this?

**Comment by staltz** [comment]
No, just wait. Thanks :)

**Comment by bafolts** [comment]
Once `npm run build_docs` runs for me I get errors about mismatched parameters which I was also going to address and change some of the spread parameters to be spread parameters instead of `input1`, `input2`, should I use this PR for those changes?

**Comment by kwonoj** [comment]
I think it makes sense to update PR freely to address additional issue you'd like to update.

**Comment by blesh** [comment]
I'll try to get this rebased and merged soon.

**Pull request merged**
