### PR TITLE
Remove bindCallback utility

### PR DESCRIPTION
**Pull request by blesh**
The bindCallback util file introduced closure and wasn't completely useful to us over all. Especially now that most `thisArg` arguments have been removed.

This PR removes `bindCallback` in favor of a simple `fn.call(thisArg, a, b, c)` call.

This also fixes some issues with type checking errors in the operators touched, because some of them were sort of leveraging `bindCallback` for type checking when there was an expectation of a function.

### CODE REVIEW

**Comment by blesh** [comment]
closes #889

**Comment by kwonoj** [comment]
Was trying to make changes for this, minutes behind :)

**Comment by kwonoj** [comment]
Can we add one test case into `every-spec` for `should accept thisArg`? rest (map, filter..) does have it.

**Comment by kwonoj** [comment]
Otherwise change looks good to me.

**Comment by blesh** [comment]
> Can we add one test case into every-spec for should accept thisArg? rest (map, filter..) does have it.

Oops, good catch. I'll add that.

**Comment by kwonoj** [comment]
:+1:

**Pull request merged**
