### PR TITLE
feat(AjaxObservable): add "abort" event listener

### LINKED ISSUE #4251: AjaxObservable: does not error when aborted
## Bug Report

Copied from https://github.com/ReactiveX/rxjs/pull/4105

**Current Behavior**
It is possible for an XHR to be aborted externally, for example when the machine loses connectivity, or when the machine is sent to sleep.

Currently, when the XHR is aborted in this way, the observable does not error and the subscription remains.

**Reproduction**
- REPL or Repo link: https://rxjs-yf3lex.stackblitz.io/

```js
import { ajax } from 'rxjs/ajax'

ajax.get('https://httpbin.org/delay/10').subscribe();
```

Whilst request is pending, send machine to sleep.

When machine is woken, request is aborted, but observable did not error.

**Expected behavior**
In this case, I think we would want to error the observable? Although it might also be useful to emit something to indicate it was aborted.

**Environment**
- Runtime: all envs that support `AjaxObservable`
- RxJS version: 6.3.3

**Possible Solution**

**Additional context/Screenshots**

### PR DESCRIPTION
**Pull request by olessavluk**
Closes #4251

**Description:**
This PR add support for [XHR `abort` event.](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequestEventTarget/onabort)

**Reference implementations:**
 - https://github.com/kwonoj/oxid/commit/e783f197b516aeb2151abeb774f820eba6eb9af7#diff-373902f1034fa6a981a40e97e16bee0fR253
 - https://github.com/axios/axios/pull/1399

**Code example**:
```js
import { ajax } from "rxjs/ajax";

const log = prefix => ({
  next: e => console.log(prefix, e),
  error: e => console.log(prefix, e),
  complete: () => console.log(prefix, "complete")
});

const request$ = ajax({
  url: "https://httpbin.org/delay/10",
  progressSubscriber: log("progress: ")
});
const r = request$.subscribe(log("request: "));

// just to simulate Chrome behavior when it aborts your request, 
// no one should do this is his code
r._subscriptions[0].xhr.abort();
```

_Current behavior:_ will do nothing, just hang
_With this patch:_ error will be thrown, and `ProgressEvent` with `type: "abort" ` (see [screenshot](https://i.imgur.com/WG288ts.jpg))

**Browser sleep/wake behavior:** 
 - Chrome, as described in #4251 it will `abort()` pending requests when going to sleep
 - Safari, Firefox does not abort requests
(tested on OS X)

**Related issue (if exists):** Closes #4251

### CODE REVIEW

**Comment by olessavluk** [comment]
It seems like TypeScript complains about XHR `abort` event type. But they were wrong and changed recently, see https://github.com/Microsoft/TSJS-lib-generator/pull/432

Not sure how could I ignore this "error"?

**Comment by benlesh** [comment]
What is the use case for this? No one should be doing this: `r._subscriptions[0].xhr.abort();`, as `_subscriptions` is an implementation detail, and could change in any given version.

**Comment by olessavluk** [comment]
Hi @benlesh 
Yes you are right, but I am running `_subscriptions[0].xhr.abort();` just to emulate Chrome behavior when you put computer to sleep with pending request (as described in #4251).  Also other use cases described in https://github.com/axios/axios/issues/537

**Comment by olessavluk** [comment]
@kwonoj since you have implemented the same feature in [oxid](https://github.com/kwonoj/oxid)
could you please take a look at this PR?

**Comment by olessavluk** [comment]
Hi @benlesh 
Have you been able to review the proposed changes? Are there any concerns regarding the idea or implementation?
I have been using a fork with this fix for quite some time and no issues so far. So can it be merged to official version?

**Comment by rppig42** [comment]
Hi @benlesh，

Since this pr won't be merged. Could you please show us how should we handle aborted request with rxjs?

**Comment by benlesh** [comment]
Closing in favor of #6041 

Sorry for the long wait. Better late than never. :)

**Pull request closed without merging**
