### PR TITLE
Update applications.md

### PR DESCRIPTION
**Pull request by natedean**
**Description:**

**Related issue (if exists):**

Fixed very small typo.

### CODE REVIEW

**Comment by kwonoj** [comment]
Change looks good to me.

**Comment by kwonoj** [comment]
LGTM

**Comment by kwonoj** [comment]
Hmm, seems I don't have privilege to pass LGTM checker. :/

**Comment by trxcllnt** [comment]
Looks good to me too.

**Comment by staltz** [comment]
LGTM

**Comment by staltz** [comment]
> Hmm, seems I don't have privilege to pass LGTM checker. :/

Maybe I do, as it just changed to green after I said LGTM

**Comment by kwonoj** [comment]
@staltz interesting, I tried same `LGTM` on https://github.com/ReactiveX/rxjs/pull/1797 but couldn't make it work.

**Comment by kwonoj** [comment]
@natedean would you mind rebase this PR? merge's blocked by branch's out-of-date.

**Pull request merged**
