### PR TITLE
refactor(WIP): WIP on subscription refactor DO NOT MERGE

### PR DESCRIPTION
**Pull request by blesh**
Attn @trxcllnt, who I know is working on similar refactors.

I think we should just put up a different branch and work against that. It will likely take multiple PRs to straighten out this refactor.

### CODE REVIEW

**Comment by blesh** [comment]
Actually, @trxcllnt, I've done just that... this is merged into a `subscription-refactor` branch here. Let's try to work off of that. Basically the game is now to get all tests green and add tests around issues that other people have seen. 

cc @staltz, @kwonoj 

This is probably our biggest priority at the moment.

**Comment by blesh** [comment]
Here is the branch: https://github.com/ReactiveX/RxJS/tree/subscription-refactor

**Comment by trxcllnt** [comment]
@blesh we should start with #1065 merged in. I started my own branch from that PR on Friday and got fairly far, I think I might continue with that and see if I can solve it there, then merge that branch into this one.

**Comment by trxcllnt** [comment]
@blesh this is finished in [my branch](https://github.com/trxcllnt/RxJS/tree/subscription-refactor).

**Comment by staltz** [comment]
@trxcllnt since your commits touched ConnectableObservable, I'd recommend pulling in the tests I wrote in PR #1042 into your branch and make sure the tests pass there.

**Comment by blesh** [comment]
@trxcllnt did you want to submit a PR?

**Pull request closed without merging**
