### PR TITLE
feat(delayWhen): add index to the selector function

### PR DESCRIPTION
**Pull request by kwonoj**
#2388

This is for re-merge https://github.com/ReactiveX/rxjs/pull/2409, all credit goes to @martinsik .

**Description:**

**Related issue (if exists):**

### CODE REVIEW

**Comment by benlesh** [comment]
Ugh. @kwonoj, can we get this updated? Perhaps a new PR if necessary?

**Comment by benlesh** [comment]
This needs refactored add added to v6 :\ . Ugh, the backlog... haha.. sorry @kwonoj

**Comment by martinsik** [comment]
@benlesh I made the original commit so I can have a look at it.

**Comment by cartant** [comment]
@benlesh This should be rebased and ready for review/merge.

**Pull request merged**
