### PR TITLE
docs(generate): add `the` and other improvements

### PR DESCRIPTION
**Pull request by robstoll**
**Description:**

**Related issue (if exists):**

### CODE REVIEW

**Comment by cartant** [comment]
Thanks. CI is breaking for reasons that are unrelated to this PR. :sob: I'll merge this once I get the build working in CI.

**Comment by robstoll** [comment]
I guess the failure is related to https://github.com/ReactiveX/rxjs/commit/b1c35738204b5b1a5d325a16e70cdbf25b523976 good luck

**Comment by cartant** [comment]
@robstoll Can you please rebase this onto the current `master` - that should address the CI failure.

**Comment by robstoll** [comment]
I'll do it later on as I need to clone the repo first (did the PR via browser)

**Comment by robstoll** [comment]
I am closing this PR in favour of #5265

**Pull request closed without merging**
