### PR TITLE
chore(build): copy source for sourcemaps

### LINKED ISSUE #1089: npm distribution and source maps
Files distributed to npm got source maps (which is good!) but those source maps are pointing to source file that are not included. An example from `Operator.js.map`:

> {"version":3,"file":"Operator.js","sourceRoot":"","sources":["../../src/Operator.ts"],"names":["defaultCallFn"],"mappings":"AACA,2BAAyB,cAAc,CAAC,CAAA;AAMxC,uBAAoC,QAAqB;IACvDA,MAAMA,CAACA,IAAIA,uBAAUA,CAAIA,QAAQA,CAACA,CAACA;AACrCA,CAACA;AAFe,qBAAa,gBAE5B,CAAA"}

See this little `"sources":["../../src/Operator.ts"]` thingy here? 

2 solutions I can think of:
* inline
* distribute sources

### PR DESCRIPTION
**Pull request by robwormald**
- copy TS source to amd/cjs/ES6 distros
- use sourceRoot option to make sourcemaps point to appropriate paths

closes #1089

### CODE REVIEW

**Comment by blesh** [comment]
@robwormald it looks like there's a minor hiccup with this: 

`ENOENT: no such file or directory, open 'dist/cjs/add/observable/src/add/observable/bindCallback.ts'`

I think it's just because something is trying to reference a file that was recently removed from the library. Also, can you rebase?

**Comment by blesh** [comment]
> I think it's just because something is trying to reference a file that was recently removed from the library. 

I'm conflating `util/bindCallback.ts` and `observable/bindCallback.ts`. So something screwy is going on here.

**Comment by blesh** [comment]
@robwormald just waiting for a rebase on this.

**Comment by gdi2290** [comment]
:+1:

**Comment by trxcllnt** [comment]
@robwormald btw I fixed the merge commits in https://github.com/trxcllnt/RxJS/tree/pr-1093 but github is complaining about unresolvable merge conflicts when I try to issue a PR to your branch... so if you just want to copy the `package.json` from my branch and `git push -f` your branch then we can close this out.

**Comment by robwormald** [comment]
closing this so Ben stops abusing me on twitter (also cuz its a bit wrong, but that's secondary). will re-open after discussion.

**Comment by blesh** [comment]
Rob can't handle the truth

**Pull request closed without merging**
