### PR TITLE
docs(zip): Fixed typo in the zip operator docstring

### PR DESCRIPTION
**Pull request by CaselIT**
**Description:**
Fixes a typo in the description of the zip operator

### CODE REVIEW

**Comment by staltz** [comment]
Looks good

**Comment by blesh** [comment]
LGTM, just waiting for the CI to complete after resolving a conflict.

**Comment by blesh** [comment]
Looks like the conflict resolution added some trailing whitespace, and the commit message seems to not match the convention.

**Comment by CaselIT** [comment]
Should I force push a new commit with the correct name?
BTW tslint v4.4 has a sort of but in the rule no-tailing-whitespaces since it does not skip the comments

**Comment by blesh** [comment]
@CaselIT I fixed the trailing whitespace here on Github, simple fix... we'll see if it passes CI. If it does, I'll squash and merge and I will fix the commit message when I do that.

Thanks again! :heart:

**Comment by CaselIT** [comment]
Let me know if I can help. 👍

**Pull request merged**
