### PR TITLE
docs(README): add browser test coverage matrix

### PR DESCRIPTION
**Pull request by kwonoj**
relates to #998 

Now travis connected to saucelab with account name `rxjs5` for main repo, updating badge to display its latest status. (Unfortunately all flags are red currently :( )

### CODE REVIEW

**Comment by kwonoj** [comment]
@blesh , will deliver account details. You can change email address, password accordingly.

**Comment by luisgabriel** [comment]
:+1: :+1:

**Comment by kwonoj** [comment]
This one's waiting confirmation of using `rxjs5` account for browser testing. Once I got sign good to go, I'll check in this myself. /cc @blesh for visibility.

**Comment by blesh** [comment]
Got it. I'll set this up by Monday. If I don't, ping me again over Twitter, @kwonoj. It's a high priority for me, but I'm liable to be busy being a dad over the weekend.

**Comment by kwonoj** [comment]
Will do. @blesh , just clarify - all setup's are already in placed, only thing you (may) need is login and change email address to remove my corporate account.

**Comment by kwonoj** [comment]
+ have nice dad weekend, I also believe family's important, highest priority. :)

**Comment by blesh** [comment]
Merged with 27a19cc... nice, @kwonoj!

**Comment by kwonoj** [comment]
Thanks @blesh :) I think this PR can be closed - closing myself.

**Pull request closed without merging**
