### PR TITLE
windowToggle: fixes and tests

### PR DESCRIPTION
**Pull request by staltz**

### CODE REVIEW

**Comment by blesh** [comment]
I should've asked for this before I merged the `bufferToggle` fixes... @staltz, can you add a more detailed message about what bugs were fixed? Something specific, like "fix(windowToggle): will no longer call crank-call the nearest pizza store when passed an empty observable".  "fix bugs to pass tests" doesn't tell me what it fixed.

Thanks!

**Comment by staltz** [comment]
Sure I can do that. There were many bugs, that's why I wrote the generic message.

**Comment by blesh** [comment]
Perfect, thanks, @staltz!

**Comment by blesh** [comment]
Great! merged with 0cb21e6!

**Pull request closed without merging**
