### PR TITLE
feat(debug): Adds the debug() operator

### PR DESCRIPTION
**Pull request by Boshen**
#2509

### CODE REVIEW

**Comment by kwonoj** [comment]
Perspective of usefullness I agree this is kind of common pattern, but I don't think this is needed operator as core level. Given changes can be trivially implemented in user code, while making this into core does not provides addition feature level enhancement or improvement compare to use level. I'd rather recommend to something similar to 

```
const dbg = (o) => {
 if(prod) return o; //user code specific prod detection
 return o.do (logger.xxx...); //or console, depends on code
}

OtherObservable.let(dbg).otheroperator ()...
```

Achieves similar shorthanded expression.

**Comment by Boshen** [comment]
Ha .. I've never noticed the `let` operator until you mention it. Your solution works for me since it's so trivial to add to a project. But I still think this is a nice thing to have in the core because it removes a lot of friction for all our developers :-)

Now I wonder whether there is separate repo for things like this, where a common pattern is abstracted, and it just combines operators from the core.

**Comment by staltz** [comment]
Hi @Boshen , thank you for taking your time to send us this PR. I understand your desire for this operator (I myself built a stream library xstream that has [debug](https://github.com/staltz/xstream/#debug)), but I want to explain how adding operators to RxJS may bring problems.

Every operator added means more maintenance to be done, more analysis paralysis for a developer looking for core (essential) operators, and overall weight of this library. @kwonoj pointed out a good solution for this. It would be awesome to make an RxJS **ecosystem**, not an RxJS framework. You can publish the debug operator as a separate npm package, and then users can import that and use it with `let()`. Right now, it seems like there should be one more operator in RxJS core, but I want to help show how a lot of operators could simply be served as separate packages. We don't want this library to get 300+ operators, right?

**Comment by Boshen** [comment]
Right. Thank you all for the responses @kwonoj and @staltz :-)

**Pull request closed without merging**
