### PR TITLE
docs(buffer): add PNG diagrams to JSDoc for buffer operators

### PR DESCRIPTION
**Pull request by staltz**
Add PNG marble diagram images on the inline documentation for each buffer-like operator, and fix
some typos and mistakes with JSDoc.

### CODE REVIEW

**Comment by staltz** [comment]
@kwonoj This PR works as an example of how should we write the docs for all operators so that they have their marble diagram images embedded.

**Comment by luisgabriel** [comment]
:+1:

**Comment by kwonoj** [comment]
This one's cool. One thing - tried locally and could see marble diagram generation is not yet included in docgen process, is my understanding correct?

**Comment by staltz** [comment]
Ah yeah, it's not yet included in docgen process.

**Comment by kwonoj** [comment]
What about add those changes also in this PR? It may possible some people think img links are broken if this changes are checked in and docs published before image's actually generated.

**Comment by staltz** [comment]
Yes I'll add them.

**Comment by staltz** [comment]
@kwonoj I added PNG diagram generation to `docgen.sh`.

**Comment by kwonoj** [comment]
Tried PR locally and seeing img links still not displayed - docs are placed under `docs` and looks for `docs/img` and seems images are not copied under `docs`.

**Comment by staltz** [comment]
That's because `docgen.sh` moves index.html from `docs` to `./` (root).

**Comment by kwonoj** [comment]
Shouldn't image also need to be copied accordingly in this case? (Not sure, checking it - I don't want to check in those into `gh-pages` myself to only check its results)

**Comment by staltz** [comment]
Good point.

**Comment by staltz** [comment]
Alright, fixed @kwonoj

**Comment by kwonoj** [comment]
Cool, tried locally and works as expected. 

Change looks good to me. I'll check this around late today if @blesh does not have any other suggestions.

**Comment by kwonoj** [comment]
Merged with abbf4e7, thanks @staltz

**Comment by staltz** [comment]
@kwonoj can you run `docgen.sh` to update http://reactivex.io/RxJS ?

**Comment by kwonoj** [comment]
@staltz Yes I can (technically). What about run it once after https://github.com/ReactiveX/RxJS/pull/1157 is checked in?

**Comment by staltz** [comment]
Yeah that's ok

**Pull request closed without merging**
