### PR TITLE
fix(cache): get correct caching behavior

### LINKED ISSUE #1628: incorrect behavior of cache()
**RxJS version:** 5.0.0-beta.6

**Code to reproduce:** 

```javascript
Rx.Observable
  .fromPromise(new Promise((res) => res(true)))
  .map(() => 'abc')
  .do(() => console.log('LOG_1'))
  .cache()
  .do(() => console.log('LOG_2'))
  .flatMap(() => Rx.Observable.timer(500)
    .flatMap(() => Rx.Observable.throw('ERR')))
  .retry(3)
  .subscribe(() => {})
```

**Expected behavior:** `LOG_1` should happen once and `LOG_2` four times:
```
LOG_1
LOG_2
LOG_2
LOG_2
LOG_2
```
Similarly to: 
```javascript
Rx.Observable.timer(1000)
  .map(() => 'abc')
  .do(() => console.log('LOG_1'))
  .cache()
  .do(() => console.log('LOG_2'))
  .flatMap(() => Rx.Observable.timer(500)
    .flatMap(() => Rx.Observable.throw('ERR')))
  .retry(3)
  .subscribe(() => {})
```

**Actual behavior:** `LOG_1` appears four times, moreover after `retry` the order of logs is reversed.
```
LOG_1
LOG_2
LOG_2
LOG_1
Uncaught ObjectUnsubscribedError
LOG_2
LOG_1
Uncaught ObjectUnsubscribedError
LOG_2
LOG_1
Uncaught ObjectUnsubscribedError
```

**Additional information:** Both code snippets generate: `Uncaught ObjectUnsubscribedError` after each retry. [demo](http://plnkr.co/edit/73s3KoDo8datezbLFc7W?p=preview)

### PR DESCRIPTION
**Pull request by blesh**
This is an initial pass at fixing the cache operator. There is still a lot to do, but this is merge-worthy IMO. Ideally, the cache operator would use the lift mechanism. Also this is not well optimized as it is introducing a lot of closures. But it works, and that's the point for now.

fixes #1628

### CODE REVIEW

**Comment by blesh** [comment]
(finally) lol

**Comment by blesh** [comment]
Merged after quick review from @kwonoj

**Comment by staltz** [comment]
Kind of sad that it's all "rx4", but you know that already.

**Comment by blesh** [comment]
@staltz, yeah, I'll iterate on it.

**Comment by trxcllnt** [comment]
@blesh Is the difference between this and `source.multicast(() => new ReplaySubject()).refCount()` that this only recycles the ReplaySubject when the source emits an error (as opposed to when the subscriber count drops to 0)?

To phrase it another way, it seems like this operator now permanently leaks memory until the source emits an error. If true, this troubles me greatly.

**Comment by blesh** [comment]
Where is the leak? Can it be demonstrated?

**Comment by trxcllnt** [comment]
@blesh 

```
// push 1000000 numbers into cache's ReplaySubject
const source = Observable.range(0, 1000000).cache();
source.take(100000).subscribe({
  complete() {
    console.log('cache's ReplaySubject now has 100000 values')
  }
});

// cache now has a reference to a ReplaySubject with 100000 values and the only way to release the reference for GC is to set source to null (but I can't, since source is a const).
```

**Comment by matthewwithanm** [comment]
Is there documentation anywhere about how `cache()` is supposed to work now?

**Pull request merged**
