### PR TITLE
fix(operators): export reserved name operators on prototype

### LINKED ISSUE #1924: _catch vs catch breaks ESM code built against the rxjs umd bundle
**RxJS version:**
beta.11

**Code to reproduce:**
```
import {_catch} from 'rxjs/operator/catch';
```
full source: https://github.com/angular/angular/blob/ee88c3c976654f15d41f8d35345ad96026fe5fe8/modules/%40angular/router/src/apply_redirects.ts#L14

+ rollup config:
```
export default {
  entry: '../../../dist/packages-dist/router/index.js',
  dest: '../../../dist/packages-dist/router/bundles/router.umd.js',
  format: 'umd',
  moduleName: 'ng.router',
  globals: {
    ...
    'rxjs/operator/catch': 'Rx.Observable.prototype'
  }
}
```
full source: https://github.com/angular/angular/blob/ee88c3c976654f15d41f8d35345ad96026fe5fe8/modules/%40angular/router/rollup.config.js#L30

**Expected behavior:**

the router bundle should be able to get hold of the `_catch` operator from the prototype via `_catch` property.

**Actual behavior:**

the `_catch` operator is not found because in the UMD bundle it was exported as `catch` (without the leading underscore).

**Additional information:**

Angular router bug that first raised this issue: https://github.com/angular/angular/issues/11300
Reproduction: http://plnkr.co/edit/aSPFwbLNxlT5sQzSyGIN?p=preview

### PR DESCRIPTION
**Pull request by robwormald**
closes #1924

### CODE REVIEW

**Comment by robwormald** [comment]
cc @IgorMinar

**Comment by jayphelps** [comment]
Had an extraneous semicolon that was failing the build, so I removed it. Used it as an opportunity to try out the new ability for maintainers to [modify submitted PR branches](https://github.com/blog/2247-improving-collaboration-with-forks) directly (even `push -f`!!) So handy.

Although I don't _like_ this solution, I can't think of any other one. This whole underscore business is unfortunate to begin with. So that said, I think this is acceptable.

I'll wait a few days to see if anyone wants to object?

**Comment by blesh** [comment]
LGTM

**Comment by blesh** [comment]
Needs rebase tho

**Comment by IgorMinar** [comment]
rebased as #1932

**Comment by jayphelps** [comment]
@IgorMinar I rebased this already, is that the only change?

**Comment by IgorMinar** [comment]
@jayphelps I just rebased. no other changes.

**Pull request merged**
