### PR TITLE
build(global): enable aggressive closure optimization

### PR DESCRIPTION
**Pull request by kwonoj**
**Description:**
This PR enables 'ADVANCED' optimization in closure compiler to generate more compressed minified global build. 

Size comparsion:
image

gain around ~30kb of more compression.

I'm marking it as **BLOCKED** - cause there isn't reliable way to validate regressions of this optimization. I have filed related issue https://github.com/ReactiveX/rxjs/issues/2229, which'll allow to test global builds correctly on browsers.

**Related issue (if exists):**
https://github.com/ReactiveX/rxjs/issues/2229
https://github.com/ReactiveX/rxjs/pull/2227
https://github.com/ReactiveX/rxjs/pull/2225

### CODE REVIEW

**Comment by trxcllnt** [comment]
nice looking forward to this!

**Comment by blesh** [comment]
@kwonoj do you think we could validate regressions by somehow building and running the specs against the this optimized build? This seems like something we should prioritize.

**Comment by kwonoj** [comment]
As noted in PR, I already filed https://github.com/ReactiveX/rxjs/issues/2229 to change browser testing's target to use UMD build instead of CJS. I gave a quick shot and found it wasn't trivial though.

**Comment by kwonoj** [comment]
I'm going to close this for now and reopen once we have pipeline for testing against browser.

**Pull request closed without merging**
