### PR TITLE
fix(tap): typings for observer overload of tap

### PR DESCRIPTION
**Pull request by josepot**
**Description:**
An attempt to fix the issue described on #5614 

**Related issue (if exists):**
 #5614

### CODE REVIEW

**Comment by cartant** [comment]
FYI, this should include a dtslint test - ideally in a separate commit that's fixed by a change included in a subsequent commit.

**Comment by josepot** [comment]
> FYI, this should include a dtslint test - ideally in a separate commit that's fixed by a change included in a subsequent commit.

Yep, sorry! Also, I just realized that this is not the correct fix... Because, I'm pretty sure that `tap` should never alter the type of the source, right?

So, I will close this PR, I will wait for the bug to be confirmed and I will try to come up with a better solution if the issue actually gets confirmed. Thanks!

**Comment by cartant** [comment]
I suspect this is v6-only and relates to this signature messing up the inference:

https://github.com/ReactiveX/rxjs/blob/075af28f2567188d6feb0ee26b4a91a5dcded3ed/src/internal/Subject.ts#L61

That signature has changed in v7 - i.e. `master`.

**Comment by josepot** [comment]
> I suspect this is v6-only and relates to this signature messing up the inference:

Makes sense! Also, I tested it and you are correct, this issue is fixed on [`7.0.0-beta.3`](https://codesandbox.io/s/jolly-mclean-oe95e?file=/src/index.ts)

**Pull request closed without merging**
