### PR TITLE
Simplify test script pipeline

### PR DESCRIPTION
**Pull request by kwonoj**
**Description:**
This PR fixes https://github.com/ReactiveX/rxjs/issues/2850, also revises current build pipeline around unit tests. Our test setup is quite complex, by using compiled output from src for importing modules, then build each (src, spec) separately to run test cases. This also causes coverage remapping tricky, as recent change caused.

Instead, PR changes test cases to require sources directly - then run compile just once for specs and create coverage as well. It get rid of few npm scripts for testing purpose only, performance wise doesn't have much differences.

Few caveat is it requires to update some other scripts like doc generation but it can be dealt with seperately.

**Related issue (if exists):**
- closes https://github.com/ReactiveX/rxjs/issues/2850.

### CODE REVIEW

**Comment by kwonoj** [comment]
@benlesh for reviewing. Mostly it doesn't touch functionality but also it touches huge number of files.

**Comment by benlesh** [comment]
This looks great OJ, I'll try to pull this down and run it locally before I merge it very soon.

**Comment by benlesh** [comment]
Apologies, @kwonoj, I dropped the ball on looking at this. We might want to wait until the 5.5 version is released and then come back to this, as the packaging/building scripts are in a little bit of flux right now.

**Comment by kwonoj** [comment]
I'm fine with that, feel freely to do so.

**Comment by benlesh** [comment]
Okay... so this looks okay... however a 4% drop in code coverage is HUGE. We should look into that before proceeding.

**Comment by kwonoj** [comment]
@benlesh it's good now, it was just glob wasn't smart enough to pick all test files. coverage change is within the threshold.

**Pull request merged**
