### PR TITLE
Scalar perf

### PR DESCRIPTION
**Pull request by blesh**
Adding a bunch of overrides to ScalarObservable to optimize performance. This is an approach different than what we've done in the past, in that it puts an override directly on ScalarObservable, rather than doing type-checking in the functions themselves.

Here is a list of results (Before and After):

```
Before

                                         |                     RxJS 4.0.1 |             RxJS 5.0.0-alpha.3 |          factor |      % improved
---------------------------------------------------------------------------------------------------------------------------------------------------
         filter-scalar-false - immediate |               717,228 (±1.17%) |             1,516,863 (±0.45%) |           2.11x |          111.5%
          filter-scalar-true - immediate |               524,921 (±0.62%) |               966,993 (±0.65%) |           1.84x |           84.2%
                  map-scalar - immediate |               641,470 (±0.87%) |             1,372,438 (±0.62%) |           2.14x |          114.0%
        reduce-scalar-noseed - immediate |               687,545 (±1.95%) |             2,429,996 (±0.81%) |           3.53x |          253.4%
               reduce-scalar - immediate |               483,549 (±0.72%) |             1,119,916 (±1.03%) |           2.32x |          131.6%
          scan-scalar-noseed - immediate |               220,031 (±0.60%) |             2,422,950 (±0.67%) |          11.01x |        1,001.2%
                 scan-scalar - immediate |               189,861 (±1.00%) |             1,161,650 (±0.51%) |           6.12x |          511.8%
                count-scalar - immediate |               745,924 (±0.67%) |             2,462,605 (±0.58%) |           3.30x |          230.1%
               skip-scalar-0 - immediate |               703,792 (±0.76%) |             2,545,683 (±0.52%) |           3.62x |          261.7%
     skip-scalar-outofbounds - immediate |               635,857 (±0.61%) |             1,825,839 (±0.78%) |           2.87x |          187.1%
                 take-scalar - immediate |               707,963 (±0.50%) |             2,576,310 (±0.68%) |           3.64x |          263.9%








After

                                         |                     RxJS 4.0.1 |             RxJS 5.0.0-alpha.3 |          factor |      % improved
---------------------------------------------------------------------------------------------------------------------------------------------------
         filter-scalar-false - immediate |               704,688 (±3.42%) |             6,231,688 (±0.79%) |           8.84x |          784.3%
          filter-scalar-true - immediate |               520,997 (±0.97%) |             1,970,056 (±0.53%) |           3.78x |          278.1%
                  map-scalar - immediate |               626,140 (±1.73%) |             4,051,141 (±0.76%) |           6.47x |          547.0%
        reduce-scalar-noseed - immediate |               674,846 (±1.43%) |             4,074,599 (±0.88%) |           6.04x |          503.8%
               reduce-scalar - immediate |               468,252 (±0.53%) |             2,007,994 (±0.71%) |           4.29x |          328.8%
          scan-scalar-noseed - immediate |               217,599 (±2.10%) |             4,043,362 (±0.80%) |          18.58x |        1,758.2%
                 scan-scalar - immediate |               192,236 (±0.52%) |             1,970,688 (±0.94%) |          10.25x |          925.1%
                count-scalar - immediate |               691,734 (±2.01%) |             4,107,881 (±0.73%) |           5.94x |          493.9%
               skip-scalar-0 - immediate |               704,049 (±1.31%) |             4,115,490 (±0.65%) |           5.85x |          484.5%
     skip-scalar-outofbounds - immediate |               647,033 (±0.55%) |             2,456,657 (±0.85%) |           3.80x |          279.7%
                 take-scalar - immediate |               688,545 (±1.71%) |             4,030,593 (±0.54%) |           5.85x |          485.4%
```

### CODE REVIEW

**Comment by blesh** [comment]
Some of these are silly... like "why would someone ever `reduce` or `skip(2)` a scalar observable? But it's an inexpensive optimization, and the answer is "maybe they didn't know they had a scalar because they received it dynamically".

**Comment by luisgabriel** [comment]
Nice job! Impressive results. ;)

:+1:

**Comment by trxcllnt** [comment]
@blesh 👌🏽👍🏽💪🏽

**Comment by staltz** [comment]
> Some of these are silly... like "why would someone ever reduce or skip(2) a scalar observable? But it's an inexpensive optimization, and the answer is "maybe they didn't know they had a scalar because they received it dynamically".

True, I know it can be quite common not to assume anything about the given Observable and still apply some operators on it. So they might look silly but are important, because it would be nice if Rx broke or threw errors for those cases.

**Pull request merged**
