### PR TITLE
feat(shareBehavior): add shareBehavior and its tests

### PR DESCRIPTION
**Pull request by staltz**

### CODE REVIEW

**Comment by blesh** [comment]
This is bike-shedding, but wasn't this called "shareValue" before? Is that a better term? What would make the most sense for people new to the library? (FWIW: I found the name of "BehaviorSubject" to be essentially nonsense when I first started using Rx)

**Comment by blesh** [comment]
Also, wasn't there a problem with `shareBehavior`, @staltz? Or was that only for `shareReplay`? (The problem being that it creates a new Subject in it's multicast)

**Comment by staltz** [comment]
> This is bike-shedding, but wasn't this called "shareValue" before? Is that a better term?

It was, but we [discussed here and reached a consensus](https://github.com/ReactiveX/RxJS/issues/298#issuecomment-139609578) to align the sharing names to their respective subjects, for symmetry: 
- share uses Subject
- shareReplay uses ReplaySubject
- shareBehavior uses BehaviorSubject

To rename it to shareValue would mean also renaming BehaviorSubject to ValueSubject. I'm not contesting that actually. My brain got used to BehaviorSubject as a name, and perhaps to people migrating to v5 it would be easier to keep the same names, but I actually agree that ValueSubject would be more intuitive.

> Also, wasn't there a problem with shareBehavior, @staltz? Or was that only for shareReplay?

Both shareBehavior and shareReplay "have problems" ([this issue](https://github.com/ReactiveX/RxJS/issues/453)), and these tests are not covering those problems yet. So this PR here is agnostic to whatever happens to our decision regarding issue #453. When that's decided, we need to add more tests for these sharing operators.

**Comment by blesh** [comment]
Okay, thanks for the clarification. Looking over this in more detail it looks fine. Sorry, I was going through 30+ PRs or something yesterday. LOL.

**Comment by blesh** [comment]
merged with 97ff1ec, thanks @staltz

**Pull request closed without merging**
