### PR TITLE
test(takeUntil): add marble tests for takeUntil operator

### PR DESCRIPTION
**Pull request by kwonoj**
Migrating RxJS 4 tests for takeUntil operator.

### CODE REVIEW

**Comment by blesh** [comment]
This one fell victim to linting errors.

```
   13:1    error  Trailing spaces not allowed                no-trailing-spaces
   14:91   error  Missing space before function parentheses  space-before-function-paren
   18:1    error  Trailing spaces not allowed                no-trailing-spaces
   21:1    error  Trailing spaces not allowed                no-trailing-spaces
   26:1    error  Trailing spaces not allowed                no-trailing-spaces
   29:1    error  Trailing spaces not allowed                no-trailing-spaces
   34:1    error  Trailing spaces not allowed                no-trailing-spaces
   37:1    error  Trailing spaces not allowed                no-trailing-spaces
   42:1    error  Trailing spaces not allowed                no-trailing-spaces
   45:1    error  Trailing spaces not allowed                no-trailing-spaces
   50:1    error  Trailing spaces not allowed                no-trailing-spaces
   53:1    error  Trailing spaces not allowed                no-trailing-spaces
   58:1    error  Trailing spaces not allowed                no-trailing-spaces
   61:1    error  Trailing spaces not allowed                no-trailing-spaces
   66:1    error  Trailing spaces not allowed                no-trailing-spaces
   69:1    error  Trailing spaces not allowed                no-trailing-spaces
   74:1    error  Trailing spaces not allowed                no-trailing-spaces
   77:1    error  Trailing spaces not allowed                no-trailing-spaces
   78:92   error  Missing space before function parentheses  space-before-function-paren
   82:1    error  Trailing spaces not allowed                no-trailing-spaces
   85:1    error  Trailing spaces not allowed                no-trailing-spaces
   86:65   error  Missing space before function parentheses  space-before-function-paren
   91:1    error  Trailing spaces not allowed                no-trailing-spaces
   94:1    error  Trailing spaces not allowed                no-trailing-spaces
   95:105  error  Missing space before function parentheses  space-before-function-paren
   97:43   error  Missing space before function parentheses  space-before-function-paren
   97:63   error  Missing semicolon                          semi
  100:1    error  Trailing spaces not allowed                no-trailing-spaces
  104:1    error  Trailing spaces not allowed                no-trailing-spaces
  105:82   error  Missing space before function parentheses  space-before-function-paren
  108:46   error  Missing space before function parentheses  space-before-function-paren
  108:72   error  Trailing spaces not allowed                no-trailing-spaces
  110:1    error  Trailing spaces not allowed                no-trailing-spaces
```

**Comment by kwonoj** [comment]
Yes, PR was created before linting was introduced. I'll update PR.

**Comment by blesh** [comment]
Thank you so much, @kwonoj

**Comment by kwonoj** [comment]
OK, rebased + lint satisfied.

**Comment by blesh** [comment]
Merged with ec7ff1c... thanks @kwonoj

**Pull request closed without merging**
