### PR TITLE
docs(versioning): add versioning to docs website

### PR DESCRIPTION
**Pull request by niklas-wortmann**

### CODE REVIEW

**Comment by benlesh** [comment]
I'm not sure which one of these to look at? #5793

**Comment by niklas-wortmann** [comment]
Sorry @benlesh this one is the v7 docs merging in the master branch the other one is the V6 branch in the 6.x branch. The changes are pretty much identical though

**Comment by benlesh** [comment]
Overall, this looks fine to me... however, I do think we had discussed trying to do something with sub directories instead? I guess I would like to more about how all of this works. We're deploying more than one version of the site?

**Comment by benlesh** [comment]
I see.. it looks like angular is doing a thing with v6.angular.io, v7.angular.io, .... , angular.io (current), next.angular.io 

I guess my only concern with that is it's not super intuitive to switch or know which one you're looking at. Particularly on mobile.

**Comment by benlesh** [comment]
This needs rebased as well. Overall LGTM.

**Comment by niklas-wortmann** [comment]
rebased. Just to sum up the plan I had for the docs versioning:
next.rxjs.dev always shows the docs of the upcoming major release
rxjs.dev shows the latest stable major version
vX.rxjs.dev will have the latest docs version for that major release

**Review by benlesh — APPROVED** [review]
Rebase and merge when you're ready, please.

**Pull request merged**
