### PR TITLE
fix(throw): Observable.throw() now returns Observable<never>

### PR DESCRIPTION
**Pull request by mernen**
**Description:** `Observable.never()`, `Observable.empty()` and `.ignoreElements()` were previously changed to `Observable<never>`; this patch complements it with `Observable.throw()`.

**Related issue (if exists):** #2640 and its PR #2691

### CODE REVIEW

**Comment by benlesh** [comment]
I don't think `never` is the right type here, as it does have a value type.  If anything maybe in this case we actually want to give it a type of some sort, because we actually know what it is. But everywhere it could be handled, it's still `any` though, so it probably doesn't matter.

I think we're going to pass on this PR, unless I misunderstand the intent.

cc @kwonoj

**Comment by mernen** [comment]
I believe `never` is the right parameter here, what it means (when the signature of `Observable<never>` is fully expanded) is that the method `next()` will never be called (while saying nothing about `complete()` or `error()`).

The main practical appeal of this change, and why I proposed it in the first place, is that `never` disappears when folded in a sum, while `any` “infects” the sum. For example, `concat(of(1, 2, 3), _throw(Error()))` currently is inferred as `Observable<any>`, while with my patch it becomes `Observable<number>`.

**Comment by staltz** [comment]
As in #2640 I was opposed to the `never` until they informed me that `never` disappears when type summed with others, so this PR seems like the right way to go. A merge or a concat of `Observable<number>` with `Observable<any>` (from throw) would give `Observable<any>` which is inaccurate and the type system knows better. Merging or concatenating `Observable<number>` with `Observable<never>` gives `Observable<number>`.

**Comment by kwonoj** [comment]
Sorry for late peeking, lemme try few things on my end too.

**Comment by benlesh** [comment]
I'm convinced. I think this is right, too. The PR just needs fixed (and rebased) so the build isn't failing.

**Comment by benlesh** [comment]
This change is now included in the `throwError` refactor. Closing this PR in favor of #3288

**Pull request closed without merging**
