### PR TITLE
test(finally): add test for the use of thisArg argument

### PR DESCRIPTION
**Pull request by staltz**

### CODE REVIEW

**Comment by kwonoj** [comment]
Maybe it's good time to discuss about make decision around drop `thisArg`? https://github.com/ReactiveX/RxJS/pull/744 is blocked for similar reason currently.

**Comment by staltz** [comment]
I'd be fine with dropping thisArg everywhere and also this PR. This PR was just a product of my effort to review each and every operator, if its tests are complete.

**Comment by kwonoj** [comment]
@staltz , I think this also can closed by https://github.com/ReactiveX/RxJS/issues/878 now leaving away from `thisArg`.

**Comment by staltz** [comment]
I'm fine with closing.

**Pull request closed without merging**
