### PR TITLE
test(concatMapTo): add tests for concatMapTo

### PR DESCRIPTION
**Pull request by staltz**
**Depends on PR #604 being merged first,** because it contains a fix to mergeMapTo which affects this operator. These tests will pass once that PR is merged.

### CODE REVIEW

**Comment by blesh** [comment]
Merged with c3e94a8 ... thanks @staltz

**Comment by blesh** [comment]
1197 tests now...

**Comment by staltz** [comment]
> 1197 tests now...

You asked for tests tests tests tests :D

**Comment by blesh** [comment]
1237 now.

**Pull request closed without merging**
