### PR TITLE
Replace @types package into typings

### LINKED ISSUE #2112: Cannot find type definition file for 'chai'
New in rc.2:

C:\projects\dayapp\node_modules\rxjs\observable\PairsObservable.d.ts
Error:(1, 1) TS2688: Cannot find type definition file for 'chai'.
C:\projects\dayapp\node_modules\rxjs\observable\dom\AjaxObservable.d.ts
Error:(1, 1) TS2688: Cannot find type definition file for 'chai'.

workaround
``` 
npm install --save-dev @types/chai
```

### PR DESCRIPTION
**Pull request by kwonoj**
**Description:**

This PR includes 2 changes regarding build / package manage

- Removes yarn lockfile which doesn't serve in a sense as initially expected. will be revisited later as needed
- Take out @types type definition package and falls back to `typings` module to avoid current compiler side issue until 2.1 public release solves this issue.

/cc @jayphelps @blesh 

**Related issue (if exists):**

closes #2112

### CODE REVIEW

**Comment by kwonoj** [comment]
related to #2108 as well.

**Comment by jayphelps** [comment]
LGTM, @david-driscoll is this typings stuff a satisfactory choice to resolve #2112 until tsc gets their release cut?

**Comment by kwonoj** [comment]
@jayphelps I'm not David, but I believe so. with this change, transpiled type definition no longer includes triple-slash references.

**Comment by jayphelps** [comment]
@kwonoj totally. @david-driscoll wasn't at the meeting so just wanted to get his blessing as well.

**Comment by kwonoj** [comment]
@jayphelps yes, I aware of those but just spoke it :) I'll check this in myself after got approval from @david-driscoll .

**Comment by jayphelps** [comment]
No word from @david-driscoll, but going to merge anyway cause I think we have an acceptable level of confidence.

**Pull request merged**
