### PR TITLE
docs(pairs): document the operator

### PR DESCRIPTION
**Pull request by mpodlasin**
When I am not trying to rewrite fundamentals of rxjs, I still write docs. ;)

* Describe what pairs accepts and returns. 
* Note what kind of object properties will be emitted.
* Add note about optional scheduler parameter.
* Modify `asDiagram` test for better marble in docs.

### CODE REVIEW

**Comment by Podlas29** [comment]
Hm... Any idea why diff covers whole files?

**Comment by kwonoj** [comment]
Assume it's newline or crlf difference.

**Comment by staltz** [comment]
After fixing that newline issue, I'm 👍 for merging the JSDoc.

**Comment by Podlas29** [comment]
@staltz @kwonoj fixed newline issue.

**Comment by JWO719** [comment]
@mpodlasin could you fix the merge conflicts?

**Pull request merged**
