### PR TITLE
chore(test): use test marbles for windowCount operator spec

### PR DESCRIPTION
**Pull request by kwonoj**
Trying to cover https://github.com/ReactiveX/RxJS/issues/309, also trying to cover https://github.com/ReactiveX/RxJS/issues/378 as well by migration of existing test cases. 

Will try to create PR to contain both (replacing current, migrate from RxJS) starting from this changes.

### CODE REVIEW

**Comment by kwonoj** [comment]
Actually one [test case](https://github.com/Reactive-Extensions/RxJS/blob/master/tests/observable/windowwithcount.js#L73) from current RxJS is not covered in this PR, where source is being disposed. Any suggestions for representing those case?

**Comment by blesh** [comment]
@kwonoj that's a good one. I was talking with @staltz recently about ways to improve the marble tests so they cover things like inner unsubscriptions and outer unsubscribes.

I think this PR is good for now, but we definitely need to come up with some solutions for the unsubscription tracking.

**Comment by blesh** [comment]
... and there are a lot of test cases we haven't covered for this operator anyway. We'll get there.

**Comment by blesh** [comment]
Merged with 84e3684

Thanks as always, @kwonoj!

**Pull request closed without merging**
