### PR TITLE
chore(package.json): bump up dependencies version

### PR DESCRIPTION
**Pull request by kwonoj**
**Description:**
This PR updates some of outdated dependencies to latest as well as type definitions.

**Related issue (if exists):**

### CODE REVIEW

**Comment by jayphelps** [comment]
needs rebase, unclear to me why coverage would be reduced--it shouldn't crawl into dependencies  and count them against us should it?

**Comment by kwonoj** [comment]
> unclear to me why coverage would be reduced--it shouldn't crawl into dependencies and count them against us should it?

: me too. Only culprit seems `nyc` which does generating coverage report, may changed mechanism to collect coverage internally. No concrete explanation though.

**Comment by jayphelps** [comment]
@kwonoj maybe try pushing to this PR without updating `nyc`. Would let us know.

**Comment by kwonoj** [comment]
@jayphelps let me do that quickly.

**Comment by kwonoj** [comment]
https://github.com/ReactiveX/rxjs/pull/1963

**Comment by kwonoj** [comment]
@jayphelps seems `nyc`'s reason, (seems) changed coverage generation bit.

**Comment by jayphelps** [comment]
LGTM

**Pull request merged**
