### PR TITLE
chore: include docs build scripts in pipeline + fix scripts

### PR DESCRIPTION
**Pull request by jakovljevic-mladen**
**Description:**
To avoid issues that we had multiple times so far where the docs build was broken after some PR merges, I'm adding running docs build and generation scripts to the pipelines. This only runs `setup` and `build` scripts from the `docs_app`, it does not deploy app remotely.

**Related issue (if exists):**
None, but one of the latest issue we had was fixed in #6881. We want to avoid having such PRs by including these runs. Also, running current `build` script will fail pipelines until #6912 is merged.

### CODE REVIEW

**Comment by benlesh** [comment]
Let me know if you need anything for this.

**Comment by jakovljevic-mladen** [comment]
Changes from the [commit 1685d86](https://github.com/ReactiveX/rxjs/pull/6913/commits/1685d86604c790329048694be5ba75eec1f4e92d) were suggested by [this comment](https://github.com/angular/angular-cli/issues/22606#issuecomment-1025206301).

**Comment by jakovljevic-mladen** [comment]
> Let me know if you need anything for this.

Thanks @benlesh, I somehow managed to fix everything. This PR is ready for review. @kwonoj, can you please review this PR as well?

**Review by benlesh — APPROVED** [review]

**Comment by benlesh** [comment]
@jakovljevic-mladen feel free to merge these into 7.x and master as you please.

**Pull request merged**
