### PR TITLE
Add rudimentary doc generation

### PR DESCRIPTION
**Pull request by robwormald**
Adds basic typescript -> doc generation.

### CODE REVIEW

**Comment by robwormald** [comment]
@petebacondarwin it would be super cool if we could move to dgeni-typescript package into dgeni-packages, if possible - i realize the angular team might not like that, but having even basic support would clean up other repos a LOT (and allow easier contributions...)

**Comment by petebacondarwin** [comment]
@robwormald I agree that copying it from the angular repository is a annoying. We don't need to remove it from angular just to put it into dgeni-package. 

If you could put together a PR against dgeni-packages that contains a basic typescript package then I will merge it. As it matures, we can drop the custom package that is in angular.

**Comment by blesh** [comment]
Awesome!

@robwormald can you flatten this PR into fewer commits at all? Are they each significant enough to have their own commit?

Also, can you rename the commits to have the "angular style" commit messages? `chore(docs): add documentation generation` for example.

**Comment by robwormald** [comment]
yeah, oops. i'll close this one without merging and i'll drop in another flattened one.

**Comment by blesh** [comment]
@robwormald no need, just rebase yours and force push to your fork, it'll update this PR.

**Comment by blesh** [comment]
@robwormald  in other words:

```sh
git rebase -i HEAD~9
```

then `fixup` the ones you want to "flatten" and `reword` the ones you'd like to change the text to.

after that you just: `git push origin dgeni-docs -f` and it'll update this PR.

**Comment by robwormald** [comment]
see https://github.com/ReactiveX/RxJS/pull/240

**Pull request closed without merging**
