### PR TITLE
chore(build): update source copy script with sourcemap to relative path

### PR DESCRIPTION
**Pull request by kwonoj**
@trxcllnt for visibility - would you able to give a shot if this fixes source path lookup issue #1423 ? For me it seems work, but not 100% sure and would like to have second opinion for verification.

### CODE REVIEW

**Comment by kwonoj** [comment]
Blocked until it's verified.

**Comment by kwonoj** [comment]
Actually seems I noticed few caveat for this.. closing PR but leave branch to allow anyone tryout. I'll reopen once I get more confidence.

**Comment by trxcllnt** [comment]
@kwonoj doesn't seem to be working, for example in `util/toSubscriber.js.map`, the `"sources":["util/toSubscriber.ts"]` needs to be `"sources":["toSubscriber.ts"]`

**Comment by kwonoj** [comment]
Yes, I noticed that so closed PR immediately :(

**Pull request closed without merging**
