### PR TITLE
refactor(test): let macro test share common test spec initializer

### PR DESCRIPTION
**Pull request by kwonoj**
While most macro test specs can be created by simple copy-paste which wouldn't need much effort, one thing tickled me was if macro test configuration change is needed, each individual case need to be updated. This PR tries to create small initializer to centralize setups allows easier modification in further if required. (Though not sure if it'll be required frequently enough..)

### CODE REVIEW

**Comment by blesh** [comment]
This is a solid idea. Left a little feedback.

**Comment by kwonoj** [comment]
Updated commit per suggestion but seems I did something incorrect while sync up this branch with latest master. If there's recommended / required flow to clean up branch, would be appreciate to let me know and I'll give try to.

**Comment by blesh** [comment]
@kwonoj 

basically I use KDiff and to a `git mergetool` when rebasing.

just:

```sh
git checkout feature-branch
git fetch upstream
git rebase upstream/master
```

Then if there are merge conflicts:

```sh
git mergetool
```

Once that's done:

```sh
git rebase --continue
```

Then push it back up to your fork:

```sh
git push origin feature-branch -f
```

**Comment by blesh** [comment]
It looks like maybe you did an interactive rebase back too many commits... That could be another issue. You really only want to do `git rebase -i HEAD~N` where N is the number of *your* commits in the PR. If you exceed that, it will give the other commits different SHAs and include them in your PR.

**Comment by kwonoj** [comment]
Seems I did somewhat bad while rebasing. Is it acceptable if I close this and create new PR with clean state of branch? Sorry for making inconveniences.

**Comment by kwonoj** [comment]
Apologize for inconveniences again. Hard rewinded commits and updated branch status though it's not generally recommended, think commit history is clean now. Please let me know if status is incorrect.

**Comment by blesh** [comment]
So close... it looks like you still have 2 commits in there that could be flattened into one.

**Comment by kwonoj** [comment]
Yes, missed that again :( Appreciate for pointing out. Commits are flattened and updated.

**Comment by blesh** [comment]
@kwonoj just walking out the door. I'll try to merge this over the weekend, otherwise it might be Monday.

Thanks again for all of your hard work!

**Comment by kwonoj** [comment]
Sure, take your time and enjoy weekend. Thank you for all help!

**Comment by blesh** [comment]
Merged with 0949fbe

**Pull request closed without merging**
