### PR TITLE
style(typings): Use typeof to capture typings for all static Observab…

### PR DESCRIPTION
**Pull request by david-driscoll**
…le methods

### CODE REVIEW

**Comment by david-driscoll** [comment]
This pulls out the static methods as per the discussion in #870

**Comment by kwonoj** [comment]
As already discussed in original PR, I like this changes and this looks good to me. Thanks for taking time with effort @david-driscoll :)

I'll check in this once @blesh agrees.

**Comment by david-driscoll** [comment]
I've also gone and rebased the other branches to be based on this one, so the changes should disappear from those PRs once this is merged.

**Comment by luisgabriel** [comment]
Super cool! :+1:

**Comment by kwonoj** [comment]
It's off-topic question, is this applicable to non-static instance also?

**Comment by david-driscoll** [comment]
Unfortunately no, because there is no way to consider the type of `this` currently with TypeScript.

Consider:

    export function combineLatest<T2>(second: Observable<T2>): Observable<[T, T2]>;

With this function we have no idea what `T` is, so to define it properly we have to replace it with `any` to compile.

    export function combineLatest<T2>(second: Observable<T2>): Observable<[any, T2]>;

And then we loose our type information.  #870 works around this, copying the definitions from the operator, defined as a function, and strips out any references to `T` from the function declaration.

The `typinggen.js` basically converts:

    export function combineLatest<T, T2>(second: Observable<T2>): Observable<[T, T2]>;

to:

    interface Observable<T> {
        combineLatest<T2>(second: Observable<T2>): Observable<[T, T2]>;
    }

So then we can then use `typeof operator.xyz`, as seen in #871.

**Comment by kwonoj** [comment]
Make quite sense, thanks. Think this topic need to be continued under original PR.

**Comment by kwonoj** [comment]
@david-driscoll Would you able to align commit message start with lowercase as same as other commit history?

**Comment by kwonoj** [comment]
Otherwise, change looks cool to me. I'll let this opened for a while to have any other suggestions / opinions around after commit message's aligned. Expecting to take some time due to holiday.

**Comment by blesh** [comment]
Merged with d4dd7f1. Thanks @david-driscoll!

**Pull request closed without merging**
