### PR TITLE
chore(perf): rename switchFirst to exhaust on micro perf

### PR DESCRIPTION
**Pull request by luisgabriel**

### CODE REVIEW

**Comment by kwonoj** [comment]
Oh, nice catch.

**Comment by kwonoj** [comment]
This makes me remind that we also have renamed scheduler..

**Comment by luisgabriel** [comment]
@kwonoj Yeah, you're right. I'll create an issue for this and start working on it.

**Comment by kwonoj** [comment]
Meanwhile, would you able to update commit message to be aligned with current history? I could see commits like https://github.com/ReactiveX/RxJS/commit/1127f13c4e40201d24ca7b501987d33601c9b30f#diff-4d51848d1226d013c854a78d7868ad24 or https://github.com/ReactiveX/RxJS/commit/8e6d560c862da0d034a0b7b9dda6d6e002c18b08#diff-4d51848d1226d013c854a78d7868ad24 mention it's micro perf changes. (I know I also made inconsistency of strict foramt.. :( )

**Comment by luisgabriel** [comment]
@kwonoj done. ;)

**Comment by kwonoj** [comment]
Awesome, merged with 7dc98c3. Thanks @luisgabriel !

**Pull request merged**
