### PR TITLE
chore(generate-operator): Fixed operator generator to not fail on the…

### PR DESCRIPTION
**Pull request by david-driscoll**
… new dom folder

### CODE REVIEW

**Comment by kwonoj** [comment]
Ah cool, thanks for catching this :+1: Came to think might need to have kind of hook to validate this on travis later..

**Comment by kwonoj** [comment]
BTW, can we align commit message with history? (I know it's not fully consistent, better to be though)

**Comment by david-driscoll** [comment]
All I did was run the tool after fixing it, I can add a note about running it.  The extra files were just ones that hadn't been picked up since the last time it ran afaik.

**Comment by kwonoj** [comment]
> I can add a note about running it. 

: I think it's ok for now. I was thinking further way to ensure this.

**Comment by luisgabriel** [comment]
I think `IteratorObservable.ts`, `ScalarObservable.ts` and `SubscribeOnObservable.ts` should not be added. Can you remove them from this PR?

We have two other tasks related to the generator:
1. Update the script to ignore the observable subclasses that are not exported via static method;
2. Update the script to generate the new operators inside the `dom` directory.

**Comment by david-driscoll** [comment]
@luisgabriel done! :)

**Comment by luisgabriel** [comment]
Nice. ;)

LGTM.

**Comment by kwonoj** [comment]
Thanks for finding out @luisgabriel , assume #1182 and #1183 's to address issue you've listed, is my understanding correct?

**Comment by luisgabriel** [comment]
@kwonoj Yep. Forgot to mention here that I've created these issues. ;)

**Comment by kwonoj** [comment]
Cool. Then I'll check in this PR, let's track remaining changes via issues.

**Comment by kwonoj** [comment]
Merged with 52eea95, thanks @david-driscoll , also @luisgabriel effort to look into this :)

**Pull request closed without merging**
