### PR TITLE
docs: update jsdoc examples (operators e through z)

### PR DESCRIPTION
**Pull request by moniuch**
**Description:** Continuation of #3768 - jsdoc examples: new pipe syntax (remaining operators)
**Related issue (if exists):** #3768

Noticed and not sure about:
- observeOn - `observeOn(Rx.Scheduler.animationFrame),` - is `animationFrame` a creation method, just like `fromEvent`? never used it before.
- some operators are still missing their examples (eg. `endsWith`, `repeat`, `race`)
- do/tap operator - is the do.png link still valid?
- share.ts: `.multicast(() => new Subject()).refCount()` - should this be changed to:
  `.pipe(multicast(() => new Subject()), refCount())` ?
- withLatestFrom - uses chaining + result selector in the description. The description might require a complete makeover though: * `a.withLatestFrom(b, c, (a1, b1, c1) => a1 + b1 + c1)`).

Code style:
- callbacks - single untyped parameters might do without parens around it - example would gain on readability where there is a lot of parens floating around (eg. `groupBy`)
- some examples (eg. `groupBy`) use Finnish notation for streams. Even though it is my personal preference as well in apps, I think it is not necessary in short examples. Unless there is a deeper reason behind that I am unaware of.

### CODE REVIEW

**Comment by moniuch** [comment]
>> is the do.png link still valid?
> Yep. It seems to be.
Well, it is not broken, but the png describes the old `do`. Saw a PR on generating the docs - will ask the author to perhaps touch that problem as well.

> Sure, seems reasonable to me. If you're changing the dot-chaining examples to use pipe and see dot chaining elsewhere in the docs, change them to use pipe.

OK, I changes those to pipeable syntax. Wasn't sure what is the current status of result selectors right now, but as long as they appear as @params they should be documented correctly.

**Comment by benlesh** [comment]
@moniuch so sorry, there was a conflict with a recent change by @JWO719 I just merged... can you rebase?

**Comment by moniuch** [comment]
@benlesh checks in progress, I hope I didn't screw anything up during rebase ;-)

**Comment by benlesh** [comment]
Thanks, @moniuch  :rocket:

**Pull request merged**
