### PR TITLE
feat(mergeScan): support concurrency parameter for mergeScan

### LINKED ISSUE #868: Expose concurrency parameter of mergeScan
While `MergeScanOperator` has implementation to accept concurrency parameter

```js
constructor(private project: (acc: R, x: T) => Observable<R>,
              private seed: R,
              private concurrent: number = Number.POSITIVE_INFINITY)
```

type definition of `mergeScan` does not allow to use it.

`mergeScan<T, R>(project: (acc: R, x: T) => Observable<R>, seed: R)`.

Would it be better to expose concurrency parameter?

### PR DESCRIPTION
**Pull request by kwonoj**
- expose concurrency parameter to interface of mergeScan
- expand test coverage to test concurrency works

closes #868

### CODE REVIEW

**Comment by kwonoj** [comment]
Updated PR to add couple of more test to cover `mergeScan` 100%.

**Comment by staltz** [comment]
Looks great.

**Comment by blesh** [comment]
LGTM

**Comment by kwonoj** [comment]
Thanks, I'll check in myself.

**Comment by blesh** [comment]
Okay

**Comment by kwonoj** [comment]
Merged with fe0eb37, appreciate for review @staltz @blesh :)

**Comment by blesh** [comment]
:+1:

**Pull request closed without merging**
