### PR TITLE
chore(test): update global hint

### PR DESCRIPTION
**Pull request by kwonoj**
Cosmetic update for test cases for editors supports jshint, hinting like below now resolved.

image

### CODE REVIEW

**Comment by staltz** [comment]
:+1: I don't know why my editor didn't show those warnings.

**Comment by kwonoj** [comment]
Think this is editor-specific, but thought still good to have. :)

**Comment by blesh** [comment]
This one actually needs to be rebased before I can merge it.

**Comment by kwonoj** [comment]
I will update PR with rebase.

**Comment by kwonoj** [comment]
PR is now rebased with TOT.

**Comment by blesh** [comment]
merged with 40e9757... thanks @kwonoj

**Pull request closed without merging**
