### PR TITLE
chore(CHANGELOG): add breaking changes on beta 4 release

### PR DESCRIPTION
**Pull request by luisgabriel**
It was probably skipped by the script because the commit was a `refactor` instead of `feat` or `fix`.

### CODE REVIEW

**Comment by kwonoj** [comment]
Would it be possible to add one more https://github.com/ReactiveX/rxjs/pull/1557#issuecomment-203556339 ? It's my fault :cry: /cc @blesh also.

**Comment by luisgabriel** [comment]
@kwonoj Sure. I'll update the PR shortly.

**Comment by luisgabriel** [comment]
@kwonoj Actually, #1557 will be in the next release. So we'll have to add it when beta 5 is out.

**Comment by kwonoj** [comment]
Thanks for clarification. I'll leave this PR to ensure aligned with release schedule and do not mess again.

**Comment by luisgabriel** [comment]
I think this PR should be merged as quickly as possible since beta 4 is already released. Users may not be aware of the fact the `fromArray` was removed.

**Comment by kwonoj** [comment]
I think it'll be quick (and @blesh 's probably already watching this.. :eyes: ) I'll ensure this does not pass this weekend.

**Comment by blesh** [comment]
This PR looks fine. We'll just have to remember #1557 for Monday.

**Comment by blesh** [comment]
Merged with 89c4a9b. Thanks @luisgabriel

**Pull request closed without merging**
