### PR TITLE
proposal: Change `Operator` from class to interface.

### PR DESCRIPTION
**Pull request by saneyuki**
The motivation of this pull request is here:

A deriving class is unclear to understand "what we should need to implement this derived classs?". Thus, I think we should define interface and implement it for each implementations in these case:

- There is no default behavior, or a few default behavior.
- No need to create a base class instance.

`Operator` base class define only `call()` method, I think it will not be high cost for us to implement `call` method for each `Operator` implementations.

How do you think about this?

### CODE REVIEW

**Comment by blesh** [comment]
@saneyuki I don't at all disagree with this PR. If we use an interface, TypeScript will then complain if we don't implement the `call` method. And I don't think we're using the plain `Operator` type anywhere. SO this makes total sense.

I'll leave this PR sit for a while for others to chime in, but for now it looks fine to me.

**Comment by blesh** [comment]
attn @trxcllnt

**Comment by trxcllnt** [comment]
@saneyuki @blesh the only reason this is a base class is because TypeScript creates an empty file for interfaces. Do we expect anybody to ever import the `defaultCallFn` from Operator?

**Comment by blesh** [comment]
> the only reason this is a base class is because TypeScript creates an empty file for interfaces. 

Doesn't seem like a big deal. Don't think of it as an "empty file"... think of it as "importing all of JavaScript in 0 bytes".

> Do we expect anybody to ever import the defaultCallFn from Operator?

I doubt it.


Otherwise LGTM. @trxcllnt ?

**Comment by trxcllnt** [comment]
@blesh lgtm

**Comment by blesh** [comment]
Thank you @saneyuki!

Merged with d565115d5c64c740dd5ce93060c816d0ad1daee1

**Comment by saneyuki** [comment]
@blesh @trxcllnt thank you for your reviewing!

**Pull request closed without merging**
