### PR TITLE
perf(exhaustMap): remove tryCatch/errorObject (~10% improvement)

### PR DESCRIPTION
**Pull request by luisgabriel**
Before:
```
                       |     RxJS 4.0.7 | RxJS 5.0.0-beta.1 | factor | % improved
----------------------------------------------------------------------------------
exhaustMap - immediate | 1,449 (±0.95%) |   17,023 (±0.88%) | 11.75x |   1,075.1%
            exhaustMap | 4,732 (±0.34%) |   80,795 (±0.38%) | 17.07x |   1,607.4%
```

After:
```
                       |     RxJS 4.0.7 | RxJS 5.0.0-beta.1 | factor | % improved
----------------------------------------------------------------------------------
exhaustMap - immediate | 1,452 (±1.14%) |   18,523 (±0.68%) | 12.76x |   1,175.5%
            exhaustMap | 4,941 (±0.29%) |   87,146 (±0.39%) | 17.64x |   1,663.8%
```

### CODE REVIEW

**Comment by kwonoj** [comment]
Change looks good to me.

**Comment by david-driscoll** [comment]
I have a (potentially dumb question) will these change affect the flame graph in any way? Or is the errorObject just a hold over from RxJS4?

**Comment by kwonoj** [comment]
I assume there won't be much changes, custom trycatcher is simply wraps trycatch by 

```js
function tryCatcher(): any {
  try {
    return tryCatchTarget.apply(this, arguments);
  } catch (e) {
    errorObject.e = e;
    return errorObject;
  }
}
```

call stack may look slightly difference by catching internally.

**Comment by kwonoj** [comment]
just curious @david-driscoll , any particular concern you have in mind?

**Comment by david-driscoll** [comment]
nope, just curious if it was related to handling the flamegraphs at all.  I know in the past the common error object was used for creating custom callback chains (I think, but it's been a while).

**Comment by kwonoj** [comment]
This PR https://github.com/ReactiveX/RxJS/pull/1251 does have background explanations of reason to adapt these changes. Mainly about perf reasons.

**Comment by kwonoj** [comment]
Merged with a55f459, thanks @luisgabriel .

**Pull request merged**
