### PR TITLE
refactor(Observable): remove unnecessary if

### PR DESCRIPTION
**Pull request by hgaleh**
there is an unnecessary if in the pipe, remove it

#6504

### CODE REVIEW

**Comment by hgaleh** [comment]
I have checked and compiled my code several times. How can I reproduce the error?

**Comment by jakovljevic-mladen** [comment]
The fix for the failing pipeline is merged yesterday to master. You have to [rebase the latest changes from master](https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request) to your local branch and force push to your remote branch.

**Comment by hgaleh** [comment]
It seems to be a long process for my pull request to be approved. What is going on out there?

**Comment by benlesh** [comment]
> It seems to be a long process for my pull request to be approved. What is going wrong out there?

@hgaleh This is an all-volunteer group of maintainers. Sorry we're not as responsive as you like, but comments like this come off as rude.

**Review by benlesh — APPROVED** [review]

**Pull request merged**
