### PR TITLE
Updated package.json types path

### PR DESCRIPTION
**Pull request by eliasm307**
**Description:**

Updates typings path in package.json to point to the actual location of type declarations.

Minor update and tests seem to pass, some are just 11 are shown as pending but I am not sure if this is an issue with the tests, there are no explicitly failing tests however: 
image

**Related issue (if exists):**

Addresses #6455

### CODE REVIEW

**Comment by kwonoj** [comment]
Dupe of https://github.com/ReactiveX/rxjs/pull/6293 , please confirm if you're on correct typescript version.

**Comment by eliasm307** [comment]
@kwonoj see below the version I am on, what is the correct version?
image

**Comment by kwonoj** [comment]
@eliasm307 please create reproducible repo and comment under issue you have filed: also we do not support nightly / dev version of typescript - it may work or not but we cannot ensure it always work.

**Comment by eliasm307** [comment]
@kwonoj the issue turned out to be a typescript version issue as you suspected. My global ts version is 4.3.0 but the project I was working on has this defined locally as 4.1.5, the error is gone after updgrading. Thanks for your help!

**Pull request closed without merging**
