### PR TITLE
chore(code-coverage): Add istanbul code coverage and travis + coveralls configuration.

### PR DESCRIPTION
**Pull request by trxcllnt**

### CODE REVIEW

**Comment by blesh** [comment]
YES.

**Comment by trxcllnt** [comment]
@blesh can I still expense the coveralls fee? ;)

**Comment by blesh** [comment]
@trxcllnt ... isn't coveralls free for open source projects?

**Comment by blesh** [comment]
After discussing with @trxcllnt on Slack, there is no reason to commit the .html files. So I've added a .gitignore for the `coverage/` directory, and removed those files. Everything is merged as of commit 26a0696.  Good stuff!

**Pull request closed without merging**
