### PR TITLE
chore(bazel): allow downstream projects to omit //:node_modules

### PR DESCRIPTION
**Pull request by alexeagle**

### CODE REVIEW

**Comment by alexeagle** [comment]
Hey @kwonoj what's the process to get PRs merged? Do I just ping you like this?

**Comment by kwonoj** [comment]
usually, we demand 2 reviewers approval. Seems Ben approved already, so I'll 🚢

**Comment by alexeagle** [comment]
Thanks, should I send a separate PR to get this on master for v6?

**Comment by kwonoj** [comment]
Oh, it was targeted for stable. If you are able to, appreciate for it.

**Comment by alexeagle** [comment]
https://github.com/ReactiveX/rxjs/pull/3358

**Pull request merged**
