### PR TITLE
feat(takeWhile): remove thisArg

### PR DESCRIPTION
**Pull request by kwonoj**
relates to #878 

This PR tries to take out `thisArg` from `takeWhile` operator.

### CODE REVIEW

**Comment by staltz** [comment]
Looks good

**Comment by kwonoj** [comment]
I'll leave this PR around half day to see if there's suggestion before check in.

**Comment by kwonoj** [comment]
PR is updated to remove `bindCallback` also. I'll continue effort to get rid of `thisArg` from operators as well as `bindCallback` itself as last step.

**Comment by blesh** [comment]
Merged with b5219a4 ... thanks @kwonoj

**Pull request closed without merging**
