### PR TITLE
test(skip): add marble tests for skip operator

### PR DESCRIPTION
**Pull request by kwonoj**
Migrating existing RxJS4 test cases.

### CODE REVIEW

**Comment by blesh** [comment]
Do you think can can add tests for `empty`, `never` and `throw`? (Throw being different than error tests, because an error test can emit a value first)

**Comment by blesh** [comment]
I'm actually shocked the RxJS 4 tests didn't have that.

**Comment by kwonoj** [comment]
Yes that's true.. didn't noticed it. Will update PR as suggested.

**Comment by kwonoj** [comment]
Test cases are added for explicit `throw`, `empty`, and some variant of `never` cases.

**Comment by blesh** [comment]
Merged as of 954a873

Thanks again, @kwonoj!!!

**Pull request closed without merging**
