### PR TITLE
chore(typescript): Cleanup usage of typings package.

### PR DESCRIPTION
**Pull request by alexeagle**
TypeScript now distributes typings via npm.

Note, `@types` is not semver, because patch releases may introduce syntax that requires a TypeScript upgrade. So the `package.json` pins these to versions (just as the `typings.json` did)

### CODE REVIEW

**Comment by kwonoj** [comment]
related to https://github.com/ReactiveX/rxjs/issues/2437.

**Comment by kwonoj** [comment]
danger checker seems off, don't mind it - I'll look into separately.

**Comment by alexeagle** [comment]
From the other issue you linked, it's not clear to me if this PR causes some problem - do we need testing of user-land type-checking?

**Comment by kwonoj** [comment]
> it's not clear to me if this PR causes some problem

: that's reason we were hesitating migrate into @types package. Surprisingly we had regressions by shipping pkg using @types pkg from typings pkg previously, and haven't introduced automatic way to verify those in our repo. It's not about testing 3rd party typing's validity, it was using those pkg TS compiler generated unexpected results. I believe that's no longer issue though.

**Comment by alexeagle** [comment]
Sounds like you would benefit from the same typings test setup we use for
angular.

**Comment by benlesh** [comment]
I've merged this into #2614. Closing in favor of that.

**Pull request closed without merging**
