### PR TITLE
chore(perf): improve micro perf ergonomics

### PR DESCRIPTION
**Pull request by blesh**
- automatically pick up new files without maintaining a huge array
- add ability to filter down to specific tests: `node perf/micro testfilter` where "testfilter" is any string
  to be found inside the path of the test

@kwonoj ... this is for you.

### CODE REVIEW

**Comment by kwonoj** [comment]
Cool! :+1:

**Comment by blesh** [comment]
I've changed it so you must use a name that is the name of the test files to run. This is because `map` matched too many files. Now it must be exact. `zip`, or `take` or `map` or `flatMap` for example.

**Comment by blesh** [comment]
Merged immediately so I can continue work.

**Comment by blesh** [comment]
Incidentally, just running `node perf/micro` will still run all of the tests.

**Pull request merged**
