### PR TITLE
Refactor scan

### PR DESCRIPTION
**Pull request by kwonoj**
This PR includes changes for

- expand test coverage of `scan` to complete code coverage
- update parameter name of `scan`, from `project`, `acc` to `accumulator` and `seed` for additional clarity.

### CODE REVIEW

**Comment by staltz** [comment]
:+1:

**Comment by luisgabriel** [comment]
:+1:

**Comment by blesh** [comment]
LGTM

**Comment by kwonoj** [comment]
Merged with 54af528.

**Pull request closed without merging**
