### PR TITLE
test(IteratorObservable): add spec file for tests on IteratorObservable

### PR DESCRIPTION
**Pull request by staltz**
Coverage up 0.6%

### CODE REVIEW

**Comment by kwonoj** [comment]
> Coverage up 0.6%

: yay :+1: Changes look good for me.

With this change, there are some lines left as uncovered, can I ask if there are further goals or some of constrains does not allow to cover those lines?

**Comment by staltz** [comment]
It's this issue: https://github.com/ReactiveX/RxJS/issues/733

**Comment by kwonoj** [comment]
Reading lines of missing coverage makes me assumed it might be related - thanks for clarification.

**Comment by blesh** [comment]
Meh, we can leave them for now.

**Comment by blesh** [comment]
Merged with 44e8e79

**Pull request closed without merging**
