### PR TITLE
docs(README.md): add spaces to import

### PR DESCRIPTION
**Pull request by ladyleet**
**Description:**
adding some formatting so we can demo pull requests for beginners #yolobrolo 

**Related issue (if exists):**
to make @jayphelps happy

### CODE REVIEW

**Comment by jayphelps** [comment]
@ladyleet the section above it also has one too `import {Observable} from 'rxjs/Observable';`. Even if I personally prefer spaces between them, it really isn't a big deal so I'm not going to be the one to merge to prevent any feelings of imposing my preferences.

For the record, I did _not_ tell her to do this or mention this style in any way! 🐧 [Angular 2's docs use the spaced style](https://angular.io/docs/) so perhaps aligning with them is ideal considering they're by far the biggest users.

**Comment by kwonoj** [comment]
I also prefer spaced style (as perfectly personal preferences).

**Comment by blesh** [comment]
LOL @jayphelps  ... this was done by myself and @ladyleet  just as a demonstation of how to contribute to a repository. :) There isn't a lot of low-hanging fruit here.

**Comment by blesh** [comment]
However, I do think I should create an issue to update to the spaced style everywhere, because the current style bothers me... furthermore, I should assign it to @ladyleet!  `*whip crack!*`

**Comment by blesh** [comment]
LGTM

**Comment by jayphelps** [comment]
Well in that case, DEATH TO NO SPACED BRACES. 🔥 🔥 🔥

**Comment by david-driscoll** [comment]
I've also hoped on board the spaces train :bullettrain_side:

**Comment by jayphelps** [comment]
everybodys doing it

**Pull request merged**
