### PR TITLE
fix(operators): force patch modules to not emit empty declarations

### LINKED ISSUE #1010: Type Definitions are empty for "add" modules
The generated `d.ts` files that correspond to the "patch" operator and observable files are empty, so they are picked up by typescript as invalid modules and the compiler errors:
```
error TS2656: 
Exported external package typings file 'node_modules/rxjs/add/observable/fromEvent.d.ts' is not a module. Please contact the package author to update the package definition.
```

This means TS users are unable to do the desired `'import rxjs/add/operator/map' ` use case. 

Workaround for angular2 users discovering this issue is to simply `'import rxjs/Rx'` which will add all the operators and observables in the meantime without error. 

This appears to go all the way back to alpha.11, which is when the /add syntax was introduced.

### PR DESCRIPTION
**Pull request by robwormald**
closes #1010

### CODE REVIEW

**Comment by kwonoj** [comment]
Just curiosity, what happens if delete all `.../add/**/*.d.ts' ?

**Comment by robwormald** [comment]
That works, but only until we bump up to TS 1.8 and patch the operator definition in the 'add' module.

**Comment by kwonoj** [comment]
Get it, thanks. (Just clarify, it wasn't suggestion to delete it, purely based on curiosity)

**Comment by robwormald** [comment]
Yeah, I hadn't even considered that option, haha!

**Comment by kwonoj** [comment]
I think changes good for immediate solution. (sorry, may require rebase due to my latest check in).

**Comment by robwormald** [comment]
whoops, screwed up that merge. fixing...
oops

**Comment by blesh** [comment]
`file mode changed`

**Comment by robwormald** [comment]
okay, good to go.

**Comment by kwonoj** [comment]
Cool, I'll check in in today once travis says good to go.

**Comment by kwonoj** [comment]
Merged with 676f82d, appreciate @robwormald !

**Pull request merged**
