### PR TITLE
Write JSDoc for defaultIfEmpty

### PR DESCRIPTION
**Pull request by staltz**

### CODE REVIEW

**Comment by blesh** [comment]
This looks great. Thanks @staltz

**Comment by staltz** [comment]
Updated to add docs for defaultIfEmpty too.

**Comment by staltz** [comment]
Funny, the operators count, first, find, findIndex were already merged but this PR stayed open. Anyway, this PR now has just the operator defaultIfEmpty

**Comment by staltz** [comment]
Well, let's not mix things up. I made PR #1586 just for defaultIfEmpty()

**Pull request closed without merging**
