### PR TITLE
docs(typings): added installation information for TypeScript users

### PR DESCRIPTION
**Pull request by david-driscoll**
**Description:**
Adds additional details about how to handle errors that might come up related to targeting `es5` with typescript.

### CODE REVIEW

**Comment by blesh** [comment]
cc @robwormald @kwonoj for review.

**Comment by kwonoj** [comment]
I'm ok for changes. Would like to suggest to recommend use typings, and gradually remove definition in repo's spec and RxJS itself uses typings registry too in further.

**Comment by robwormald** [comment]
Does es6-shim /collections typings handle this?

**Comment by david-driscoll** [comment]
Sadly no, they don't provide the interfaces, presumably because they don't actually create a `Symbol`.

**Comment by kwonoj** [comment]
Merged with fc64420, thanks @david-driscoll 

I've checked this in since it's documentation. @david-driscoll ,  for further ergonomic issues such as @robwormald 's question, let's discuss via separate issue.

**Comment by ericmartinezr** [comment]
@david-driscoll @kwonoj sorry for bumping a closed issue

I tried the suggested solution using `typings install rxjs-symbol-typings` and throws
```
Unable to find "rxjs-symbol-typings" for "npm" in the registry. Did you want to install ambient typings with the ambient flag? If you can contribute these typings, please help us: https://github.com/typings/registry
```
Using --ambient
```
typings ERR! message Unable to find "rxjs-symbol-typings" for "dt" in the registry. Did you want to install ambient typings with the ambient flag? If you can contribute these typings, please help us: https://github.com/typings/registry
typings ERR! caused by https://api.typings.org/entries/dt/rxjs-symbol-typings/versions/latest responded with 404, expected it to equal 200
```
Any clue on this?

**Comment by kwonoj** [comment]
@ericmartinezr Sorry for inconvenience, that's because type definition has been updated to not to use it at https://github.com/ReactiveX/rxjs/pull/1582 . For now, please use b.4 - next version will not need this anymore.

**Comment by ericmartinezr** [comment]
@kwonoj no problem at all, thanks for answering :+1:

**Pull request closed without merging**
