### PR TITLE
chore(package.json): do not build SystemJS bundle

### PR DESCRIPTION
**Pull request by kwonoj**
**Description:**
This PR removes SystemJS from package generation, ready to be served for #1776 if it's concluded to go. If not, PR can be simply closed.

**Related issue (if exists):**

### CODE REVIEW

**Comment by kwonoj** [comment]
marking as blocked for now.

**Comment by blesh** [comment]
@kwonoj what is this blocked by?

**Comment by kwonoj** [comment]
@blesh just waiting #1776 get final  conclusion. Changewise it's ready.

**Comment by jayphelps** [comment]
LGTM, no arguments heard in #1776. Needs rebase.

**Pull request merged**
