### PR TITLE
docs (Docker support for docs_app)

### PR DESCRIPTION
**Pull request by Hermel**
**Description:**
added support for running the docs_app as a docker container
and tested it successfully on docker over ubuntu.

added 2 new files:
* added .dockerignore - for ignoring node_modules, logs, etc.
* Dockerfile - installing the docs app and exposing port for use.
updated 2 existing files:
* package.json - start script is running the stable version + host flag
* readme - updated with the docker commands

**Related issue (if exists):** -

### CODE REVIEW

**Comment by JWO719** [comment]
Hi, thanks for the initiative and contributing. Just from curiosity what's the benefit for the project with adding support for docker, maybe it's due to my lack of knowledge, but I don't see it. I would be happy to merge it as long as it has some benefit for developers

**Comment by Hermel** [comment]
Hey,
Basically it could help for those who develop on offline stations (without active internet connection) to serve the documentation locally on docker container. For me it was very useful :)

**Comment by JWO719** [comment]
You need to rebase this branch to trigger cirecleci properly. If you need help with, just let me know. Despite that I happily merge this

**Comment by Hermel** [comment]
> You need to rebase this branch to trigger cirecleci properly. If you need help with, just let me know. Despite that I happily merge this

@JWO719 Hey, I'm not quite sure what should I do :sweat_smile:
Could you please explain more what do you mean?

**Comment by Hermel** [comment]
@JWO719 could you approve and merge the PR?

**Comment by JWO719** [comment]
Thanks a lot for the contribution. Sorry for coming back so late .

**Pull request merged**
