### PR TITLE
style(tslint): expand lint coverage to all source codes

### PR DESCRIPTION
**Pull request by kwonoj**
`tslint` glob only expanded to specific path (`src/**`) instead of fully expanded (`src/*, src/**/**/*`). Updated parameter also aligned files to lint friendly.

### CODE REVIEW

**Comment by blesh** [comment]
Because of #664 ... you're going to need to rebase this commit.

**Comment by kwonoj** [comment]
Yes, I thought so. I'll update PR with rebase.

**Comment by kwonoj** [comment]
PR is rebased and passed travis.

**Comment by blesh** [comment]
haha... this needs rebased again. Sorry, @kwonoj

**Comment by blesh** [comment]
merged with 63c2d2f ... thanks @kwonoj

**Pull request closed without merging**
