### PR TITLE
chore(Subscriber): add comment why Subscriber.destination is 'PartialObserver<any>'

### PR DESCRIPTION
**Pull request by saneyuki**
This is just for readability and explain the design.

### CODE REVIEW

**Comment by saneyuki** [comment]
@blesh @trxcllnt 

Does this patch is reflect your intent correctly?

**Comment by blesh** [comment]
@saneyuki ... sorry it took so long for me to respond on this one. I'm not sure that this PR is necessary or adds a lot of value to the project. It's a "no" for me for now, but I'll ask @kwonoj, @staltz, @trxcllnt or @mattpodwysocki to weigh in. If someone else thinks it's really worth merging, then I'm okay with it. But like I said, for now for me, it's a "no".

**Comment by kwonoj** [comment]
I was actually bit indifferent on this one and would like to hear other opinions as well. For me, I don't see huge values though.

**Comment by trxcllnt** [comment]
I'm usually in favor of more comments, especially when they help explain typing decisions we had to make to support generics.

**Comment by blesh** [comment]
Meh, I'll just merge it, It's not going to hurt anything but the filesize for people who are crazy enough to download the unminified global.

**Pull request merged**
