### PR TITLE
fix(subject): Fixes signature of Subject::lift

### PR DESCRIPTION
**Pull request by hearnden**
**Related issue (if exists):**
https://github.com/ReactiveX/rxjs/issues/2539

### CODE REVIEW

**Comment by benlesh** [comment]
@david-driscoll @kwonoj This *might* be breaking, so let's punt it to the next major. It's not a bug that should effect common uses cases, so we can wait a little bit.

**Comment by staltz** [comment]
LGTM

**Comment by Igorbek** [comment]
With `typescript@next` this signature mismatch is being caught by compiler that prevents using rxjs completely. So I would not say this is a breaking change.

**Comment by benlesh** [comment]
@Igorbek right now 6.0.0-alpha.0 is targeting TS 2.3... I'll be updating that to TS 2.4 RC in short order. That should level this out for you. However, the stable branch will stay at 2.0, as there were breaking changes required to update to 2.1. It's better to not break anyone than make a few people happy.

**Comment by karptonite** [comment]
FYI, TypeScript has released 2.4; this issue is now caught by the compiler, so it won't be possible for anyone using rxjs version 5 to upgrade to the latest TypeScript.

**Comment by david-driscoll** [comment]
Can you check if turning on `skipLibCheck` in your `tsconfig.json` will stop this error from happening?  It should be a stop gap change until we can get 6.0 out.

**Comment by karptonite** [comment]
@david-driscoll Unfortunately, that doesn't help. While that gets rid of the error the compiler finds in Subject directly, it does nothing for all of the errors in my code that use Subject.

**Comment by saneyuki** [comment]
@karptonite `asObservable()` method might help you if your code try to assign `Subject<T>` to the variable/return value which expect `Observable<T>`.

**Comment by karptonite** [comment]
@saneyuki Thanks! I think in this case, I'm better off just staying on ts 2.3.4 until the official fix comes.

**Comment by benjamincombes** [comment]
It would be really great if it could be released as soon as possible, as it affects Angular users too that can't upgrade to TypeScipt 2.4: https://github.com/angular/angular/issues/17800

**Comment by villanuevadani** [comment]
I managed to make it work with RxJS fixed at 5.4.1 and TS at 2.3.4

**Comment by OliverJAsh** [comment]
For all TypeScript users who want to upgrade to 2.4.x but don't want to use an alpha version of TypeScript, and don't want to upgrade to the next major version, is it possible to apply this change to v5 and release a new patch version? Of course this may not be possible if it's considered a breaking change.

**Comment by Igorbek** [comment]
My hack was to automatically patch rxjs typings on `postinstall` script to change `'lift<R>(operator: Operator<T, R>): Observable<T>` to `lift<R>(operator: Operator<T, R>): Observable<R>`.
ps. I still cannot understand why the bugfix considered a breaking change.

**Comment by Meligy** [comment]
I also think this fix should not be considered a breaking change, and would make total sense as a bugfix release version not even minor.

**Comment by JemiloII** [comment]
This should just be a bugfix patch fix for 5.x.x

**Comment by fletchsod-developer** [comment]
fyi the fix already landed on RxJS 5.4.2 (<a href="https://github.com/ReactiveX/rxjs/blob/master/CHANGELOG.md#542-2017-07-05">changelog</a>), you can either close this issue or leave it open.

**Pull request merged**
