### PR TITLE
chore(tests2png): add more test cases for PNG diagrams

### PR DESCRIPTION
**Pull request by staltz**
Specify more test cases with 'asDiagram()' for many operators, to enable their PNG diagrams.

### CODE REVIEW

**Comment by blesh** [comment]
Can you rebase this one, please, @staltz?

**Comment by staltz** [comment]
Rebased.

**Comment by staltz** [comment]
And tests fixed. Should be good now.

**Comment by staltz** [comment]
Rebased this fellow again.

**Comment by blesh** [comment]
Merged with 1e28a1c. Thanks @staltz

**Pull request closed without merging**
