### PR TITLE
chore(marketing): Give Logo a Hair Cut

### PR DESCRIPTION
**Pull request by pertrai1**
**Description:**

The outline of the logo now does not have a pixelated white border
around the edges. Removing this allows it to be used on other color
backgrounds besides white.

### Comparison

Left side is current - Right side is hair cut - (Click on image to see it in full size)

rxjs-side-by-side-example

### CODE REVIEW

**Comment by pertrai1** [comment]
Thanks for catching that @cartant. I was using the border to check for any out of balance pixels that might have been missed. It is now removed.

**Comment by rgbkrk** [comment]
This is great, thank you!

**Comment by JWO719** [comment]
I also like it very much!

**Comment by benlesh** [comment]
cartant, is that .svg in the repo? I feel like it's been floating around for a while. Or different people have an SVG, but we haven't put one officially anywhere. Perhaps we should keep the assets here somewhere (but make sure we aren't publishing them with a package).

**Comment by benlesh** [comment]
Thanks, @pertrai1

**Pull request merged**
