### PR TITLE
docs(manual): write some content (introduction, observable, etc)

### PR DESCRIPTION
**Pull request by staltz**
This PR has mostly text/content being added to the documentation.

To see this page live, open http://rxjs5-esdoc-manual-content-wip.surge.sh/.

screen shot 2016-02-25 at 16 39 51

### CODE REVIEW

**Comment by staltz** [comment]
Depends on https://github.com/esdoc/esdoc/issues/231 getting fixed.

**Comment by blesh** [comment]
LGTM

**Comment by blesh** [comment]
Alternatively, perhaps we can get @Widdershin to give us a workaround for esdoc vomiting on HTML comments? ... I have no idea what that would be... a config maybe? I dunno. I'm just trying to push the effort forward.

**Comment by blesh** [comment]
Marking as blocked because of the esdoc issue.

**Comment by staltz** [comment]
Indeed blocked. And no response from ESDoc side so far, perhaps I can try solving it myself and submitting a PR. The other option being turning off markdown-doctest for now.

**Comment by Widdershin** [comment]
Not sure there's anything I can do on the markdown-doctest side (although suggestions are welcome).

Without fully understanding the problem, I made a little fix.

```diff
    sanitizer: (tag) =>{
+      if (tag.match(/<!--.*-->/)) {
+        return tag;
+      }
+
        const tagName = tag.match(/^<\/?(\w+)/)[1];
        if (!availableTags.includes(tagName)) {
          return escape(tag);
        }

        const sanitizedTag = tag.replace(/([\w\-]+)=(["'].*?["'])/g, (_, attr, val)=>{
          if (!availableAttributes.includes(attr)) return '';
          if (val.indexOf('javascript:') !== -1) return '';
          return `${attr}=${val}`;
        });

        return sanitizedTag;
      },
```

Would really love to avoid turning off markdown-doctest, especially while new docs are being written (would love to encourage people to write examples that actually run :wink:

)

**Comment by staltz** [comment]
> Would really love to avoid turning off markdown-doctest, especially while new docs are being written 

Me too. Was that fix for ESDoc?

**Comment by Widdershin** [comment]
Yep! Publisher/Builder/util.js

**Comment by Widdershin** [comment]
It would be awesome if you could see about getting that fix merged @staltz, I'm pretty overloaded right now so I'm not sure when I would have time

**Comment by staltz** [comment]
Thanks for pointing me in the right direction @Widdershin :)

**Comment by staltz** [comment]
I submitted a PR to ESDoc:
https://github.com/esdoc/esdoc/pull/239

This PR is blocked until that is merged and a new version is released.

**Comment by staltz** [comment]
> This PR is blocked until that is merged and a new version is released.

Uhmm, I take that back. I'm baffled that the tests just passed in Travis :|

**Comment by staltz** [comment]
Hello, this PR should now be unblocked

**Comment by kwonoj** [comment]
Change looks good to me too. Since @blesh already confirmed changes, I'll check this in later today. (give small time buffer just in case any other suggestion comes in)

**Comment by staltz** [comment]
Yeah anyway it's just to kickstart the content, replacing `TODO` with actual content. We may freely modify/improve it afterwards.

**Comment by kwonoj** [comment]
Merged with 935212a, thanks @staltz :)

**Pull request closed without merging**
