### PR TITLE
chore(commitizen): fix adapter path

### LINKED ISSUE #1691: `npm run commit` is not committing
Is it only me?

[Looks like latest version of `commitizen` expects the adapter path w/o `node_modules/` prefix.](https://github.com/commitizen/cz-cli#commitizen-for-project-maintainers)

```json
...
  "config": {
    "commitizen": {
      "path": "cz-conventional-changelog"
    }
  }
```

### PR DESCRIPTION
**Pull request by sarbbottam**
fixed #1691

### CODE REVIEW

**Comment by kwonoj** [comment]
maybe can bump up version to `commitizen` also?

and you may able to use commit message `chore(package.json): ...` for general npm script related.

**Comment by sarbbottam** [comment]
> maybe can bump up version to commitizen also?

Wondering if it should be done automatically via https://greenkeeper.io/?

**Comment by kwonoj** [comment]
> Wondering if it should be done automatically via https://greenkeeper.io/?

: I considered it previously but some of package compatibility makes it should be managed by manually. commitizen is also one example, there's no way to automatically verify regression.

**Comment by sarbbottam** [comment]
updated the commit message and bumped `commitizen` version.

**Comment by kwonoj** [comment]
Merged with 97bcc15, thanks @sarbbottam

**Pull request merged**
