### PR TITLE
chore: add disambiguateByNonOperator disambiguator

### LINKED ISSUE #6539: Create new disambiguator to remove warning when building docs
Since operators are now exported from top level module (as of #6488), when building docs, a multiple warnings are produced. For example:

```
warn:    Error in {@link raceWith} - Ambiguous link: "raceWith".
Matching docs:
  "index/raceWith" (function) : (api/index/function/raceWith / internal/operators/raceWith.ts)
  "operators/raceWith" (function) : (api/operators/raceWith / internal/operators/raceWith.ts) - doc "api/deprecations" (deprecation)
```

The reason is that there are multiple documents that exist in two modules: `index` module and `operators` module. For this reason, `{@link raceWith}` won't work since package that builds links can't decide which one to take. Thus, a new disambiguator should be created to remove operators from `operators` module.

### PR DESCRIPTION
**Pull request by jakovljevic-mladen**
This PR fixes all errors when building docs. It add new disambiguator that removes duplicates when building docs. Since most of the operators are now exported in both root (`'rxjs'`) and `/operators` paths, a lot of duplicates were created. With this disambiguator, precedence is given to those from `'index'` module (`'rxjs'` import site).

Also, existing `disambiguateByDeprecated` disambiguator is changed for this reason: many duplicated documents that were deprecated are filtering all existing documents with this disambiguator  which lead to yet another error saying that no documents are found.

Side note: for couple of months now, running `npm run docs` has always slightly modified `/concatAll.svg` file, which I committed now - this is totally unrelated to the issue solved with this PR. If not needed, please let me know so I can remove it.

**Related issue (if exists):**
Closes #6539

### CODE REVIEW

**Comment by jakovljevic-mladen** [comment]
I'm not sure why this test is failing. It doesn't seem to be related to the changes from this PR. Seems related to #5370 and #4089 (@cartant).

**Comment by cartant** [comment]
> I'm not sure why this test is failing.

Ben encountered the same failing test - in CI - recently and was unable to get it to fail locally. Rerunning the CI tests 'fixed' the problem there and here, too.

**Comment by jakovljevic-mladen** [comment]
@cartant thanks!

**Review by benlesh — APPROVED** [review]

**Comment by benlesh** [comment]
Thank you @jakovljevic-mladen!

**Pull request merged**
