### PR TITLE
test(mergeMap): improve subscription assertions on tests

### PR DESCRIPTION
**Pull request by staltz**

### CODE REVIEW

**Comment by kwonoj** [comment]
Just minor curiosity, was commit message supposed to be includes operator name?
>improve subscription assertions on **mergeMap** tests

**Comment by staltz** [comment]
In this case I think I shortened the commit message by removing mergeMap. I'm unsure if the commit message after `type(scope):` should be a complete message or if it should assume the `scope` is known.

**Comment by kwonoj** [comment]
>  should be a complete message or if it should assume the scope is known

: I think this is fine. Just wanted confirm if this is known and intended :)

**Comment by kwonoj** [comment]
Merged with e11f5d8, thanks @staltz

**Pull request closed without merging**
