### PR TITLE
chore(package.json): update markdown-doctest to 0.3.1

### PR DESCRIPTION
**Pull request by staltz**
Tiny PR, please merge this baby :baby: :baby_bottle:

### CODE REVIEW

**Comment by kwonoj** [comment]
> /home/travis/build/ReactiveX/RxJS/node_modules/markdown-doctest/lib/doctest.js:30
        return handler(...match);
                       ^^^
SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)

seems travis is not happy with baby?

**Comment by staltz** [comment]
Weird. @Widdershin ?

**Comment by Widdershin** [comment]
@staltz v0.3.2 should work, please try again :smile:

**Comment by staltz** [comment]
It works :)

**Comment by kwonoj** [comment]
Merged with bcfee80, thanks @staltz

**Pull request merged**
