### PR TITLE
test(groupBy): fix misbehaving groupBy test

### PR DESCRIPTION
**Pull request by staltz**
Closes issue #1743.

### CODE REVIEW

**Comment by blesh** [comment]
LGTM

**Comment by jayphelps** [comment]
LGTM, needs rebase.

**Comment by staltz** [comment]
Rebased. Pinging @jayphelps

**Comment by jayphelps** [comment]
@staltz broken

**Comment by staltz** [comment]
Unrelated test was failing. I just clicked restart in Travis and ✅.

**Pull request merged**
