### PR TITLE
chore(test): add macro performance tests for zip

### PR DESCRIPTION
**Pull request by kwonoj**
Attempt to create macro test to close https://github.com/ReactiveX/RxJS/issues/259

### CODE REVIEW

**Comment by kwonoj** [comment]
May I possible ask blocked label means? Does PR have issues need to be addressed?

**Comment by blesh** [comment]
No.. your PR is fine. There's an issue with the macro perf tests and the latest version of Chrome.

**Comment by blesh** [comment]
In other words, you're blocked by @jeffbcross! :P haha.

**Comment by blesh** [comment]
.... actually, I guess I can merge this and verify later, since it's not in the critical path and won't cause Travis to fail.

**Comment by kwonoj** [comment]
Thanks for clarification, much appreciated.

**Comment by jeffbcross** [comment]
> In other words, you're blocked by @jeffbcross! :P haha.

Welcome to the Blocked By @jeffbcross Club!

**Comment by kwonoj** [comment]
:smiley:

**Pull request merged**
