### PR TITLE
feat(using): add static Observable.using creation operator.

### PR DESCRIPTION
**Pull request by trxcllnt**
Addresses #1345

### CODE REVIEW

**Comment by kwonoj** [comment]
Change looks good to me.

**Comment by blesh** [comment]
Looks fine. It's missing a few tests and at least one perf test.

**Comment by blesh** [comment]
I think this just needs a rebase and update the tests to TypeScript.

**Comment by trxcllnt** [comment]
@blesh done

**Comment by luisgabriel** [comment]
@trxcllnt I think you have to change the spec file extension to `.ts`, otherwise it will not be executed.

**Comment by trxcllnt** [comment]
@luisgabriel thanks

**Comment by kwonoj** [comment]
Merged with 6c76593, thanks @trxcllnt

**Pull request closed without merging**
