### PR TITLE
chore(test): use test marbles for filter operator spec

### PR DESCRIPTION
**Pull request by jinroh**
Try covering #390. Hope this is sufficient and adhere to contributions guidelines.

Could not find tests from RxJS3/4 for filter.

### CODE REVIEW

**Comment by kwonoj** [comment]
Maybe [this](https://github.com/Reactive-Extensions/RxJS/blob/master/tests/observable/where.js) test cases can be adopted for `filter`?

**Comment by jinroh** [comment]
@kwonoj indeed ! Forgot about the `where` alias.

**Comment by jinroh** [comment]
I may have to wait for #402 to backport some of those tests.

**Comment by blesh** [comment]
Merged with 4bbd4a5... thank you @jinroh!

**Pull request closed without merging**
