### PR TITLE
test(windowToggle): add test against breaking unsubscription chain

### PR DESCRIPTION
**Pull request by staltz**
For issue #875.

### CODE REVIEW

**Comment by kwonoj** [comment]
Couple of change seems need to be lint friendly :)

**Comment by staltz** [comment]
Yes, I thought `npm test` was running lint (at some point I'm sure it was, it's not anymore), that's why these leaked.

**Comment by kwonoj** [comment]
You may use `npm run build_test` instead of `test` to lint kick off. `test` itself just invokes jasmine only.

**Comment by staltz** [comment]
Yeah but `build_test` is really slow since it also compiles TypeScript.

**Comment by kwonoj** [comment]
I agree, still you have && operator at least for now. :) I always felt there might be better ergonomics instead of using npm script, but far, far away story.

**Pull request closed without merging**
