### PR TITLE
test(scan): add scalar, array micro perf test for scan operator

### PR DESCRIPTION
**Pull request by kwonoj**
- remove perf test for scan under current thread scheduler

add micro perf test for scalar, array specific for `scan` operator, also removes existing test case under current-thread-scheduler. As same as other operators like `zip` (https://github.com/ReactiveX/RxJS/pull/357), test under current thread scheduler does test over different schedulers only for sources.

### CODE REVIEW

**Comment by blesh** [comment]
You're going to need to rebase this one. I rebased it locally, but it's not passing lint. Moving on to merge the next PR if possible. (trying to get caught up)

**Comment by kwonoj** [comment]
I'll do rebase and update PR once it's satisfied.

**Comment by kwonoj** [comment]
Rebased with lint-satisfied.

**Comment by blesh** [comment]
Thank you, @kwonoj! Merged with 0b6e35e

**Pull request closed without merging**
