### PR TITLE
chore(micro-perf-runner): fix micro-perf runner to write CSV file

### PR DESCRIPTION
**Pull request by trxcllnt**
… when no other CLI args specified. fix micro-perf runner null pointer exception when run without arguments.

### CODE REVIEW

**Comment by kwonoj** [comment]
Seems I can drop partial changes in this PR at https://github.com/ReactiveX/RxJS/pull/531/files after this PR is merged.

**Comment by blesh** [comment]
@trxcllnt ... the lint bug has you.

**Comment by blesh** [comment]
I've got the lint changes done... once i"m done running the perf tests, I'll merge it.

**Comment by blesh** [comment]
Merged with 48489743b0eb94e010eb216beaa30344d9805124

Thanks @trxcllnt!

**Pull request closed without merging**
