### PR TITLE
fix(docs-app): remove stopWordFilter from lunr pipeline

### LINKED ISSUE #4524: Missing results in search
### Documentation Related To Component:

Search

### Please check those that apply

- [ ] typo
- [ ] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in example
- [ ] needs example

### Description Of The Issue

When I try to search for an operator, some are missing from the results. Like this example for `of`. 

demo

### PR DESCRIPTION
**Pull request by flakolefluk**
**Description:**
This PR removes the stopWordFilter from the lunr pipeline. It filters words like "of" and "from" when indexing, missing some operators or functions when searching.

https://github.com/olivernn/lunr.js/blob/master/lib/stop_word_filter.js

**Related issue (if exists):**
Fixes #4524

### CODE REVIEW

**Comment by JWO719** [comment]
I need to test that manually very quick. I'll do my best to do it asap. I'll let you know. But thanks for contributing!

**Comment by flakolefluk** [comment]
awesome! thanks for reviewing it :)

**Comment by ladyleet** [comment]
hi @flakolefluk !!!!!!

**Comment by ladyleet** [comment]
hey @JWO719 @benlesh - @flakolefluk  is joining our team next week!

**Pull request merged**
