### PR TITLE
chore(readme): Simplifes CDN usage directions

### PR DESCRIPTION
**Pull request by ichpuchtli**
**Description:**

**Related issue (if exists):**

### CODE REVIEW

**Comment by kwonoj** [comment]
Looks ok, but maybe (still) need to expose non-minified package as well? (https://unpkg.com/@reactivex/rxjs@5.0.1/dist/global/Rx.js)

**Comment by ichpuchtli** [comment]
Sure. I actually had that with a label saying Good for Debugging, so I will add that back.

**Comment by blesh** [comment]
Honestly, I've been using `https://unpkg.com/rxjs/bundles/Rx.min.js`

**Comment by ichpuchtli** [comment]
@blesh is it possible to selectively pull in operators using the cdn? i.e. 
```html
<script src="https://unpkg.com/rxjs/observable/observable.min.js" />
<script src="https://unpkg.com/rxjs/observable/of.min.js" />
<script src="https://unpkg.com/rxjs/operators/map.min.js" />
```
would be equivalent to
```ts
import { Observable } from 'rxjs/Observable';
import { of } from 'rxjs/observable/of';
import { map } from 'rxjs/operator/map';
```

**Comment by jayphelps** [comment]
@ichpuchtli it's not. The maintenance overhead to our build pipeline would be pretty onerous and it's already a nightmare. We make the assumption that people who care about file size should bundle--after all, patching with individual links would be pretty inefficient cause of number of HTTP requests

**Comment by jayphelps** [comment]
Updated PR to use `https://unpkg.com/rxjs/bundles/Rx.min.js` per @blesh.

We may go back and forth on this so forgive us if we do. It's still not clear when someone should use `@reactivex/rxjs` vs `rxjs` and why we need two different packages.

**Pull request merged**
