### PR TITLE
feat(bufferTime): add `maxBufferSize` optional argument

### PR DESCRIPTION
**Pull request by figueredo**
Add `maxBufferSize` to `bufferTime` as a way of implementing `bufferTimeOrCount` as discussed in #1295.

### CODE REVIEW

**Comment by blesh** [comment]
I think it would be better for our end users to allow this operator signature to be more polymorphic.

The following should work:

```
bufferTime(bufferTimeSpan);  // arguments.length === 1
bufferTime(bufferTimeSpan, scheduler);  // arguments.length === 2 && isScheduler(arguments[1])
bufferTime(bufferTimeSpan, bufferCreationInterval); // arguments.length === 2 && !isScheduler(arguments[1])
bufferTime(bufferTimeSpan, bufferCreationInterval, scheduler); // arguments.length === 3 && isScheduler(arguments[2])
bufferTime(bufferTimeSpan, bufferCreationInterval, maxBufferSize); // arguments.length === 3 && !isScheduler(arguments[2])
bufferTime(bufferTimeSpan, bufferCreationInterval, maxBufferSize, scheduler); // arguments.length === 4
```

basically, you're going to have to check the length of the arguments, and whether or not the last argument `isScheduler` in order to determine what's been passed.

**Comment by blesh** [comment]
Other than that, it looks like a solid change. Thanks @figueredo

**Comment by figueredo** [comment]
Yeah, makes much sense, I didn't think of implementing it in that way. I'll change that. Thanks for reviewing, @blesh.

**Comment by figueredo** [comment]
Updated the PR making the signature more polymorphic.

**Comment by blesh** [comment]
I was thinking on this change over this last week. I wonder if maybe RxJS needs to add the concept of buffers as a type of thing (ala js-csp). I think I'd like to put this change on hold until that's discussed.

**Comment by blesh** [comment]
@figueredo I'm unblocking this and I think we can go ahead with a merge. Sorry for the delay. Do you think you can rebase for me?

**Comment by figueredo** [comment]
@blesh I'll do it later today. What about the buffers idea (#1609)?

**Comment by blesh** [comment]
Merged with cf45540... thanks @figueredo for your contribution! Good stuff!

**Pull request closed without merging**
