### PR TITLE
chore(Observable.of): expose as standalone function

### PR DESCRIPTION
**Pull request by cburgdorf**
Adresses #1113

This is actually untested. I'm not sure if this is supposed to have a test but are happy to get any pointers :)

### CODE REVIEW

**Comment by blesh** [comment]
@cburgdorf I'm not sure what tests you could add around this at this point in time. I guess maybe some day we can have some integration tests that try to use all of the module files and the like. But for now this PR is fine.

**Comment by kwonoj** [comment]
Yes, there isn't any test cases regarding this type of changes but only manual verification would work. I can pull down and check this works (Assume there isn't no reason to not work)

**Comment by kwonoj** [comment]
I thought of just re-importing existing one to serve as alias like

`import './fromArray';`

but that's just personal - change looks ok to me. I'll check in changes once after I check it's working.

**Comment by cburgdorf** [comment]
Oh, I didn't think of that. Feel free to change the commit before merging.

**Comment by kwonoj** [comment]
@cburgdorf , just pull down pr and actually this doesn't work, not because of change in this PR but it's not compiled by compiler. TypeScript compiler can compile any file referenced but this change's alias to existing operator and not to be included anywhere, so doesn't compiled too.

couple of way to make it to work
- reference this in `Rx`, `Rx.KitchenSink` - double import `of` occurs
- update package.json, add `of.ts` in compiler

I'd go second way. Would you able to update PR?

**Comment by kwonoj** [comment]
Or I can add following commit for compiler script changes, feel freely let me know.

**Comment by cburgdorf** [comment]
Sorry, I'm not exactly sure where to add it in the `package.json`. And I'm not familiar enough with the build to test it manually myself right now. Feel free to drop the PR and introduce the change yourself. I'm not trying to sneak myself into the contributors list this way ;)

**Comment by kwonoj** [comment]
@cburgdorf I believe this change itself is quite valid, and your effort is appreciated. Then let me leverage this PR to add commit for compiler changes :)

**Comment by cburgdorf** [comment]
Thanks, sure. Whatever works well for you ;)

**Comment by kwonoj** [comment]
Merged with 1edb636, by adding one commit to allow compiler actually takes this changes.

Appreciate for taking time to create PR @cburgdorf :)

**Comment by cburgdorf** [comment]
And now that I see your changes I even learned some more bits about the project :) Collaboration as it should be :+1:

**Comment by blesh** [comment]
Awesome! Thanks again @cburgdorf!

**Comment by kwonoj** [comment]
Interestingly I'm seeing travis not able to find newly added file ('of.ts') and fail to build. I'll look this into quickly and will create fix if something's not correct with my script.

**Pull request merged**
