### PR TITLE
chore(package.json): bump up typescript version

### PR DESCRIPTION
**Pull request by kwonoj**
- bump up typescript compiler version, compile with --pretty option
- markdown test is moved to travis

Small changes to build script,
- Typescript `pretty` option
: basically this option will prints out additional detail when compile fails like below, help someone does not have editor side compiler support.
image

- markdown test is moved to travis
: markdown test doesn't necessarily need to be executed per every local unit test run, moved into travis.

### CODE REVIEW

**Comment by kwonoj** [comment]
I can check in this once got signed off.

**Comment by blesh** [comment]
This needs to be rebased. Outside of that, I'm pretty indifferent about TypeScript versions, as long as we're up to date and things build properly.

**Comment by kwonoj** [comment]
OK. I'll rebase and check this in by myself.

**Comment by kwonoj** [comment]
Merged with 836b140, this requires `npm install` to update typescript compiler.

**Pull request closed without merging**
