### PR TITLE
[Fix] Pluck overload signature

### PR DESCRIPTION
**Pull request by gund**
**Description:** With new version of typescript and new keyword `keyof` it is possible now to add type safety to the signature of `pluck` operator.

But because nature of pluck is quite dynamic it is impossible to completely describe statically return type of this operator however for single argument version it's feasible.

This change yields the next result:
```ts
const obs = Observable.of({ a: 1, b: { c: '2' } });

const a = obs.pluck('a');
// 'a' has type Observable<number> <-- This is new safer behavior

const b = obs.pluck('b', 'c');
// 'b' has type Observable<{}> <-- 2 or more arguments version still works as before

const c = obs.pluck<any, string>('b', 'c');
// 'c' has type Observable<string> <-- And it is still possible to manually specify the return type
```

Thanks

### CODE REVIEW

**Comment by kwonoj** [comment]
As I suggested in https://github.com/ReactiveX/rxjs/pull/2895#issuecomment-333949400, I'd like to hold off changes to `next` branch for a moment to prevent diverge between 2 branches. It is already quite diverged and we expect huge number of merge conflict resolving. Do you feel this is urgently reviewed and checked in?

**Comment by gund** [comment]
I just saw that you merged my previous PRs so thought that it's okay now to make new PR =)
Anyway this is not urgent so take your time.
Thanks

**Comment by benlesh** [comment]
Yeah... @gund, we have a really nasty merge coming up that I'm setting aside some time to do. After that, we're going to move `next` to `master` and press onward. But first, we need to get 5.5 out

**Comment by benlesh** [comment]
@gund ... sorry for the long delay. Would you like to update this PR (probably just create a new one) with the same changes to our pipeable version of `pluck`? (heh... "pipeable pluck" ... that's perfectly pleasant).

cc @david-driscoll can you help out if @gund isn't able?

**Comment by gund** [comment]
Hey @benlesh, thanks for the follow up.

I will take a look into this in a few days as right now I do not have access to computer.

**Comment by gund** [comment]
Just a quick question: should this change be done in next branch or any different?

**Pull request closed without merging**
